Makefile, README.md, minimal-notebook/Dockerfile, minimal-notebook/README.md, minimal-notebook/enable_sudo.sh, minimal-notebook/ipython_notebook_config.py, minimal-notebook/notebook.conf, r-notebook/Dockerfile, r-notebook/README.md, scipy-notebook/Dockerfile, scipy-notebook/README.md
I'm submitting this PR not expecting it to get merged as-is, but as a strawman for discussion. It contains:
1. `minimal-notebook` which acts as a base image or a lightweight notebook environment in which the user can use conda to install everything
2. `scipy-notebook` for a Python 2 and 3 stack
3. `r-notebook` for an R stack
4. READMEs for each
Most package versions are pegged to allow patch level increases only to avoid breakage across Docker builds. (I've learned this the hard way.)
If this is inline with what people are thinking for this repo, follow-ons might be:
1. `all-spark-notebook` (Scala, Python, R w/ Spark 1.4.x plus Yarn and Mesos connectivity preconfigured)
2. `data-science-notebook` (needs a better name) with Python, R, Julia, Scala, Spark (Brian's request)
3. …
=> Initial stacks

minimal-notebook/Dockerfile
Noticed that r-notebook was installing ipython 3.2.1 while the base image already had 3.2.0. Updated minimal-notebook conda command to allow patch to vary.
=> Allow notebook patch release to vary

README.md, all-spark-notebook/Dockerfile, all-spark-notebook/README.md, minimal-notebook/Dockerfile, minimal-notebook/README.md, minimal-notebook/jupyter_notebook_config.py, pyspark-notebook/Dockerfile, pyspark-notebook/README.md, r-notebook/Dockerfile, r-notebook/README.md, scipy-notebook/Dockerfile, scipy-notebook/README.md
* Change minimal-notebook to install notebook=4.0*
* Change config and pem file paths for jupyter 
* Install ipywidgets in all containers that have a Python stack
* Update all READMEs to describe v3.2 and v4.0 since Docker Hub only shows one README for all tags
Doing this all in a 4.0.x branch first to check how it builds on Docker Hub under a 4.0 tag. If all goes well, will merge to master here and latest there.
=> Upgrade to Jupyter Notebook 4.0

all-spark-notebook/Dockerfile, r-notebook/Dockerfile
Workaround for issue #17.  
Force irkernel to install without deps, then install the irkernel deps. Manually built and tested locally with some notebooks to see if irkernel is minimally functional at least.
@rgbkrk OK as a workaround? IMHO, better than having 4.0 tagged images out there that are really 3.2.1. (Surprise! :tada:)
=> Prevent r-irkernel from downgrading to ipython 3.2.1

all-spark-notebook/Dockerfile, all-spark-notebook/README.md, datascience-notebook/Dockerfile, datascience-notebook/README.md, minimal-notebook/Dockerfile, minimal-notebook/README.md, minimal-notebook/start-notebook.sh, pyspark-notebook/Dockerfile, pyspark-notebook/README.md, r-notebook/Dockerfile, r-notebook/README.md, scipy-notebook/Dockerfile, scipy-notebook/README.md
* Create user jovyan with UID=1000 in the default users group in the Dockerfile
* Set group ownership of user home and conda to root to avoid 'users' group from host access when mounted
* Set stick bit on both paths so root owns subdirs too
* Change jovyan UID if NB_UID is specified and is not the default 1000
@costerwi Can you give this a shot and see if it retains what you're looking for via the NB_UID runtime env var plus fixes the problems you were correcting in your latest PRs? Meanwhile, I'm going to see if it fixes both the bash and julia kernel install problems people have reported with the current setup.
=> Create jovyan in Dockerfile, reset UID at startup

Makefile, all-spark-notebook/Dockerfile
* Copy/paste from r-notebook
* Also add PORT option to make dev target for ease of testing
Fixes #53 and #54
=> Add system prereqs for R to all-spark-notebook

all-spark-notebook/README.md, datascience-notebook/README.md, minimal-notebook/README.md, minimal-notebook/jupyter_notebook_config.py, minimal-notebook/start-notebook.sh, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md
* Remove PORT and INTERFACE env vars which can conflict with other systems (e.g., Mesos)
* Document command line pass-through to start-notebook.sh
Besides documenting how docker run args can be passed to start-notebook.sh and then through to jupyter notebook, I opted for removing, not deprecating, the redundant env vars. Justification: folks can pin to the previous build git SHA if they want to retain the env var support while master marches forward without them.
=> Remove trivial env vars, doc command line args

all-spark-notebook/Dockerfile
Allows rebuilds against git SHAs in docker-stacks
Fix #65
=> Build spark kernel from specific SHA

all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile, pyspark-notebook/Dockerfile, scipy-notebook/Dockerfile
Bump pandas to 0.17.  I had to bump scipy to 0.16 as well to satisfy conda dependencies.  I built pyspark-notebook locally:
```
Successfully built 94d9e25a74f4
```
=> Bump to pandas 0.17

datascience-notebook/Dockerfile
patsy, numba, bokeh all need upgrade to satisfy conda constraints
Ref #69, same as #71 in another image
=> Fix datascience-notebook build after pandas bump

minimal-notebook/Dockerfile
Fixes #82. Should merge after PR #84 lands.
Unfortunately, we cannot build all containers that depend on minimal at the moment because the #55 workaround is no longer viable.
=> Configure en_US.UTF-8

all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile, r-notebook/Dockerfile
Requires r-rmarkdown=0.8, r-devtools=1.9, r-tidyr=0.3 in r-notebook
Fixes #55 and makes it possible to build stacks with R again!
=> Bump r-irkernel to 0.5 to fix zmq issue

examples/make-deploy/Dockerfile, examples/make-deploy/Makefile, examples/make-deploy/README.md, examples/make-deploy/letsencrypt.makefile, examples/make-deploy/self-signed.makefile, examples/make-deploy/softlayer.makefile, examples/make-deploy/virtualbox.makefile
@jtyberg and I spent the morning hacking on this KISS automation for deploying singular docker-stack images to docker-machine controlled hosts. The included README should say it all.
This PR comes in response to various requests about how to go beyond "Great, I can run a jupyter in isolated in docker on my local machine." It's definitely not the end-all, be-all (it's based on Makefiles!), but we think it's a reasonably simple, raw example from which people can learn.
=> make-deploy example: run stacks on docker-machines

all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile, minimal-notebook/Dockerfile, r-notebook/Dockerfile
Bite the bullet and preinstall it so that plotting libs that default
to using desktop rendering just work (matplotlib, ggplot, ...)
out of the box without having to get configuration right beforehand
(e.g., %matplotlib inline ahead of matplotlib import)
Only adds ~100k to the minimal-notebook image size
=> Install libxrender1 to appease matplotlib et al.

minimal-kernel/Dockerfile
* Remove SHELL env var and leftover USER nobody
* Install wget for tini then immediately uninstall it
* Install build-essentials and python3-dev for tornado speed up
then immediately uninstall them
Before these changes:
`jupyter/minimal-kernel         e7c2515ad9b2        9bd715cba589        56 minutes ago      485.3 MB`
After:
`jupyter/minimal-kernel                            latest              206fd7939811        2 minutes ago       240.5 MB`
So the image size is cut in half. The downside is that anyone looking to extend the image (e.g., add more Python libs, add new kernels, etc.) probably needs to add build-essentials and other build deps back in. 
I think minimization is the correct path for kernel images like this one in contrast to what we did in notebook images. Here, I expect …
=> Remove build deps from minimal-kernel image

minimal-kernel/Dockerfile
Also change CMD vs ENTRYPOINT to match what minimal-notebook
and some major official Docker images do (redis, mysql, nginx, ...)
by having the jupyter kernelgateway in the CMD, and just tini --
in the entrypoint
=> Bump kernel gateway to 0.3.1

ubuntu_14_04_locale_fix/Dockerfile
Sorry this is way overdue. Added locale fixes for ubuntu:14.04 so that we can get CI running as was mentioned here. ( https://github.com/jupyter/notebook/pull/547#issuecomment-146991682 )
Circle CI seemed like the best choice for doing CI with docker images. However, they did not allow us to change the locale. Not changing the locale caused us build issue with the `jupyter/notebook` image. Changing locale is not a problem when building on Docker Hub or locally. The image described here simply applies the needed locale change so it can act as a base image for `jupyter/notebook` and allow for CI support on that image.
ping: @parente
=> Added ubuntu:14.04 locale fix

all-spark-notebook/Dockerfile, all-spark-notebook/README.md, all-spark-notebook/kernel.json, pyspark-notebook/Dockerfile, pyspark-notebook/README.md
Should be merged **AFTER** PR #112
* Use Spark 1.6.0
* Use Apache Toree (new name/home of ibm-et/spark-kernel)
* Add missing pub key for binary
* Add SHA check for spark package download
=> Bump to Spark 1.6.0 with Apache Toree

examples/make-deploy/README.md, examples/make-deploy/letsencrypt.makefile
I ran into an issue when running through the make-deploy example: my letsencrypt certs kept getting wiped out after initial creation.  I traced it back to an issue in docker, where running `docker run` with the `--rm` option would delete any volumes attached with the `-v` option, even if they were pre-existing docker volumes.
https://github.com/docker/docker/issues/17907
It looks like the issue has been closed, but I'm not sure what version the fix is in (maybe 1.10?).
This fix is a workaround that uses temporary containers to manipulate files in the letsencrypt volume.
Also added a `CERT_SERVER` variable that defaults to letsencrypt's staging server.
=> Fix letsencrypt in make-deploy example.

datascience-notebook/Dockerfile, minimal-notebook/Dockerfile
Refresh the images with more current versions of all packages as well as using current conda and Python3.5 as the default py3 environment.
I also added h5py, which is quite useful in general and necessary to be able to run [the LIGO gravitational wave analysis notebooks](http://nbviewer.jupyter.org/urls/losc.ligo.org/s/events/GW150914/GW150914_tutorial.ipynb) out of the box.
Is it correct that this repo will automatically build the images on [docker hub](https://hub.docker.com/u/jupyter)? I did test the builds locally.
=> Update stacks to current conda, python3.5, and add h5py

all-spark-notebook/Dockerfile, pyspark-notebook/Dockerfile
Currently, we are installing Mesos for Debian Wheezy as it is not available from Debian Jessie. This adds a comment to remind us to switch to Debian Jessie once it is available.
Related: https://github.com/jupyter/docker-stacks/issues/137
=> Comment to get Mesos for Debian Jessie

.travis.yml, Makefile, all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile, minimal-kernel/Dockerfile, minimal-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile
Related: https://github.com/jupyter/docker-stacks/issues/7
This doesn't include releases or anything else at this point. All this does is tries to use Travis CI to do the builds. It also makes sure all images have been refreshed so that hopefully `Dockerfiles` that were left unchanged and don't have changed dependencies won't be rebuilt.
=> Use Travis CI

all-spark-notebook/.dockerignore, datascience-notebook/.dockerignore, minimal-kernel/.dockerignore, minimal-notebook/.dockerignore, pyspark-notebook/.dockerignore, r-notebook/.dockerignore, scipy-notebook/.dockerignore
Fixes https://github.com/jupyter/docker-stacks/issues/142
Don't think this solves our issue on Travis CI with `COPY` busting the cache, but it does avoid having the READMEs enter the context.
=> Add dockerignores

all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile, minimal-kernel/Dockerfile, minimal-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile
Related: https://github.com/jupyter/docker-stacks/issues/62
Simply empties `/var/lib/apt/lists/` of contents. This directory is repopulated on any call to `apt-get update` so it is not a problem to remove it. All it serves as is a cache. Should save a little bit more space for each image (~10MB).
Refs:
* ( http://unix.stackexchange.com/a/217371 )
* ( http://askubuntu.com/questions/179955/var-lib-apt-lists-huge-in-12-04/179992#179992 )
=> Clean apt-get list

README.md
This adds a status badge for Travis CI. Also, it will be a nice test of the build system. As a release was just completed, this should use the cache the entire way.
=> README: Add badge for Travis CI

minimal-notebook/Dockerfile
Specify `cacert=/etc/ssl/certs/ca-certificates.crt` in `/home/$NB_USER/.curlrc` so curl can locate the certificates. See Issue #153 .
=> Add cacert to .curlrc in home directory

scipy-notebook/Dockerfile
`ipython kernelspec install-self` was deprecated in 4.0. Use `ipython kernel install` aka `python -m ipykernel install` instead.
=> use current command for Python 2 kernel install

all-spark-notebook/Dockerfile
Fixes https://github.com/jupyter/docker-stacks/issues/137
Hi! It would be really useful to upgrade the Mesos client to version 0.25. The client in this notebook is old, and it does not allow to connect to newer high availability Mesos clusters, since the name of an entry in ZooKeeper changed. Also right now Mesosphere provides a Jessie package, and you should switch to that one.
I tested my branch and it works good. I would be really useful to merge this.
Cheers
Marco
=> Switch to Mesos Jessie repository, and upgrade to 0.25

all-spark-notebook/README.md, datascience-notebook/Dockerfile, datascience-notebook/README.md, minimal-kernel/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md
Fixes https://github.com/jupyter/docker-stacks/issues/165
Replaces https://github.com/jupyter/docker-stacks/pull/157
* add `.juliarc.jl` allowing Julia to locate hdf5 libraries installed by `conda` via h5py
* install HDF5 Julia package 
* update README 
This is meant to fix issue #165 .
=> Add hdf5 julia support to datascience stack

all-spark-notebook/Dockerfile, all-spark-notebook/README.md, pyspark-notebook/Dockerfile
Based on #202 but moving Toree to dev7
/cc @parente
=> Bump Spark to 1.6.1, Toree to 0.1.0.dev7

base-notebook/start-notebook.sh
When a notebook container is started (as root/sudo) with a host mount (for a different user) as work directory like
root> docker run -it --rm -v ~someuser/mynotebooks:/home/jovyan/work -e NB_UID=someuid --user=root jupyter/minimal-notebook
and the host directory ~someuser/mynotebooks does not exist, it is created on-demand by docker run but will not be writable for the notebook user, so all attempts to create a notebook will fail.
This can be avoided by adding the current directory (container work directory) to the chown call.
=> Support on-demand creation of mounted work directory

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, minimal-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile
base-notebook defines environment variables for the Conda install path and the
notebook user. However, in some instances, these locations were still hardcoded.
Let’s use the variables instead.
=> Make use of available environment variables

all-spark-notebook/Dockerfile
Resolves pbdZMQ related issues:  https://github.com/IRkernel/IRkernel/issues/303, https://github.com/zeromq/libzmq/issues/1637, https://github.com/ContinuumIO/anaconda-issues/issues/506.
This was discovered when installing the latest/master irkernel and moving to the latest docker stack tag in https://github.com/jupyter-incubator/declarativewidgets/issues/426
=> Update R version to 3.3*

base-notebook/Dockerfile
=> Update conda to 4.1.11 in base-notebook

all-spark-notebook/README.md, base-notebook/README.md, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md
This PR fixes a few broken hyperlinks and inconsistencies in README files. In particular:
* each README file contained hyperlinks for start scripts, which pointed to the `minimal-notebook` instead of `base-notebook`
* the [base-notebook README](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/README.md#jupyterhub) includes an example which references `minimal-notebook` rather than `base-notebook`
It looks like these were left over after some recent reorganization.
=> Fixed errors in READMEs

base-notebook/Dockerfile
This configures `conda` so that it should not auto-update. Instead users will need to explicitly update it.
=> Disable `conda` auto-update

scipy-notebook/Dockerfile
This upgrade allows for the HDF5 package license to be displayed from within the container.
cat /opt/conda/pkgs/hdf5-1.8.17-2/info/LICENSE.txt
=> Upgrade hdf5 and h5py conda packages

Makefile, all-spark-notebook/README.md, base-notebook/Dockerfile, base-notebook/README.md, base-notebook/start-notebook.sh, base-notebook/start-singleuser.sh, base-notebook/start.sh, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md
Refactors `start-notebook.sh` to make it easy to specify alternative container commands while retaining the special features of the docker-stacks (e.g., `GRANT_SUDO`). For example, here's how to get Jupyter Lab running in a docker-stacks image:
```dockerfile
FROM jupyter/scipy-notebook
RUN pip install jupyterlab && \
jupyter serverextension enable --py jupyterlab
CMD ["start.sh", "jupyter", "lab"]
```
The PR contains updates to all the READMEs with additional examples (e.g., IPython console, kernel gateway).
=> Add a generic start.sh script to images

base-notebook/Dockerfile
Closes https://github.com/jupyter/docker-stacks/issues/256
Includes a copy of `tini` that provides its license.
cc @tylere
=> Update `tini` to `v0.10.0`

all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile, r-notebook/Dockerfile
=> Workaround for R plotting regression

scipy-notebook/Dockerfile
Matplotlib builds a font cache the first time it's imported. By importing it during the docker build, we can avoid this:
=> Build matplotlib font cache during docker build.

base-notebook/Dockerfile
httpredir fails semi-regularly when installing lots of packages,
and will be deprecated in stretch.
Based on info from http://deb.debian.org
=> use cdn for apt

README.md, all-spark-notebook/README.md, base-notebook/README.md, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md, tensorflow-notebook/README.md
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

all-spark-notebook/README.md, base-notebook/README.md, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md, tensorflow-notebook/README.md
This uses the MicroBadger badge service. It allows prospective image users to
quickly get an idea of the size of an image from glancing at the README.
=> Add badges with image size and layers

datascience-notebook/Dockerfile, datascience-notebook/README.md
Julia 0.3 is pretty old and most Julia packages no longer support it. These commits move us to 0.5, which was released in September.
Unfortunately, none of the Debian repositories seem to support 0.5, so I have a hack to use Ubuntu's stable Julia PPA instead. I've done some moderate sanity checks (playing around with Gadfly, reading and writing HDF5 files), but it's pretty kludgey.
One option would be to stick with Julia 0.4.7, which is in the Sid repositories for Debian. I think that the changes in Julia 0.5 are major enough that we should go with 0.5... OTOH I don't actually use Julia that much so `¯\_(ツ)_/¯`.
=> Update Julia version to 0.5

base-notebook/Dockerfile
and get it from conda (conda-forge)
single-user protocol should still be compatible, so this shouldn't change supported Hub versions
=> JupyterHub 0.7

Makefile, base-notebook/Dockerfile.ppc64le, base-notebook/Dockerfile.ppc64le.patch
I'm a part of power team which does port the project to power architecture. In this case we need to have another Dockerfile. It will help to run Jupyter Notebook on power.
=> Dockerfile version for power ppc64le

tensorflow-notebook/Dockerfile
The tensorflow-notebook image currently ships TensorFlow version 0.9.0. However, the official TensorFlow website no longer carries documentations for this version. Documentations are available for versions 0.10.0, 0.11.0, and 0.12.0.
Given 0.12.0 is still in RC0 and not available in conda-forge yet, I opted for 0.11.0. I am new to TensorFlow, and I don't know how soon the release version of 0.12.0 would come out. It may be better not  updating the docker image just now. However, it would be great to have a version with  still accessible official documentations.
=> TensorFlow 0.11.0

all-spark-notebook/Dockerfile
Alternative fix for #315 to allow docker-demo-image to combine the current
datascience-notebook image which clears ~/.local directory with
all-spark-notebook.
=> Install Toree to conda env instead of user home

all-spark-notebook/README.md, base-notebook/Dockerfile, base-notebook/README.md, base-notebook/jupyter_notebook_config.py, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md, tensorflow-notebook/README.md
* Upgrade to latest debian base image
* Upgrade to Notebook 4.3
* Upgrade to Miniconda 4.2.12
* Remove USE_HTTPS env var in favor of command line options for key and cert
* Add GEN_CERT env var for generating a self-signed certificate
* Remove PASSWORD env var in favor of the new Notebook 4.3 default token auth
or the more secure a hashed password command line option
=> debian, miniconda, notebook version, option updates

all-spark-notebook/Dockerfile, all-spark-notebook/README.md
This adds spylon-kernel, a lightweight pure python scala kernel for spark.
cc @parente
=> Add spylon-kernel to all-spark

pyspark-notebook/Dockerfile
Add ca-certificates-java and prefer jessie-backports. Ref: http://unix.stackexchange.com/questions/342403/openjdk-8-jre-headless-depends-ca-certificates-java-but-it-is-not-going-to-be
=> Fix #340: Failing openjdk install

datascience-notebook/Dockerfile, datascience-notebook/README.md, r-notebook/Dockerfile, r-notebook/README.md
I've added [Hadley Wickham's `tidyverse`](https://github.com/tidyverse/tidyverse) to both the R and data science notebooks. The `tidyverse` package includes dependencies to major R packages that are frequently used in modern data analyses, including (copied shamelessly from the tidyverse README):
* `ggplot2`, for data visualisation.
* `dplyr`, for data manipulation.
* `tidyr`, for data tidying.
* `readr`, for data import.
* `purrr`, for functional programming.
* `stringr`, for strings.
* `lubridate`, for date/times.
* `modelr`, for modelling within a pipeline
* `broom`, for turning models into tidy data
The `conda` reference to `tidyverse` replaces the references to `ggplot2`, `dplyr`, `tidyr`, and `stringr`. Their version numbers remain the same as the ones previously specified in both …
=> R's tidyverse added to r-notebook and datascience-notebook

base-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
This PR changes the versions of packages such that we can easily switch to Python 3.6 later.
Once Spark 2.1.1 is released and `spylon-kernel` updated to `py36` we can change `conda` to 4.3* and profit 😄
=> Bump all the package versions

pyspark-notebook/Dockerfile
Spark 2.1.0 requires Py4J 0.10.4, not 0.10.3.
=> Bump Py4J to 0.10.4

minimal-notebook/Dockerfile
texlive-xetex provides xelatex, fixing `nbconvert failed: xelatex not found on PATH` issue
Fixes #353
=> Adds texlive-xetex package

base-notebook/Dockerfile
we could also move it down to `scipy-notebook`, if we don't want to increase the size of the base images.
@jasongrout @blink1073 @ellisonbg any (conda-packaged) extensions you think we should have available by default at the `scipy-notebook` or `datascience-notebook` level?
=> add jupyterlab 0.17 to minimal-notebook

base-notebook/Dockerfile.ppc64le, base-notebook/Dockerfile.ppc64le.patch
This PR is to fix the following issue
https://github.com/jupyter/docker-stacks/issues/377
This updates the ppc64le patch file and make build-all and make test-all succeeds post this update.
=> Updated patch file to build base-notebook Dockerfile on ppc64le

base-notebook/Dockerfile
I added the `fonts-liberation` requirement to `base-notebook`. Since it's so early in the image layers, it requires a fairly massive rebuild, which may not be desirable. On the other hand, it should solve the font issue everywhere, and it doesn't add terribly much to the image size. 
See: [Commonly Used Fonts on Debian](https://wiki.debian.org/Fonts#Commonly_Used_Fonts)
Also, FWIW, I considered using,
```sh
fc-list -f "%{file}\n" | grep .ttf | \
while read f ; \
do cp $f /opt/conda/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf; \
done
```
This copies all available `ttf`s to the `matplotlib` font directory. But, font-liberation seems like a cleaner solution.
=> Add fonts-liberation requirement, fix #372

datascience-notebook/Dockerfile
This gets close to #331, but we're not quite there. I believe the only files left in $HOME are `.curlrc` and `.ipython/profile_default/startup/mplimporthook`
@parente do you recall what the curlrc config solves and/or if it can be put in `/etc/` somewhere?
=> install Julia packages in /opt/julia

all-spark-notebook/README.md, base-notebook/README.md, base-notebook/start.sh, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md, tensorflow-notebook/README.md
Hi,
we are using jupyter in multi-tenant environment. That means that we are mounting folder with notebooks and data. These folders on host system have different permissions based on uid and gid. The problem is, that currently it allows you to specify only the uid of the user, sending NB_UID as a parameter: `-e NB_UID=1000`
It will be nice to have also the possibility to specify the gid using: `-e NB_GID=100`.
I've also added `-o` parameter to be able to specify non-unique groups.
Best,
Stanislav
=> Change GID of NB_USER to NB_GID if NB_GID is passed as a parameter

tensorflow-notebook/README.md
`initialize_all_variables` is deprecated, although it still works, and `global_variables_initializer` is the replacement.
=> Update Tensorflow example

base-notebook/start-notebook.sh, base-notebook/start-singleuser.sh
- launch singleuser if JupyterHub environment variables are detected (avoids users' need to set CMD)
- invoke start.sh in start-singleuser.sh, for consistency with notebook entrypoint (e.g. GRANT_SUDO)
=> singleuser-start adjustments

base-notebook/start.sh
This reverts commit 4b3b6697e78bd286910ccabd7cfe423592e1a841.
\#includedir is the correct syntax, not a comment
https://www.sudo.ws/man/1.8.13/sudoers.man.html#Including_other_files_from_within_sudoers
Fixes #400
=> Revert "Fix sudoers.d inclusion on debian img (fix #394)"

README.md, all-spark-notebook/hooks/post_push, base-notebook/hooks/post_push, datascience-notebook/hooks/post_push, minimal-notebook/hooks/post_push, pyspark-notebook/hooks/post_push, r-notebook/hooks/post_push, scipy-notebook/hooks/post_push, tensorflow-notebook/hooks/post_push
* Added `hooks/post_push` to tag builds with the 12-char git SHA and invoke downstream builds
* Updated the README with info about managing the build order of repositories on Docker Cloud
Note that the hooks must be replicated in every folder since every stack is independent and assumes a build root of its own folder.
Closes #215.
=> Enable master branch build-tag-push on Docker Cloud

base-notebook/start.sh
UID env is not set when launching as root, so root condition is never triggered. Use `id -u` check instead.
=> start.sh: fix check for if we are root

base-notebook/start.sh
closes #414 
Some remarks:
* This now assumes that the base image does not rename the notebook user, and keeps it `jovyan`. Is that OK?
* Like the previously existing code, I assume that the home is located in `/home/$NB_USER`. This isn't given, but out of scope of the MR
* I do not copy anything from `/home/jovyan` to the new location, assuming that the users know what they want to put in the new location.
* I am not a linux administration expert and I may be forgetting something obvious.
=> update home folder and username on startup

README.md, base-notebook/Dockerfile, datascience-notebook/Dockerfile, examples/docker-compose/bin/letsencrypt.sh, pyspark-notebook/Dockerfile
alternative to #427
Especially since we use at least one PPA, we might have an easier time tracking Ubuntu.
I haven't been able to find a really good way to choose between debian and ubuntu. Docker best practices reference debian as a good default starting point, but package support seems better on ubuntu.
=> proposal: base image on ubuntu:16.04 (LTS)

all-spark-notebook/README.md, base-notebook/README.md, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, scipy-notebook/Dockerfile, scipy-notebook/README.md, tensorflow-notebook/Dockerfile, tensorflow-notebook/README.md
Only Python 3 from now on
Implementation of first proposal in #432 
closes #432
=> Remove Python 2

base-notebook/start-singleuser.sh
DockerSpawner will stop passing these args, so make them optional before we start passing `--arg=<empty>`
=> make jupyterhub env->cli args optional

all-spark-notebook/Dockerfile, all-spark-notebook/README.md, base-notebook/Dockerfile, base-notebook/README.md, base-notebook/fix-permissions, base-notebook/start.sh, datascience-notebook/Dockerfile, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/Dockerfile, r-notebook/README.md, scipy-notebook/Dockerfile, scipy-notebook/README.md, tensorflow-notebook/Dockerfile, tensorflow-notebook/README.md
- any files the user should be able to write should have group `user-permissions` with `g+rwX`
- remove `chown` from start.sh because it is no longer needed
- add `fix-permissions` script for setting the user-writable permissions on a path
- users group is GID 100
- containers can set group with `--group-add users` if they want to run with a different uid/gid
(without -u root -e NB_UID -e NB_GID, which make this unnecessary), for instance:
docker run -u 501:501 --group-add users -it jupyter/base-notebook
Questions:
- is there a reason we need a dedicated high-gid group for this? Or can we leave it as the default `users` group 100?
closes #434
closes #395
I believe this resolves issues brought up in #188 without needing to consider the possible implications of running with gid=0
=> use groups for managing write-access to files

base-notebook/Dockerfile
Update jupyterlab from 0.27.* to 0.28.*.
This allows the current version of ipywidgets (7.0.2) to be installed.
=> Update jupyterlab to 0.28

datascience-notebook/Dockerfile
instead of appending, which causes broken R due to mismatched icu version.
gives R channel lower priority than conda-forge.
This is probably due to some package having an improper pin somewhere.
=> prepend R channel

scipy-notebook/Dockerfile
As discussed in https://github.com/jupyter/docker-stacks/issues/505
Also mentioned here: https://github.com/jupyter-widgets/ipywidgets/issues/1683#issuecomment-328952119
Docker image builded with
`docker build -t $USER/scipy-notebook -f Dockerfile .`
Image run with
```
alias ds='docker run -ti --rm -p 8888:8888 -v "$PWD":/home/jovyan/work --name scipy-notebook $USER/scipy-notebook'
ds
```
In JupyterLab mode, ipywidgets confirmed working
```
import ipywidgets
ipywidgets.IntSlider()
```
List of extension tested with
```
jupyter nbextension list
jupyter labextension list
```
=> Activate ipywidgets for JupyterLab. #505

README.md, base-notebook/start.sh, base-notebook/test/test_container_options.py, scipy-notebook/Dockerfile
Adding extra information to the main README file, for easier access to sub images.
Fix for granting SUDO to jovyan user and run bash commands.
Running:
docker run -ti --rm -p 8888:8888 -e GRANT_SUDO=yes --user root jupyter/base-notebook:033056e6d164 start.sh
Will immediately exit the container.
With the fix, the image stays in bash after granting SUDO to jovyan user.
=>  Fix for granting SUDO to jovyan user and run bash commands.

base-notebook/start.sh, base-notebook/test/test_container_options.py
=> Add /bin to sudo secure_path

base-notebook/start.sh
I ran into an issue when trying to get this to work with a NFS server which I did not have direct control over (EFS).  As part of the PersistentVolumeClaim, there is no easy way to set the UID and GID of the created directory.on the networked FS.
My only concern with this chown is that some user out there might be running jupyterhub in an odd configuration where $NB_USER is not supposed to have these exact permissions on the storage.  I think this is quite unlikely, but it is worth mentioning. 
I chronicled my experiences with working around this issue and setting up z2jh on EFS in https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/421 with @yuvipanda.
=> Support provisioned storage with incorrect permissions

base-notebook/README.md, base-notebook/start-notebook.sh, base-notebook/start-singleuser.sh
=> jupyterhub-lab support will be enabled if $JUPYTER_ENABLE_LAB is set.

base-notebook/start.sh
In order to fix the PYTHONPATH problem in pyspark-notebook, I have added PYTHONPATH to sudo command in start.sh
=> Fixing PYTHONPATH in base-notebook/start.sh

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
For details of why the PR exists see https://github.com/jupyter/docker-stacks/issues/547
The result (for all-spark-notebook in this case) is as shown down below.
The ``matplotlib`` cache (scipy-notebook) is retained as I think that is needed to avoid recalculating font cache details. I haven't aggressively removed the whole of ``.cache``, ``.conda``, ``.config`` and ``.yarn`` in case some change comes along in base images later which does need to retain something. Better to retain and deal with removing extra files later, rather than always remove everything as then later is harder to work out why files were being removed which weren't expected to be.
```
$ ls -lasR
.:
total 40
4 drwsrwsr-x 10 jovyan users 4096 Feb 16 10:59 .
4 drwxr-xr-x 10 root   root  4096 Feb 16 10:59 ..
4 -rw-rw-r-- …
```
=> Ensure directories/files under home directory are writable.

base-notebook/start.sh
changes to /etc/sudoers can be overwritten by later changes or package installs. it is preferable to place this config change into /etc/sudoers.d
=> improve secure_path modification by storing in sudoers.d

examples/source-to-image/README.md, examples/source-to-image/assemble, examples/source-to-image/run, examples/source-to-image/save-artifacts, examples/source-to-image/templates.json
This example directory contains sample builder scripts for being able to build custom notebook images using the Source-to-Image (S2I) tool. Details on the S2I tool can be found at:
* https://github.com/openshift/source-to-image
The S2I tool makes it easy to combine notebooks, data files etc., from a Git repository or local directory, with a base image. In this case the examples are using the ``docker-stacks`` images. As well as combine notebooks and data files with an image, the build scripts can also automatically install additional Python packages required by the notebooks during the image build.
The S2I tool and sample build scripts here provide similar capabilities to ``mybinder.org`` but without the complexity of having to setup any special infrastructure.  Instead you can run builds …
=> Sample builder scripts for build custom notebook images using Source-to-Image.

examples/openshift/README.md
This is a change to README for OpenShift example which shows how the Jupyter Lab interface can be enabled after the notebook has been deployed. There is no template parameter to set it at this point, but could consider adding it later so can optionally enable it at time of first deployment.
=> Add instructions for enabling Jupyter Lab interface with OpenShift deployment.

r-notebook/Dockerfile
This is another conda package which is required for some tidyverse functions (specifically, `stringr::str_view`) but not included in the `r-tidyverse` metapackage. (cf #532)
=> add r-htmltools pkg

scipy-notebook/Dockerfile
Without the extension it is not possible to use all Bokeh functionalities in JupyterLab
=> Add jupyterlab_bokeh extension

r-notebook/Dockerfile
sparklyr alone without any other spark package added to the install image. For user's who only use R and who want to access a spark cluster this is very useful.
=> sparklyr add to r-notebook

pyspark-notebook/Dockerfile
This way we can profit from pandas UDF
Please advise on the best place to install pyarrow. It's now installed in the inner layer (of this image), together with java.
=> Add pyarrow installation

minimal-notebook/Dockerfile
Netcat (nc) is often used as a tool to test socket server/client, 
and very useful to quickly get started with, f. e., Spark Streaming. 
See #583.
=> Add netcat

pyspark-notebook/Dockerfile
On my Jenkins master I am getting the following error when pulling the image:
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: Container ID 1311767953 cannot be mapped to a host ID
This is because the spark files inside the downloaded spark package are owned by user with uid: 1311767953.
Because I have docker userns enabled this id needs to be between 0 - 65535 for this feature to work. Unpacking it as root files also fixes the issue.
Some more information about the issue can be found here: https://circleci.com/docs/2.0/high-uid-error/
=> Make extracted spark files root id

scipy-notebook/Dockerfile
As conda-forge does not use the `nomkl` package, but instead uses the `blas` package to select BLAS versions, install the `blas` package and select the `openblas` implementation.
xref: https://github.com/jupyter/docker-stacks/pull/296
=> Use conda-forge's blas package w/openblas

datascience-notebook/Dockerfile
The `r` channel has been considered part of `defaults` since `conda` version `4.3.0`. So it should already be taken into consideration by `conda` installs without having to explicitly add the channel. Further the `conda-forge` channel has incorporated an ever growing, healthy stack of R packages. As such it appears all of the R packages used in this stack now come from `conda-forge` and not `defaults`. Given all of this, it seems safe to drop the `r` channel from explicit addition to the channel list.
cc @parente
xref: https://github.com/conda/conda/pull/3677
xref: https://github.com/conda-forge/staged-recipes/issues/2009
=> Drop the `r` channel

all-spark-notebook/README.md, base-notebook/start.sh, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md
Actual use cases can be:
- impose more restrictive ulimit
- cleanup user trash directory
- whitelist env variables (eg kubernetes service endpoint info removal)
=> Run additional scripts in /usr/local/bin/start-notebook.d/

scipy-notebook/Dockerfile
The `cd` command switches to the user's home directory (away from the directory we want to delete)
Then we remove the facets directory using the full path
=> Remove facets directory

scipy-notebook/Dockerfile
Update libraries in **scipy-notebook**:
* `scikit-learn=0.19*` [release notes](http://scikit-learn.org/stable/whats_new.html#version-0-19-1)
* `scikit-image=0.13*` [release notes](https://github.com/scikit-image/scikit-image/blob/master/doc/release/release_0.13.rst)
(follow up on issue https://github.com/jupyter/docker-stacks/issues/612)
=> Update scikit libraries

pyspark-notebook/Dockerfile
Added conda clean to pyspark-notebook Dockerfile. Addresses #627.
Building locally, this reduces the image size from 5.16GB -> 5.08GB (~80 MB).
=> Added missing conda clean to pyspark-notebook Dockerfile

base-notebook/start.sh
Only the top level permissions are set wrong due to kubernetes not being able to do this automatically.
This hits significant problems when the chown takes more than 30s and the pod fails to start
=> Don't chown -R a user's home directory

docs/contributing/features.md, docs/contributing/packages.md, docs/contributing/stacks.md, docs/contributing/tests.md, docs/index.rst
Work on test and community stack sections. The latter coincides with https://github.com/jupyter/cookiecutter-docker-stacks which will ultimately point to http://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html for instructions about how to use it.
=> Continued work on contributor doc

scipy-notebook/Dockerfile
As it appears that `defaults` has added `blas` without a feature, the `conda` solver appears to be prioritizing the removal of features over channel priority. As a result, we leverage `MatchSpec` here to pin the `blas` package to `conda-forge` and the `openblas` feature. This should be respected by `conda` and thus avoid switching to the incompatible `blas` package from `defaults`.
=> Use `MatchSpec` to force `blas` from `conda-forge`

base-notebook/Dockerfile, base-notebook/start.sh
This change enables ``pam_wheel`` so that execution of ``su`` can be restricted to just the ``root`` user or any users in the ``wheel`` group. By default, no users would be in the ``wheel`` group, so only the ``root`` user can execute ``su``. It is believed this will not interfere with ``sudo`` mechanism used by the image.
This is being done to partly address issues raised in https://github.com/jupyter/docker-stacks/issues/560 as raised by @minrk.
It should eliminate the current problem that when running as a random user ID which is not in the ``/etc/passwd`` file, and ``setuid`` capabilities has not been dropped for the container, that the user can run ``su`` by adding a password for a target user, by virtue of being placed in the ``root`` group as fallback when user ID has no group.
The …
=> Lock down ability to run su command.

base-notebook/Dockerfile, pyspark-notebook/Dockerfile
Redo of #658  with one extra commit to allow conda to update to that latest patch release while keeping the same major/minor as the miniconda installer.
=> Bumping up Spark and Conda to the current version

docs/using/recipes.md
Found a typo at http://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#juptyerhub, `juptyer` should be `jupyter`
=> Fix typo - Juptyer

README.md
Fixed JupyterLab launch sample command options. Option name and image version was wrong
=> Fixed README, Jupyter Lab launch sample command

base-notebook/Dockerfile, pyspark-notebook/Dockerfile
As described in issue #639, the config file is not created within the base image. As a result, setting the password in the Web interface after launching the container fails because the file cannot be found. This fix creates a default config file by running the appropriate command in a dedicated step.
When building this image, the build failed due to a timeout of the download of the Spark libraries. The Apache Mirror that was used for downloading was too slow and took more than 18min, which caused the build process to terminate after hitting the 10min timeout. I replaced it with a different official Apache Mirror that is already used in the recipes. I encourage the use of only one mirror in the whole project or fetch the closest mirror in the docker file like this:
```
curl …
```
=> Adds config file initialization and updates Apache Mirror due to timeout issue

base-notebook/start.sh
`pip` uses the directory `$XDG_CACHE_HOME/pip` for caching. If this directory exists and is writeable, all downloads are cached there, and pip will attempt to [build and cache a wheel for every package it installs](https://packaging.python.org/tutorials/installing-packages/#source-distributions-vs-wheels).
By default, `$XDG_CACHE_HOME` points to `/home/jovyan/.cache` and is not changed when `$NB_USER` is set. As a consequence, `pip` cannot cache downloads or wheels:
sudo docker run --rm --name condatest --user root -e NB_USER=$(whoami) -e NB_GROUP=$(id -ng) -e NB_UID=$(id -u) -e NB_GID=$(id -g) -p 8888:8888 -v work:$HOME/jupyterhub jupyter/scipy-notebook:621b96ed75cb start.sh pip install librosa
prints
[...]
Executing the command: pip install librosa
The directory …
=> Change XDG_CACHE_HOME when using NB_USER

base-notebook/README.md
Right now URLs simply point to the badge image source
=> point README badges to dockerhub

base-notebook/Dockerfile, scipy-notebook/Dockerfile
Updating `jupyterlab`, `hub-extension` and `jupyterlab-manager` to last versions. `jupyterlab_bokeh 0.6.2` seems to work fine with jupyterlab 0.34.
`make build-test-all` succeeded locally.
=> Update jupyterlab & extensions

base-notebook/start.sh
I had to add some hooks to the end of `start.sh` in order to hack some custom image configuration (in this case, it was some stuff that had to be done after the users got set up).  It could also be used for debugging (which would have been quite useful for me a month ago).
This is a little bit of a hackish solution, but it seems that the problem is so minimal now that it's not worth making a more heavyweight solution.  But if this is deemed useful, I can improve some more.
Still possibly needs tests.
---
- The start.sh script does different operations on users, and
sometimes one may need to do operations *after* that is done (as
opposed to /usr/local/bin/start-notebook.d/ which is run before).
This provides that possibility.  (One use case is hooks which must
be run after the users are …
=> Add a posibliity for a pre-start hook

datascience-notebook/Dockerfile
Tested by building locally with:
```
cd datascience-notebook
docker image build -t test-stack .
```
Ran locally with both classic notebooks an jupyter lab correctly showing 1.0:
```
docker container run --rm -p 80:8888 test-stack
docker container run --rm -p 80:8888 test-stack jupyter lab
```
=> Update Juilia version to 1.0.0

base-notebook/jupyter_notebook_config.py
Latest release of notebook (5.7.0) introduces bug when `c.NotebookApp.ip` is set to '*'. See https://github.com/jupyter/notebook/issues/3946 for details.
=> Update jupyter_notebook_config.py to fix bug introduced in notebook 5.7.0

all-spark-notebook/README.md, base-notebook/README.md, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md, tensorflow-notebook/README.md
Updates to README only:
* Currently clicking on the pulls & stars badges directs users to the actual button svg image source. The link should point to https://hub.docker.com/r/jupyter/minimal-notebook/.
* Add alt-text "image metadata" to microbadger badge
=> Point badges to dockerhub, add alt-text to microbadger

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, minimal-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
This changes the FROM specification in the Dockerfile to use an ARG.  This allows the base container to be overridden in scripts so that local registries may be used (for example).
=> Convert FROM specification to ARG (#727)

.travis.yml, base-notebook/Dockerfile, scipy-notebook/Dockerfile
This PR specifies the exact point release of the packages of importance in base-notebook to fix the probiem in #716. It trades off automatically upgrading to the latest point release when there's other changes in base-notebook. Those have not been frequent updates of late and this also makes it explicit when and what version of these core libraries are being used.
I'm updating to the latest version of 
@parente , ~two~ three open questions:
1. Should we be conservative and bump to the last minor release of the 0.34 release line (0.34.12) instead of the 0.35.* major release of JLab?
2. I do not understand the semantics of the jupyterlab-hubextension versioning scheme versus the jupyterhub versioning scheme. Is what I have added here compatible? Though maybe this is a question for …
=> Bump to latest point releases

docs/using/recipes.md
Adding recipe for including nbextensions (specifically spellchecker) per https://github.com/jupyter/docker-stacks/issues/675
The nbextension plugin does not cover jupyterlab, there is an option for that here https://github.com/ijmbarr/jupyterlab_spellchecker I haven't included.
Tested on Windows using minimal-notebook base image
=> Adding recipe for nbextension spellchecker for issue 675

all-spark-notebook/Dockerfile
Apache Toree 0.3.0-incubating has officially released, and this update the pip install instructions to use the proper official release.
=> Update to official Toree 0.3.0-incubating release

examples/openshift/templates.json, examples/source-to-image/templates.json
For the OpenShift deployment examples, when deployed, the Jupyter Notebook instance runs as the default service account of a project/namespace in Kubernetes. Because of the default RBAC security profile of OpenShift, the default service account has no special role and so even though the service account access token is mounted in the container and could be read by the user of the Jupyter Notebook, they can't use it for anything.
Because however the default service account of a project is used for any deployments unless a specific service account is created and used, there is a small risk that a project admin may add additional roles to the default service account to satisfy the requirements of another application. In that case, the user of the Jupyter Notebook instance could use the …
=> Disable mounting of service account token under OpenShift.

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, base-notebook/Dockerfile.ppc64le, datascience-notebook/Dockerfile, minimal-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile
References issue #776 
Removing apt-get clean commands from Dockerfiles.
Ran build against base-book with and without apt-get clean line and both came out to 738MB build.
=> Remove apt-get clean command. Unecessary on official Ubuntu images.

docs/using/selecting.md
**csharp-notebook** is a community Jupyter Docker Stack image. Try C# in Jupyter Notebooks.
The image contain more than **200** Jupyter Notebooks with C# sample code. The image is prepared to run online through mybinder.org for easy link and C# code trying.
* GitHub [github.com/tlinnet/csharp-notebook](https://github.com/tlinnet/csharp-notebook)
* Docker Hub [hub.docker.com/r/tlinnet/csharp-notebook](https://hub.docker.com/r/tlinnet/csharp-notebook)
[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/tlinnet/csharp-notebook/master) [mybinder.org/v2/gh/tlinnet/csharp-notebook/master](https://mybinder.org/v2/gh/tlinnet/csharp-notebook/master)
=> Adding link to a new Community Stack : csharp-notebook

docs/using/selecting.md
=> Replace vim by nano in the minimal-notebook documentation (fix #779)

r-notebook/Dockerfile
Updated R packages in `r-notebook` to match `all-spark-notebook` update in PR #782
```bash
r-base=3.4.1 -> 3.5.1
r-sparklyr=0.7* -> 0.9*
r-shiny=1.0* -> 1.2*
r-htmlwidgets=1.0* -> 1.2*
r-nycflights13=0.2 -> 1.0*
r-rsqlite=2.0* -> 2.1*
r-tidyverse=1.1* -> 1.2*
r-rmarkdown=1.8* -> 1.11*
```
=> Updated R packages in r-notebook to match all-spark-notebook update in PR #782

base-notebook/start.sh
`whoami &> /dev/null || STATUS=$? && true` causes STATUS to be set to an empty string when the container starts with option `--add-group="root"` resulting in both `nayvoj` and `jovyan` having `uid=1000` and `gid=100`. The first match in `/etc/passwd` wins and so the container user ends up being `nayvoj` accidentally.
Avoid this by checking that `whoami`'s `STATUS` is neither blank nor 0 before adding a new `/etc/passwd` entry
=> Fix bug where container user is "nayvoj"

datascience-notebook/Dockerfile
Updated R packages in `datascience-notebook` to match `r-notebook` packages update in PR #786
Note: only  the `rpy2` package (also updated here) is in the `datascience-notebook` and not in  `r-notebook`, **other packages are identical**. 
We should think of finding a way to help us maintain the coherence of the images between them (at least some documentation). Let me know if you have an idea.
=> Updated R packages in datascience-notebook to match r-notebook packages update in PR #786

base-notebook/start.sh
- The "done running loop" log message was inside the loop, causing it
to appear over and over again, making log quite confusing.
... I caused this in the first place.
=> Fix logging bug in run-hooks (order of logging statement)

docs/using/selecting.md
New community image living at https://github.com/umsi-mads/education-notebook.
Now we have 2 examples!!
=> Add reference to education-notebook

.gitignore, base-notebook/jupyter_notebook_config.py
Ensure `distinguished_name` is set when generating an ssl cert. Fixes master branch build regression due to change in upstream openssl conda package.
=> Generate missing openssl.cnf

datascience-notebook/Dockerfile
This is the latest stable release of Julia.
I also cleaned up the package operations and added `QuantEcon/InstantiateFromURL.jl`, which is a small utility for binding Julia dependency information to a Jupyter notebook.
Builds fine on my local machine.
=> Julia 1.0.0 => 1.1.0

base-notebook/start.sh
I noticed this when a before-notebook hook script `set -eu` and didn't unset them.  `PYTHONPATH` wasn't set, resulting in:
`/usr/local/bin/start.sh: line 105: PYTHONPATH: unbound variable`
If we dereference as `PYTHONPATH=${PYTHONPATH:-}` this problem would be avoided, without any functionality changes.  The other variables in the same place seem less likely to be unset.
=> Made variable reference PYTHONPATH safe in case of set -eu.

scipy-notebook/Dockerfile
=> Update packages in scipy-notebook

r-notebook/Dockerfile
`install_github` is an handy tool to install R packages directly from GitHub repositories (see [Putting your R package on GitHub](http://kbroman.org/pkg_primer/pages/github.html) for more information). In the `r-notebook` this method does not working.
```bash
$ R
> devtools::install_github("hadley/babynames")
```
To fix it I have bumped the version of devtools to `2.0*`, but it was still not OK. A problem related to the `tar` utility remains.
When telling R to give the content of the `TAR` environment variable this is its answer.
```bash
$ R
> Sys.getenv("TAR")
[1] "/bin/gtar"
```
Since `/bin/gtar` does not exist on the platform, it does not work.
This problem is known:
- [`install_github` fails in conda environment on Linux · Issue #4 · conda-forge/r-devtools-feedstock · …
=> devtools install_github does not work

base-notebook/Dockerfile
Sets `force_color_prompt=yes` in `/etc/skel/.bashrc` to configure color prompts when adding a new `NB_USER` at image build time. ~Sets the same key/value in `/etc/bash.bashrc` to configure color prompts when host mounting a `.bashrc` file that respects the setting at runtime.~
For #815
=> Enable color terminal in common cases

all-spark-notebook/hooks/manifest.tmpl, all-spark-notebook/hooks/post_push, base-notebook/hooks/manifest.tmpl, base-notebook/hooks/post_push, datascience-notebook/hooks/manifest.tmpl, datascience-notebook/hooks/post_push, minimal-notebook/hooks/manifest.tmpl, minimal-notebook/hooks/post_push, pyspark-notebook/hooks/manifest.tmpl, pyspark-notebook/hooks/post_push, r-notebook/hooks/manifest.tmpl, r-notebook/hooks/post_push, scipy-notebook/hooks/manifest.tmpl, scipy-notebook/hooks/post_push, tensorflow-notebook/hooks/manifest.tmpl, tensorflow-notebook/hooks/post_push
The code in this PR generates "manifest" pages for #823 and pushes them to the docker-stacks GitHub wiki. The logic repeats in every image `hooks` subfolder because DockerHub only makes the directory containing the Dockerfile being built and its subdirs available at build time (i.e., the entire git repo is not available for code sharing). We could look at using a git submodule or similar to share code, but I think it's better to keep all the folders independent with an eye toward the day we might actually split up this monorepo.
I developed the hook logic over in https://github.com/parente/sandbox/. https://github.com/parente/sandbox/wiki/sandbox-cd5ba036b204 is an example result. I'm sure there will be sur
The `post_build` hook requires a GitHub deploy key with *write access* to this …
=> [ci skip] Add package manifest support

base-notebook/start.sh, base-notebook/test/test_container_options.py
This adds logging-output for each `CHOWN_EXTRA` item, as well as mentioning `CHOWN_HOME_OPTS` and `CHOWN_EXTRA_OPTS` in output.
Added a test for `CHOWN_EXTRA`.
=> chown: add logging and a test

README.md
There is no quick and easy way to head to DockerHub to have a look at the images and download them from there. These two simple links should make that easier.
=> Add DockerHub-links to README.md

docs/using/recipes.md
As discussed in #813 
Just rebuilt everything to verify the layer bloat, 3GB is crazy. The datascience image with manpages enabled in the base image is only 2.7MB bigger than the existing image, btw.
=> Manpage recipe

docs/using/recipes.md
Instructions seemed outdated so I've updated it to use spark session.
I couldn't find a way to set hadoopConf from sparksession
Setting `aws-java-sdk` in `--packages` shouldn't be necessary since dependency resolution of `hadoop-aws` should grab the proper version, however, the version required is quite old (march 2014). I tried a newer jar but got an error that looked like [this](https://stackoverflow.com/questions/49278728/pyspark-an-error-occurred-while-calling-o50-parque)
=> Added s3 + spark session instructions

base-notebook/Dockerfile
This is a follow up to the PR https://github.com/jupyter/docker-stacks/pull/654.
That prior PR was intended to lock down a very specific corner case where the notebook images were run as an arbitrary user which had no user ID in the ``/etc/passwd``.
In that situation, the user would run with group ID of 0, since there also was no group for the unknown user ID. The prior PR removed the write access to ``/etc/group`` that had previously been added for group ID of 0 to prevent them from adding themselves to any groups, and requiring a user be in ``wheel`` group in order to run ``su``. This was to prevent a user adding a password hash into ``/etc/passwd`` for ``root`` and then using ``su`` to become root.
What has been overlooked in the prior PR, is that a user could change the primary group …
=> Disable su/sudo access unless sudo explicitly enabled for a specific user using GRANT_SUDO.

pyspark-notebook/Dockerfile
The mirror we prefer no longer has 2.4.0. Daily build has been failing.
=> Update to Spark 2.4.1

base-notebook/Dockerfile, tensorflow-notebook/Dockerfile
This PR pins the Python version to prevent Conda from downgrading (e.g. from 3.7 to 3.6). It also updates two packages, `numba` and `h5py`, to make them compatible with Python 3.7.  Fixes issue #768
=> Upgrade Python in scipy-notebook to 3.7

docs/.tx/config, docs/locale/it/LC_MESSAGES/contributing.po, docs/locale/it/LC_MESSAGES/index.po, docs/locale/it/LC_MESSAGES/maintaining.po, docs/locale/it/LC_MESSAGES/using.po, docs/locale/pt_BR/LC_MESSAGES/contributing.po, docs/locale/pt_BR/LC_MESSAGES/index.po, docs/locale/pt_BR/LC_MESSAGES/maintaining.po, docs/locale/pt_BR/LC_MESSAGES/using.po, docs/locale/zh/LC_MESSAGES/contributing.po, docs/locale/zh/LC_MESSAGES/index.po, docs/locale/zh/LC_MESSAGES/maintaining.po, docs/locale/zh/LC_MESSAGES/using.po
Until we figure out what I did wrong with the GitHub integration setup:
https://community.transifex.com/t/github-pr-goes-to-wrong-folder/366
Replaces #851, #852
=> tx pull -all manually

docs/using/specifics.md
I have changed the statement used to initialise the spark in _Python Notebook_ to keep up-to-date according to Spark docs. I have followed the same ideas as [**Spark Documentation**](http://spark.apache.org/docs/latest/quick-start.html#self-contained-applications) used for first _Hello World_ example.
=> [Doc] Change Spark Python Notebook entry point sentence

docs/contributing/translations.md, docs/index.rst, docs/maintaining/tasks.md
For #827.
@michiboo @Allanfs @Nico769 (or anyone that cares to review) would you like to see if the new "Doc Translations" page matches your experience. If there's anything else you'd like to add about how you signed up and have been using the Transifex site that other potential translators might need to know, feel free to comment on it here.
=> Draft pages about translation

Makefile, base-notebook/hooks/post_checkout, docs/.tx/config, docs/locale/en/LC_MESSAGES/contributing.po, docs/locale/en/LC_MESSAGES/index.po, docs/locale/en/LC_MESSAGES/maintaining.po, docs/locale/en/LC_MESSAGES/using.po
* Remove `msgstr` values. They were accidentally pulled from Transifex and committed during initial setup. `make gettext` properly regenerates them with `msgid`s only.
* Add `[ci skip]` to the commit messages when Travis pushes English template files to master to avoid a no-op rebuild.
* Add a hook to try to skip Docker Hub builds when `ci skip` is present in the message.
=> More translation fixes

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, base-notebook/Dockerfile.ppc64le, base-notebook/Dockerfile.ppc64le.patch, datascience-notebook/Dockerfile, docs/using/recipes.md, examples/source-to-image/README.md, examples/source-to-image/assemble, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
This PR has all of the instances I could find grepping through the files of the `-tipsy` flag on `conda clean` changed to `--all -f -y` per the discussion in issue #861.
=> Changed `conda clean` flags to `--all -f -y`

docs/using/selecting.md
I'd like to add Haskell to the list of Community Stacks, please.
this `ihaskell-notebook` Docker Stack was created using the [Community Stack contributing guide](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/stacks.html).
<https://github.com/jamesdbrock/ihaskell-notebook>
=> Community Stacks documentation ihaskell-notebook

pyspark-notebook/Dockerfile
Spark 2.4.3 has gone back to being compiled with Scala 2.11 by default. Update to that version to fix #860 and because the mirror no longer has 2.4.2 available.
https://spark.apache.org/releases/spark-release-2-4-3.html
=> Update to Spark 2.4.3

base-notebook/Dockerfile
Pin the conda version so that a call to `conda update --all` will not
cause conda to update itself to a higher version with possible breaking
changes.
Motivating example: Upgrade from __4.6.*__ to __4.7.5__ causes the build to fail
due to a conda error:
[Errno 13] Permission denied: '/.cph_tmpilpdzq7x'
Resolves #891
=> Pin conda version to $CONDA_VERSION

base-notebook/Dockerfile, scipy-notebook/Dockerfile
When rebased on top of https://github.com/jupyter/docker-stacks/pull/894 , this commit will cause *docker-stacks* to pass the `make build-test-all` CI check for *JupyterLab 1.0.0*.
=> jupyterlab_bokeh@1.0.0 (rebase on PR #894) for JupyterLab 1.0.0

base-notebook/Dockerfile, scipy-notebook/Dockerfile
The hub-extension's functionality has been merged into JupyterLab itself.
=> Bump JupyterLab and remove hub-extension.

r-notebook/Dockerfile
The e1071 R package is a dependency of functions within the caret package. Without it, `caret::train` (for example) cannot be run. This pull request addresses issue #889 (https://github.com/jupyter/docker-stacks/issues/889). 
note - I first tried installing e1071 in the RUN command started on line 27 but that resulted in e1071 not installing (don't know why) but adding an additional RUN command led to succesful installation... So I just went with it.
=> Added install of e1071 R package

scipy-notebook/Dockerfile
Using a dev build, vendors~main.js is 35.4 MB.  With the prod build it is only 5.0 MB.  This makes a huge difference in load times for non-local sessions.  For more details, see the links in https://github.com/jupyterlab/jupyterlab/issues/6869 .
=> Use prod instead of dev build for JupyterLab

scipy-notebook/Dockerfile
Based on [this discussion](https://github.com/jupyter/docker-stacks/pull/896#issuecomment-515792038).  It seems to work, but I have not tested it thoroughly.
=> Switch to matplotlib-base to avoid qt dependency

all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile
- This would have made updating all package versions easier, so doing it now.
- Differences I noticed:
- r-notebook and datascience-notebook are almost identical
- r-notebook has r-odbc and unixodbc, datascience-notebook doesn't
- all-spark-notebook has r-ggplot2 explicitely added and version
pinned.  The others pull it in but isn't version pinned.
- I'm conflicted as to if I should skip the CI on this, but since it's
not pure text changes I won't.
=> Sort package installation lines alphabetically for easier comparison

docs/using/selecting.md
Added sage-notebook as per https://github.com/jupyter/docker-stacks/blob/master/docs/contributing/stacks.md
=> Add link to sage-notebook Community Stack

base-notebook/Dockerfile
Update Miniconda to 4.7.10 and conda to 4.7.12 also use a env variable to set the miniconda MD5
=> Update Miniconda to 4.7.10 and conda to 4.7.12

base-notebook/Dockerfile, base-notebook/Dockerfile.ppc64le, minimal-notebook/Dockerfile
This PR removes the `apt-get dist-upgrade` from the build  process of the base-notebook image, as per the [dockerfile best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices).
Upgrading the base image, especially without being able to specify package versions, can break dependencies, reproducibility of builds, and can significantly enlarge the final image.
I also added a call to `apt-get clean` after package installations: this command will remove any debs files left in apt-get's cache.
=> Don't upgrade base image

base-notebook/Dockerfile
Make the `fix-permissions` script executable by everyone, avoiding permission denied error when `NG_UID` isn't root and doesn't match the file's owner or group id.
=> Make fix-permissions executable by all

scipy-notebook/Dockerfile
Reverts a temporary workaround included in [this commit](https://github.com/jupyter/docker-stacks/commit/eb5c77ee43c8ee193f34c8e23ac3568f1f3f2578#diff-90dd1590ae70de58d60090b55b7ee318), which addressed [this issue](https://github.com/jupyterlab/jupyterlab/issues/6869) which has subsequently been fixed.
=> With JupyterLab 1.1, --dev-build=False is no longer necessary.

tensorflow-notebook/Dockerfile
Conda currently does not have tf2 as can be seen in [url](https://anaconda.org/conda-forge/tensorflow/files) 
I used pip installation
=> upgrade to tensoflow2

docs/using/recipes.md
Add a recipe that we can more easily link into issues asking for the sudo password than we can the section describing the `GRANT_SUDO` env var.
Fixes #949
=> Add sudo recipe

base-notebook/Dockerfile
This allows configuring the python version installed in the base dockerfile, allowing others to replicate images provided by docker stacks with other python versions.
Extending the base image rather than running `conda install` in a child container allows for containers with small file sizes without the need to perform destructive squashing operations.
=> Configure Python Version with Build Arg

base-notebook/Dockerfile
Twistlock vulnerability scanning showed OS issues removable by upgrading of package versions.
=> Update ubuntu base image.

datascience-notebook/Dockerfile
This just updates two lines to have the build pull down Julia 1.3.1 (Most current as of Dec 30 2019). The first is the variable JULIA_VERSION, the second is the associated checksum for the tar.gz file.
=> Update to Julia 1.3.0

base-notebook/Dockerfile
JupyterHub 1.1.0 just landed, so I figured I'd go ahead and bump it in the base-notebook image. While doing so I bumped the patch version of `notebook` and `jupyterlab` as well.
I have now ignored the seemingly unmaintained Dockerfile.ppc64le and Dockerfile.ppc64le.patch.
=> Bump: notebook (6.0.0 > 6.0.2), jupyterhub (1.0.0 > 1.1.0), jupyterlab (1.2.1 > 1.2.5).

base-notebook/start.sh
In reference to jupyter#975.
Changes
```
mv /home/jovyan "/home/$NB_USER"
```
to
```
mv /home/jovyan "/home/$NB_USER" || ln -s /home/jovyan "/home/$NB_USER"
```
to fall back on a symlink for the home directory in the case that mv fails. mv can fail for some volume mounting options. (This was originally documented for AWS EBS-backed volume when running JupyterHub on Kubernetes.)
=> Fall back on symlink if mv fails

all-spark-notebook/hooks/post_push, datascience-notebook/hooks/post_push, minimal-notebook/hooks/post_push, pyspark-notebook/hooks/post_push, r-notebook/hooks/post_push, scipy-notebook/hooks/post_push, tensorflow-notebook/hooks/post_push
New Docker Hub UI loses newlines in the env var settings. Loss of new lines leads ssh-add to prompt and fail when loading the key.
Base64 encode and decode the key to workaround the limitation.
🤞 the Docker Hub build env has the `base64` command line tool.
=> Fix ssh deploy key format

Makefile, all-spark-notebook/Dockerfile, datascience-notebook/Dockerfile
Bump version of R packages in `datascience-notebook` and `all-spark-notebook` focusing mainly on R Base `3.6.2` and Sparklyr `1.1`.
Notes: 
- I've not intentionally updated `r-notebook` since it's deprecated -> #693
- I do not know why `r-sparklyr` is installed in the `datascience-notebook` since Spark is not installed. I think it could be removed however I've not done it yet, I will create a dedicated issue for that.
```R
library(sparklyr)
sc <- spark_connect(master = "local")
```
Also added two new targets in the `Makefile` that I find handy to quick debug and check in the images
- `run`: run a bash in interactive mode in a stack
- `run-sudo`:  run a bash in interactive mode as root in a stack
So for example
```bash
$ make run/all-spark-notebook
docker run -it --rm …
```
=> Bump version of R packages

datascience-notebook/Dockerfile
Hello,
`r-sparklyr` was installed in the `datascience-notebook` but Spark was not installed. So IMHO this does not make sense -- I figured this out during the PR #1000 .
```R
library(sparklyr)
sc <- spark_connect(master = "local")
```
So, I've simply removed it.
Best.
=> Remove sparklyr from datascience notebook

Makefile, base-notebook/test/test_container_options.py, conftest.py, pyspark-notebook/Dockerfile, pyspark-notebook/test/test_spark.py, pytest.ini
Hello,
- The Spark version `2.4.4` is no more available from the mirror (http://mirrors.ukfast.co.uk/sites/ftp.apache.org/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz) -> bump version to `2.4.5`
- Add one (dumb) test to check if Spark is running properly
- Add `/usr/local/spark/bin` to the `PATH` in order to be able to run Spark commands (`spark-shell`, `pyspark`, etc.)
Misc
- Fix the `test/%` command in the `Makefile`
- Add a test `test_chown_home` to check the behavior of the `CHOWN_HOME` option (see #1003)
- Configure a logger along with a `pytest.ini` file to set its behavior      
Best
=> Bump to spark 2.4.5 + minor improvements

pyspark-notebook/Dockerfile
Hello,
I've noticed that the `pyspark-notebook` build was often failing after 10 min with the following message.
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
I've checked and it was due to the performance of the previous mirror (http://mirrors.ukfast.co.uk/sites/ftp.apache.org/spark/). I've made a test and my browser estimated the download time at more than 25 min.
So I have used the official site to grab the preferred mirror (https://www.apache.org/dyn/closer.lua/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz).
```bash
$ wget -qO- https://www.apache.org/dyn/closer.lua/spark/spark-2.4.5/spark-2.4.5-bin-hadoop2.7.tgz\?as_json
```
Then, by parsing the JSON we can get the full URL and use it …
=> Use the preferred spark download mirror

docs/contributing/features.md, docs/contributing/packages.md, docs/contributing/tests.md
Hello,
Just fixed the **contributing documentation** to use the correct `Makefile` target `build` instead of `image`:
```bash
make image/somestack-notebook -> make build/somestack-notebook 
```
Best.
=> Fix contributing doc make image -> make build

base-notebook/test/test_pandoc.py, minimal-notebook/Dockerfile, minimal-notebook/test/data/notebook1.ipynb, minimal-notebook/test/test_nbconvert.py, pytest.ini
Hello,
I've noticed that `pandoc` was installed 2 times. It's installed in the `minimal-notebook` as a `conda` package, then in the `minimal-notebook` as an OS package.
```bash
$ which pandoc
$ find / -name pandoc
$ ls -alsh  /opt/conda/bin/pandoc /usr/bin/pandoc
```
So I've removed the OS package installation from the `minimal-notebook` and written a test on the `base-notebook` to check that `pandoc` is working without this package. I've also performed a manual export to PDF test in a `minimal-notebook`.
It will contribute to slightly reduce the size of this image (same effect on downstream images as well).
Here is comparison
```bash
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
jupyter/minimal-notebook   latest              a817cb6de443 …
```
=> Remove installation of unnecessary pandoc and tex OS packages

docs/using/selecting.md
Based on #1023 and #1001 , the [GPU-Jupyter](https://github.com/iot-salzburg/gpu-jupyter) is added as community stack into docker-stacks.
=> Added GPU-Jupyter in selecting.md community stacks

base-notebook/Dockerfile, r-notebook/Dockerfile
I'm thinking of speeding up conda (because it's really slow) either during the build of the stacks and for the user when they want to install additional package.
> As of version 4.6.0, Conda has a strict channel priority feature. Strict channel priority can dramatically speed up conda operations and also reduce package incompatibility problems. We recommend it as a default. However, it may break old environment files, so we plan to delay making it conda's out-of-the-box default until the next major version bump, conda 5.0.
>
> -- <cite>https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html#strict</cite>
As we prepend `conda-forge` channel, I think the impact could be limited since I think the goal is to privilege `conda-forge` packages.
> With strict channel …
=> Turning channel priority to strict

docs/using/selecting.md
cgspatial-notebook is a community Jupyter Docker Stack image. The image includes major geospatial Python & R libraries on top of the datascience-notebook image
=> cgspatial-notebook

scipy-notebook/Dockerfile
Bump `scipy-notebook` to the latest versions of packages.
See also #1014 and #1024 .
```
$ make check-outdated/scipy-notebook
```
=> Bump scipy-notebook

base-notebook/Dockerfile
I am building a custom container by using the base-notebook/Dockerfile and overriding BASE_CONTAINER from the command line. My base image has additional software installed in /opt. The dockerfile is trying to fix permissions on the entire /opt tree, which blows up the image size. Is it OK to limit the fix permissions to /opt/conda?
=> limit fix permissions to /opt/conda

docs/using/selecting.md, scipy-notebook/Dockerfile
I am proposing to allow the use of ipympl widgets as raised in  #955 
I thought these simple additional packages and build commands would suffice, but somehow it does work. This PR functions correctly within jupyter notebooks, but it does not work with jupyterlab. The cell only responds by returning ‘Loading widget…’ , but it never loads anything. 
Do not merge this!
=> Try to get ipympl working

docs/using/recipes.md
Added a reference in order to bring more information on recipes about running containers as `root` as highlighted in the issue #608.
Best
=> Recipes documentation: running container as root more information

Makefile, docs/contributing/packages.md, pytest.ini, requirements-dev.txt, test/helpers.py, test/test_outdated.py
Hello,
I propose to integrate a feature--still experimental at this time-- in order to help identifying which packages can be updated. It could be useful in the frame of maintaining stacks up to date (see #1014). It could be part of the [Package Update documentation](https://jupyter-docker-stacks.readthedocs.io/en/latest/contributing/packages.html) documentation.
It's implemented as a test that is run through a specific command. It's skipped by default when running standard tests through `make test/<stack>`--however I can be integrated if we think it could be useful in the test context.
The principle is to call a specific entry `make check_outdated/<stack>` in the `Makefile` to get a report of the packages that can be updated.
```bash
$ make check_outdated/base-notebook
```
It's a very …
=> Conda outdated package helper

base-notebook/Dockerfile, scipy-notebook/Dockerfile
This version update fixes issue #1038 by updating jupyterlab and the jupyter-matplotlib and bokeh extensions.
=> update jupyterlab and plotting extensions

base-notebook/start-singleuser.sh
As stated on https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html
> JupyterHub users should use the c.Spawner.default_url = '/lab' setting instead of the deprecated and now removed labhubapp (#7724)
I removed the check for the JUPYTER_ENABLE_LAB in start-singleuser.sh as it is not necessary to call `jupyter labhub` anymore. The environment variable is still used in start-notebook.sh to determine whether the jupyter process should be started with argument `lab` instead of `notebook`, so it is not necessary to update the documentation.
=> Fix #1041: Update JupyterLab start command

Makefile, test/helpers.py, test/test_packages.py
This test module tests if R and Python packages installed can be imported.
It's a basic test aiming to prove that the package is working properly.
The goal is to detect import errors that can be caused by incompatibilities between packages for example:
- #1012: issue importing `sympy`
- #966: isssue importing `pyarrow`
This module checks dynmamically, through the `CondaPackageHelper`, only the specified packages i.e. packages requested by `conda install` in the `Dockerfiles`.
This means that it does not check dependencies. This choice is a tradeoff to cover the main requirements while achieving reasonabe test duration.
However it could be easily changed (or completed) to cover also dependencies `package_helper.installed_packages()` instead of `package_helper.specified_packages()`. …
=> Test packages

scipy-notebook/Dockerfile
This responds to #1043 adding the dvipng packaged used by matplotlib to render latex.
I don't think this requires an update for the docs since this tends to only outline the python packages, but a note could be added if needed.
=> include dvipng

scipy-notebook/Dockerfile
As discussed in #752 , just replaced a `rm` by a call to `jupyter lab clean` for clarity reasons.
The result is the same the `$CONDA_DIR/share/jupyter/lab/staging` is removed.
=> Using jupyter lab clean command instead of rm (#752)

base-notebook/Dockerfile
Hello,
Try the latest `Miniconda` / `conda` version `4.8.2`. I've only tested `base-notebook` :fearful: ...
I've noticed that, since this version, Miniconda is provided in two Python versions
- `Miniconda3-py37_4.8.2-Linux-x86_64.sh`
- `Miniconda3-py38_4.8.2-Linux-x86_64.sh`
I've kept Python `3.7.x`, one change at a time :relieved:.
Please note that I've not used an `ARG` or an `ENV` to switch between the two Python versions (`py37` / `py38`). We have already `conda` and Python versions in the file.
> Perfect is the enemy of good.
But I can dot it, if someone think it's better.
Best.
=> Bump miniconda -> 4.8.2

docs/using/recipes.md
`conda env create` is only to create environment from a `YAML` file.  Fixed the command in "Add a Python 3.x environment" to use `conda create` instead.
-> [Reference](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)
=> [DOC] #1060 Fix conda command to create env

docs/using/selecting.md
* Fix a sentence saying that `pandoc` is not installed on `base-notebook` #1013
* Precision on emacs installation (`emacs-nox`) #1059
* Dask added to `scipy-notebook` image documentation
=> [DOC] Selecting image doc minor fixes

docs/using/selecting.md
Change the Community Stacks ihaskell-notebook Binder urlpath to the revived IHaskell.ipynb notebook.
=> ihaskell-notebook binder urlpath

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, datascience-notebook/test/test_julia.py, r-notebook/Dockerfile, scipy-notebook/Dockerfile
* Bump `base-notebook`
* OS version
* `jupyterlab`
* Bump `scipy-notebook`
* `beautifulsoup4`
* `cloudpickle`
* `dask`
* ~`numba`~
* `xlrd`: version specified (it was not the case)
* Bump `datascience-notebook`
* `r-devtools`
* `r-forecast`
* Julia version
* Test added to check if Julia is correctly installed (`julia --version`)
* Note: A new version of `r-base` is out `4.0.0` however it cannot be installed yet since dependencies with other packages cannot be resolved.
* Bump `r-notebook`
* Same as `datascience-notebook` except Julia.
* Bump `all-spark-notebook`
* `r-sparklyr`
Dependencies resolution fails with `numba` `0.49`. I do not know the root cause.
Here is the difference between the two versions.
```bash
$ conda search --info numba
numba 0.48.0 py36hb3f55d8_0 …
```
=> Regular update 2020 W18

tensorflow-notebook/Dockerfile
Before image size was 5.21GB, after fix: 4.78GB - ~430MB saved.
=> Use pip --no-cache-dir to install tensorflow

CONTRIBUTING.md
The best links connects a linking object and its text occurrence, e.g. the link to documentation is near documentation's occurrence in the text. Since no explicit link to the guide the guide text font became bold but link to the docs moved to doc's text occurence
=> CONTRIBUTING.md misleading link to guide

all-spark-notebook/test/data/local_pyspark.ipynb, all-spark-notebook/test/data/local_sparkR.ipynb, all-spark-notebook/test/data/local_sparklyr.ipynb, all-spark-notebook/test/data/local_spylon.ipynb, all-spark-notebook/test/data/local_toree.ipynb, all-spark-notebook/test/test_spark_notebooks.py, docs/using/specifics.md
Some changes to the Spark documentation following the PR #911
for local and standalone use cases with the following drivers
* Simplify some of them (removing options, etc.)
* Use the same code as much as possible in each example to be consistent (only kept R different from the others)
* Add Sparklyr as an option for R
* Add some notes about prerequisites (same version of Python, R installed on workers)
Best
=> Follow-on PR #911: Spark documentation rework

docs/contributing/features.md, docs/contributing/packages.md, docs/contributing/stacks.md, docs/contributing/tests.md, docs/using/common.md, docs/using/recipes.md, docs/using/specifics.md, examples/docker-compose/README.md, examples/make-deploy/README.md, examples/openshift/README.md, examples/source-to-image/README.md
Fixed some issues:
1. Added ```dockerfile (bash, python) - it makes it look more beautiful on github (especially dockerfile)
2. When using a list, it's better to indent all the ```s
=> Improve documentation

base-notebook/start.sh
Suppress `id: jovyan: no such user` stderr output when determining whether to override user/group info. This aligns it with the rest of the startup script, which already suppresses this.
=> suppress "id: jovyan: no such user" message during start

base-notebook/Dockerfile
Upgrading:
Ubuntu to ubuntu:focal-20200606
Miniconda to 4.8.3
Jupyterlab to 2.1.5
=> Upgrading Ubuntu, miniconda and jupyterlab

minimal-notebook/Dockerfile
`texlive-fonts-extra` seems not be be a requirement of `nbconvert`.
Reduces the image size by ~ 1.3 GB which will affect all images that build on the `minimal-notebook` image.
```bash
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
minimal-notebook-nofonts      latest              9641ee9dd31c        3 minutes ago       1.7GB
minimal-notebook              latest              e23d7794a410        14 minutes ago      3.01GB
```
I opened a [issues ](https://github.com/jupyter/docker-stacks/issues/1129)questioning if there is any reason to keep this package. See also the comment [here](https://github.com/jupyter/docker-stacks/pull/1013#discussion_r379897106) in [PR 1013](https://github.com/jupyter/docker-stacks/issues/1129).
So this PR closes …
=> Removed optional texlive-fonts-extra

.github/workflows/docker.yml, .github/workflows/sphinx.yml
Job results are not accessible to other jobs within a workflow unless [the job stores them as artifacts](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts). Instead of introducing that complexity, this PR combines the build and deploy docker image jobs into one, with the deploy steps guarded by a conditional that evaluates true for the master branch only. The PR combines the Sphinx build and gettext jobs in a similar manner.
=> Combine jobs within workflows

Makefile
I copy/pasted commands from the `.travis.yaml` without correct for Makefile syntax and capability.
=> Fix git-commit var syntax

.github/workflows/docker.yml, .github/workflows/sphinx.yml, Makefile
I forgot I was in make-land when using `cd` in the `git-commit` target. This afforded me the opportunity to fix the `ci skip` support which was not configured correctly for PRs.
=> [ci skip] Fix wiki commit, 'ci skip' support

all-spark-notebook/README.md, base-notebook/README.md, datascience-notebook/README.md, minimal-notebook/README.md, pyspark-notebook/README.md, r-notebook/README.md, scipy-notebook/README.md, tensorflow-notebook/README.md
We shows these READMEs on Docker Hub. Note that the images are now built on GitHub Actions and link to the GitHub project.
=> [ci skip] Update stack READMEs

Makefile
Pushing to the wiki is still failing. The push is going to `jupyter/docker-stacks` instead of `jupyter/docker-stacks.wiki`. Adding an echo and splitting an overly long bash line to debug.
=> Debug info for wiki push failure

.github/workflows/docker.yml
`GITHUB_REPOSITORY` is a built-in env var for GitHub Actions. We cannot override it via env vars when trying to push to the wiki repo. Pass the desired value directly on the command line instead.
=> Fix GITHUB_REPOSITORY value

.pre-commit-config.yaml, examples/docker-compose/notebook/Dockerfile, examples/make-deploy/Dockerfile
- Exclude `ppc64` `Dockerfiles` from the linting in pre-commit since we cannot check their build easily and so fix the lint errors without breaking something (already excluded in the `Makefile`)
- Fix examples `Dockerfiles` to invert root and jovyan user instructions ("Last user should not be root" `DL3002`)
Best
=> Resolve Docker lint (hadolint) errors

docs/using/specifics.md, pyspark-notebook/Dockerfile
Allow to build `pyspark-notebook` image with an alternative Spark version.
- Define arguments for Spark installation
- Add a note in "Image Specifics" explaining how to build an image with an alternative Spark version
- Remove Toree related documentation from "Image Specifics" since its support has been dropped in #1115
It resolves to the following issues:
- #626
- #1145 
Best
=> Resolves #1131: Allow alternative Spark version

base-notebook/start.sh
Starting the container with `--user root`, as indicated by the [Docker Options section of the docs](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#docker-options) in conjunction with a script using the `start-notebook.d` or the `before-notebook.d` hooks that set a custom`NB_UID`, `NB_UID`, and using the standard `NB_USER` (jovyan) environment variables results in the container exiting stating that the groupadd failed because the `jovyan` group already exists.
This fix adds the `-f` flag to the `groupadd` command to either add the [group if it doesn't exist or exit gracefully if it does exist](http://manpages.ubuntu.com/manpages/cosmic/man8/groupadd.8.html).
Another viable option is to use `groupadd --gid $NB_GID --non-unique ${NB_GROUP:-${NB_USER}}` as done in PR …
=> Add -f option with groupadd to gracefully exit when adding existing groups

base-notebook/Dockerfile, datascience-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
Following images updated
Updated
- Ubuntu
- `notebook`
- `jupyterlab`
- `conda`
Improved the way Miniconda is installed to
- enable overriding defaults by using arguments
- permit to install a different version of `conda` than the default provided in the Miniconda installer
Updated
- `bokeh`
- `cloudpickle`
- `dask`
- `matplotlib-base`
- `protobuf`
- `seaborn`
- `statsmodel`
Dropped `hdf5` installation specification since it's a dependency of `h5py`.
Updated
- `tensorflow`
Updated
- `r-forecast`
- `r-htmltools`
- `r-rmarkdown`
- `r-shiny`
- `rpy2`
- Julia 
Improved the way Julia is installed to enable overriding Julia version by using arguments.
Failed to update
```bash
Package          Current    Newest
---------------  ---------  --------
r-base       3.6.3      4.0.2
```
Updated
- …
=> Stack update

base-notebook/Dockerfile
Some conda packages rely in the `conda activate` to set the corresponding environment variables, therefore just including the `bin` directory in the `PATH` is not sufficient.
=> Activate conda base environment by default

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, docs/using/selecting.md, minimal-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
The following changes have been made.
- `base-notebook`
- `Changed`: Bump Ubuntu
- `Changed`: Bump conda
- `Fixed`: Add missing `apt-get clean`
- `scipy-notebook`
- `Fixed`: Add missing `apt-get clean`
- `Changed`: Bump `dask`
- `Changed`: Bump `protobuf`
- `r-notebook`
- `Changed`: Bump `r-base`
- `Changed`: Bump `r-rmarkdown`
- `Removed`: The description of `tidyverse` packages because it's not the place to do that and it will always be obsolete.
- `datascience-notebook`
- `Changed`: Bump `r-base` to `4.0.x` see #1102 (partial)
- `Removed`: `plyr` package because it's retired fixes #1103
- `Removed`: `r-reshape2` package because it's retired fixes #1103
- `Changed`: Bump `r-rmarkdown`
- `Changed`: Bump Julia
- `tensorflow-notebook`
- `Changed`: Bump `tensorflow`
- `pyspark-notebook`
- …
=> Update docker stacks 2020-11-20

docs/using/recipes.md
By default, [Dockerfile's `COPY` creates files and directories with UID and GID 0](https://docs.docker.com/engine/reference/builder/#copy). When we put them in `jovyan`'s `$HOME` or want `jovyan` to manipulate these files, they should be owned by `jovyan` instead.
Specifically [recipe "Add a Python 3.x environment"](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipes.html#add-a-python-3-x-environment) failed with a "permission denied" error when the code for using an `environment.yml` file was un-commented. I assume some of the other recipes might have failed like that, too, but I didn't test them.
(I didn't make this change for [recipe "Use jupyter/all-spark-notebooks with an existing Spark/YARN cluster"](https://jupyter-docker-stacks.readthedocs.io/en/latest/using/recipe …
=> recipes: use COPY with --chown for jovyan's files

minimal-notebook/Dockerfile
/usr/bin/nano-tiny does not exist, the good path is /bin/nano-tiny on ubuntu 18.04 and 20.40 (https://ubuntu.pkgs.org/20.04/ubuntu-universe-arm64/nano-tiny_4.8-1ubuntu1_arm64.deb.html).
=> /usr/bin/nano-tiny does not exist

Makefile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile
The following changes have been made.
- General
- `Changed`: Bump hadolint (Docker linter)
- `Changed`: Use Jupyterlab by default when using `make dev`
- `base-notebook`
- `Changed`: Bump Ubuntu
- `Changed`: Bump jupyterhub
- `Changed`: Bump jupyterlab
- `r-notebook`
- `Changed`: Bump `r-rmarkdown`
- `datascience-notebook`
- `Changed`: Bump `r-rmarkdown`
- `pyspark-notebook`
- `Change`: Bump `pyarrow`
=> Regular update 2020-11-05

docs/using/selecting.md
Including `kotlin-notebook` link and description in `docs/using/selecting.md` community stacks list.
[kotlin-notebook](https://github.com/knonm/kotlin-notebook) is a community Jupyter Docker Stack image. The image includes [Kotlin kernel for Jupyter/IPython](https://github.com/Kotlin/kotlin-jupyter) on top of the `base-notebook` image.
=> Adding kotlin-notebook to community stacks list

base-notebook/start.sh, base-notebook/test/test_container_options.py
There's a bug in the `start.sh` that causes a crash when starting a notebook with `NB_USER=<username>` and `CHOWN_HOME=yes` environment variable. For example:
```
$ mkdir -p pr/base
$ cd pr/base
$ git clone https://github.com/jupyter/docker-stacks.git
$ cd docker-stacks
$ make build/base-notebook
$ docker tag jupyter/base-notebook:latest jupyter/base-notebook:base
$ docker run -e NB_USER=steven -e CHOWN_HOME=yes --user root jupyter/base-notebook:base
Set username to: steven
Changing ownership of /home/steven to 1000:100 with options ''
chown: cannot access '/home/steven': No such file or directory
```
This happens because `chown` gets called in  `start.sh` before moving/creating the directory `/home/$NB_USER`: https://github.com/jupyter/docker-stacks/blob/master/base-notebook/start.sh#L50- …
=> [Bug fix] Create home directory before changing ownership

base-notebook/Dockerfile, docs/using/common.md, docs/using/selecting.md, test/helpers.py, test/test_packages.py
Hello,
I'm _trying_ to perform a structuring change by switching from [Miniconda](https://docs.conda.io/en/latest/miniconda.html) installer to [Miniforge](https://github.com/conda-forge/miniforge).
> This repository holds a minimal installer for conda specific to conda-forge.
Here are the main reasons
* Switch to **open source** since Anaconda has recently updated its [TOS](https://www.anaconda.com/terms-of-service) to restrict commercial usage of its repositories (including the repo hosting Miniconda installers) -> This could impact users of Jupyter Docker images
* It's built to use `conda-forge` channel by default
* it is the channel we are using that is not restricted
* there is no need to prepend it anymore
* other [default channels](https://repo.anaconda.com/pkgs/) that are concerned …
=> Switch from Miniconda to Miniforge

docs/using/specifics.md, pyspark-notebook/Dockerfile, pyspark-notebook/test/test_spark.py
Spark installation improved by sourcing the `spark-config.sh` in the `before-notebook.d` hook that is run by `start.sh`. It permits to add automatically the right Py4J dependency version in the `PYTHONPATH`. So it is not needed anymore to set this variable at build time.
Documentation describing the installation of a custom Spark version modified to remove this step. Also updated to install the latest `2.x` Spark version.
`test_pyspark` fixed (was always OK before that).
Best
=> Improve spark installation

Makefile, all-spark-notebook/Dockerfile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, scipy-notebook/Dockerfile
The following changes have been made.
- General
- `Changed`: Bump `hadolint` (Docker linter)
- `base-notebook`
- `Changed`: Bump Ubuntu
- `Changed`: Bump Miniforge and conda 
- `Changed`: Bump `notebook`
- `Changed`: Bump `jupyterhub`
- `Added`: `MINIFORGE_VERSION`env variable, I think it's interesting to have it for information at runtime (cf PR #1189)
- `Removed`: `bzip2` ubuntu package -> shipped with Miniforge [1]
- `Changed`: Gather together prerequisites install (move `tini` install with `conda` and `pip` install).
Keep jupyter installation separated from prerequisites installation.
Permit to save one step of `conda install`.
- `scipy-notebook`
- `Changed` Bump `h5py`
- `Changed` Bump `sympy`
- `datascience-notebook`
- `Changed`: Bump Julia
- `all-spark-notebook`
- `Changed`: Bump …
=> Regular update + improvements

all-spark-notebook/.dockerignore, base-notebook/.dockerignore, datascience-notebook/.dockerignore, minimal-notebook/.dockerignore, pyspark-notebook/.dockerignore, r-notebook/.dockerignore, scipy-notebook/.dockerignore, tensorflow-notebook/.dockerignore
Hello,
Just figured out that standards `hooks` and `test` directories that are part of most of the Docker image's folder were not included in the `.dockerignore`.
It's not a big improvement but they will not be anymore send to the daemon now.
Best
=> Fix .dockerignore by adding default hooks + test dirs

all-spark-notebook/test/data/issue_1168.ipynb, all-spark-notebook/test/test_spark_notebooks.py, pyspark-notebook/Dockerfile
Hello,
Fixes #1168.
It consists in applying the fix described in the [Spark downloading instructions](https://spark.apache.org/docs/latest/#downloading):
> For Java 11, `-Dio.netty.tryReflectionSetAccessible=true` is required additionally for Apache Arrow library. This prevents `java.lang.UnsupportedOperationException: sun.misc.Unsafe` or `java.nio.DirectByteBuffer.(long, int) not available` when Apache Arrow uses Netty internally.
The only problem of this solution is how it fits with other versions of Spark / Java that can be changed at build time through `ARGS`. However I have tested with Java 8 and tests are passing, Spark 2.x does not work with Python 3.8, see https://github.com/apache/spark/pull/26194, so I'm not sure it's worth going further on this compatibility point.
I've added a …
=> Fix spark installation for Java 11 and Arrow

base-notebook/Dockerfile
Hello,
This is a workaround to fix #1215. I've also bumped some dependencies in `base-notebook`.
This will have to be removed once fixed on upstream.
_Note: I've noticed in the previous build that iPython was downgraded to `7.18.1`, maybe a consequence of pinning jedi to `<1.18`._
=> Fix autocompletion issue #1215

README.md, base-notebook/start-notebook.sh, base-notebook/test/test_start_script.py
Hello,
This is a very first step of the feature #1217 that consists in printing a deprecation notice in the `start-notebook.sh`.
Here is the new behavior
- **With no option (no specific environment variable)**: Jupyter Notebook is launched (no change). However a warning message is printed pointing to https://github.com/jupyter/notebook#notice.
- **With `JUPYTER_ENABLE_LAB`**: Jupyter Lab is launched (no change).
I've written a test that checks this behavior.
Best
=> Jupyter Notebook Deprecation Notice

README.md, binder/Dockerfile
Fix #1219
The link to check that everything works:
https://mybinder.org/v2/gh/mathbunnyru/docker-stacks/master?filepath=README.ipynb
(The only change in the link is using `mathbunnyru` instead of `jupyter`, I committed directly to master)
=> Update image used in binder

binder/Dockerfile
Main change is to make `README.ipynb` writeable.
Other changes are made to make this Dockerfile look similar to all the other notebook Dockerfiles we have.
Link to check the change:
https://mybinder.org/v2/gh/mathbunnyru/docker-stacks/asalikhov/improve_binder?filepath=README.ipynb
(Note: `mathbunnyru` (my fork) and branch name `asalikhov/improve_binder`)
=> Improve binder image

base-notebook/Dockerfile, datascience-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile, scipy-notebook/test/test_extensions.py, tensorflow-notebook/Dockerfile
Upgrade to JupyterLab `3.0.x` as described in #1207 and other upgrades.
- `base-notebook`
- `Changed`: Bump ubuntu
- `Changed`: Bump `jupyterlab` -> Fixes #1207 and fixes #1167
- `scipy-notebook`
- `Changed`: Bump `dask`
- `Changed`: Bump `ipympl`
- `Changed`: Bump `pandas`
- `Changed`: Bump `scipy`
- `Removed`: Jupyter Extension management through `npm` and `jupyter labextension`.
It is not necessary anymore, and I have checked that both `ipywidgets` and `matplotlib` are working with JupyterLab and Jupyter. It speeds up the build time.
- `Removed`: Skip extension test, see limitations below for detail
- `datascience-notebook`
- `Changed`: Bump `rpy2`
- `tensorflow-notebook`
- `Changed`: Bump `tensorflow`
Even with the limitations (Bokeh extension is the only regression) listed below, I …
=> JupyterLab 3.0 and other updates

base-notebook/Dockerfile
The ipython package dependencies has been fixed in conda-forge see https://github.com/ipython/ipython/issues/12740#issuecomment-768898772. So it's no longer necessary to pin jedi here, as it is managed by the upstream dependency and it leads to the same result install jedi `0.17.2` instead of `0.18.0`.
Best
=> Fixes #1215: remove the workaround

docs/using/recipes.md
Following https://github.com/jupyter/docker-stacks/pull/1222 the `jupyter/scipy-notebook:latest` image now uses JupyterLab 3. This allows us to [streamline the installation process](https://github.com/dask/dask-labextension#jupyterlab-30-or-greater) in the Dask JupyterLab extension recipe.
=> Update dask-labextension recipe for JupyterLab 3

Makefile
Fix https://github.com/jupyter/docker-stacks/issues/1237
There was a change in 20.10.0 docker:
https://docs.docker.com/engine/release-notes/#20100
`Add -a/--all-tags to docker push docker/cli#2220`
So, only the latest version is now pushed by default.
Since we don't fix the docker version and always use the latest one, it affected our setup.
=> Push all tags in docker push command

datascience-notebook/Dockerfile, r-notebook/Dockerfile
Title says it all readlly. I  was updating the images I built for Kubeflow and saw that  r-rmarkdown 2.7 was released 5 days ago. Thought the jupyter docker-stacks could also use the update.
=> update r-rmarkdown to 2.7*

base-notebook/Dockerfile, base-notebook/test/test_package_managers.py, docs/using/common.md, docs/using/selecting.md
Hello,
This PR replaces #1213 and resolves #1210: installation of [Mamba][1] in `base-notebook`.
This time Mamba is only installed and not used to install packages of the stack, so it will be available to end users as a _faster_ alternative to Conda if they want to install their own packages. It seems to be a feature required by several users.
- Installation: I have used a flavor of the [Miniforge][2] installer shipping `mamba` by default.
- Docs: Updated, maybe I missed some.
- Test: Added generic test `test_package_managers.py` for all package managers including `mamba`.
- Size: +23MB penalty on all images
```bash
REPOSITORY              TAG               IMAGE ID       CREATED          SIZE
jupyter/base-notebook   latest            bdb5390b61b5   24 minutes ago   704MB …
```
=> Install mamba in base-notebook

Makefile, base-notebook/Dockerfile, pyspark-notebook/Dockerfile, scipy-notebook/Dockerfile
Hello,
A standard update of the stack with very little change.
Best
=> Regular update 2021-02-28

pyspark-notebook/Dockerfile
Hello, 
Following the example properties in the spark default configuration, I believe the syntax is incorrect and might lead to these properties being ignored. 
The syntax problem only occured to me when trying to add additional properties following the syntax with inverted comas. I am not sure if my suggested changes actually fix anything, as I don't know the reason for these properties. If so, it still may worth merging to prevent others from having problems adding properties. 
Hope it helps!
=> Fix spark config properties syntax in Pyspark notebook Docker image

README.md
Hello,
As discussed in #1217, remove the April target by a _not defined_ (At some point) target in the `README.md`.
Best
=> Remove April from the deprecation notice

Makefile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile
A regular update.
Main changes
- Hadolint
- Ubuntu
- Conda
- Notebook
- Julia
- ipympl
Best
=> Regular update 2021-04-08

docs/using/specifics.md, pyspark-notebook/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/1163
@romainx as you suggested, in your issue, we could use a spark archive to be able to build the old spark versions.
You said, that we will put pressure on a specific download site.
I think that's true, at the same time it's `https://spark.apache.org`.
The pressure we create is only a few builds per day (at max).
And I think there are not so many people, who rebuild our images from scratch (I think it's not needed in most cases).
I agree that this way is less clever than using the preferred site.
At the same time, it's much easier to use only one `wget` command.
If I'm right, we haven't tried `https://archive.apache.org` as a mirror so it might be reliable to use (I hope it is).
I think - let's give `archive` a try, if everything …
=> Install spark from archive.apache.org to be able to use old versions

base-notebook/Dockerfile
> JupyterHub 1.4 is a small release, with several enhancements, bug fixes, and new configuration options. ([see changelog](https://jupyterhub.readthedocs.io/en/stable/changelog.html))
I was not able to locally test due to [known issues](https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues) with Docker on Apple silicon.
=> Update JupyterHub to 1.4.0

.github/workflows/docker.yml, .pre-commit-config.yaml, Makefile, binder/Dockerfile, docs/contributing/lint.md
Thanks to https://github.com/hadolint/hadolint/pull/523 we can use hadolint directly in `pre-commit`.
Downsides:
- being able to run hadolint on a specific image with `make` command. But it is actually still possible to run it via `pre-commit --run` flags.
- need to be running docker to run hadolint. But this project uses docker for basically everything, so this should not be a problem.
Upsides:
- 21 deletions in Makefile
- approximately 50 deletions in docs
- The setup is easier because there are no specific things for hadolint
- No hadolint binary in HOME (I didn't like this on my mac)
- Pre-commit hooks versions could be updated automatically (I will try to do it later)
=> Use hadolint from pre-commit

base-notebook/Dockerfile, base-notebook/test/test_python.py
This is a follow up on https://github.com/jupyter/docker-stacks/pull/1286
=> Update miniforge to 4.10.1 and python version to 3.9.2

base-notebook/Dockerfile
> JupyterHub 1.4 is a small release, with several enhancements, bug fixes, and new configuration options.
> 1.4.1 is a small bugfix release for 1.4.
[see JupyterHub changelog](https://jupyterhub.readthedocs.io/en/stable/changelog.html)
[see JupyterLab changlog](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0-15)
I was not able to locally test due to [known issues](https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues) with Docker on Apple silicon.
=> Update JupyterHub to 1.4.1 and JupyterLab to 3.0.15

base-notebook/Dockerfile, base-notebook/test/test_start_container.py, docs/using/selecting.md
Hello,
According to @lima4658 suggestion in #1306, `tini` is now installed from the ubuntu package.
The installation is cleaner because we can remove the corresponding pin of the conda package.
Also added a test to check that `tini` is used as the `PID` 1 when launching the `base-notebook` container.
Best
=> Install tini from the ubuntu package

Makefile, docs/using/selecting.md
This PR fixes a markdown formatting error and ensures that future errors caught by pre-commit will emit relevant information by showing a `git diff`.
=> ci: provide a git diff on pre-commit failures

README.md, binder/Dockerfile, docs/index.rst, docs/using/recipes.md, docs/using/running.md, docs/using/selecting.md, examples/docker-compose/README.md, examples/docker-compose/notebook/Dockerfile, examples/make-deploy/Dockerfile
I tried to find all the places where we have fixed tags.
And updated to tag `33add21fab64`, which was built an hour ago.
So, users will run the latest (and greatest) image when following our documentation.
It should also make maintenance easier - next time one grep + replace should be enough (right now there are about 10 different tags across all the docs).
=> Update tags in documentation

docs/conf.py, requirements-dev.txt
This adds small copy button to all the code blocks.
I think it's quite nice and helpful (especially when copying one-liners)
=> Add copy button to the docs

.github/workflows/docker.yml, .github/workflows/pre-commit.yml
Several reasons for this change:
- PRs like this shouldn't trigger docker build. https://github.com/jupyter/docker-stacks/pull/1339
- A bit faster CI (1 minute)
- Unfortunately, we can't fully rely on pre-commit.ci, because we use Docker-based linter and docker is not available in pre-commit.ci
=> Run pre-commit in separate workflow

.github/workflows/docker.yml, .github/workflows/pre-commit.yml
This is already used in sphinx, works fine.
And it will be easier to start using new features for the new code.
(Changing the python version here doesn't change the content of the docker image).
=> Use python-version: 3.x in github actions

.github/workflows/docker.yml
This change is to address the situation in https://github.com/jupyter/docker-stacks/pull/1341 (also happened with me once).
Now we can't merge to the master if there is something in the master which is not yet built.
This will cause errors.
The reason for that is that in the docker builds we clone the wiki in the beginning, and at the end of the build update the wiki.
And in between, we build the images (it's a long step that takes more than 30 minutes now).
And then there will be two commits in the docs which change the docs in a different way.
So, the second build will not update wiki (manifests).
And so the CI will fail.
This commit uses wiki only for a minute:
- clone wiki (seconds)
- hook everything (1min15s)
- push wiki if it's master (seconds)
This way we lock the wiki only for a …
=> Clone wiki only for steps which need it

.github/workflows/docker.yml
This is more idiomatic on GitHub, doesn't create a warning, supports plenty of registries (https://github.com/marketplace/actions/docker-login) and does automatic logout in the end of the job.
=> Use docker/login-action instead of manual docker login

README.md
Just a small rearrange of sections - I want the users to see the quick start first and only then info about maintainers and jupyter notebook.
=> Put quick start first in README.md

minimal-notebook/Dockerfile
As discussed in https://github.com/jupyter/docker-stacks/issues/1372, this PR adds `openssh-client` to the list of packages installed in the `minimal-notebook`. - It's needed for the git-over-ssh support.
Closes #1372
=> Add openssh-client (needed for git-over-ssh)

minimal-notebook/Dockerfile
The `build-essentials` package was not a dependency to install other packages in the images of this repo, and it increased the minimal-notebook image size from 1.37GB to 1.55GB for example.
With the motivation that it is probably only relevant for users that depend on this image as a base image from other Dockerfiles where it is easy to install an additional `apt` package, this PR propose it is deleted. If this caused a breaking change for you, and you were using the image directly without using this image as a base image (via a `FROM` statement in a Dockerfile), please open an issue and describe that use case!
=> Remove build-essential install

.github/workflows/docker.yml, .github/workflows/sphinx.yml, Makefile
Github Actions are awesome.
Having many lines in Makefile is not.
After this change Makefile is always simply running a command or two, without any logic.
Also, the amount of code is reduced and there are not workarounds for wiki repo and env variables.
Funny thing that we can remove the check for `[ci skip]` in workflows because automatically created commits by default do not triggers workflows.
But, I think it's nice to be able to push something to master and not trigger builds, so I didn't remove `ci skip` condition.
=> Use stefanzweifel/git-auto-commit-action to push to github

Makefile, all-spark-notebook/Dockerfile, binder/Dockerfile, datascience-notebook/Dockerfile, minimal-notebook/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
This is a follow-up on https://github.com/jupyter/docker-stacks/pull/1368
This should make it easy for someone to have local builds pushed to their docker hub and pulled from it.
=> Introduce owner to Dockerfiles to make it easy to test locally

.github/workflows/docker.yml
This is a followup to complement#1399 and #1408 about things that wasn't tested as it was part of the steps to push to the official registry.
`docker buildx build --push` resulted in 401 Unauthorized while `docker push` didn't. I think the reason is that there is a bug in buildx 0.5.1 that is patched in 0.6.0 that was released an hour ago.
To make it available, I explicitly declare that I want to use the latest version of buildx to make it download and install it.
=> Explicitly ask for the latest buildx version

Makefile, pytest.ini
Closes #1426 by ensuring that our ci system, after having built an image, makes it accessible to `docker` so that our later steps in our ci system don't go ahead and download an entirely different image and tags/tests using that image instead of the one we built.
=> Fix failure to tag correctly

datascience-notebook/Dockerfile, r-notebook/Dockerfile
Hi,
This PR fix #1450.
The packages following the comment after "r-e1071" are not installed be
To keep the comment I moved it to the line just above.
Regards,
=> Fix: Move comment to uncomment packages installation after r-e1071

datascience-notebook/Dockerfile, r-notebook/Dockerfile, requirements-dev.txt
As mentioned here: Latest release 5.0.1 container exec_run fails
https://github.com/docker/docker-py/issues/2885
We will have to pin the version until the upstream fixes the issue and then updates the package.
=> Pin docker version and move comment out of install

base-notebook/start.sh
`cp -R` does not copy hidden files/directories, causing issues (cfr #1465) .
Using `-a` instead of `-R` makes `cp` work more closely as `rsync -avx` (which the `cp -R` replaced in 0dbce4526e165ce716e4ca41a7384e8dce0bfd0b) . This solves the problem that `CHOWN_HOME` was required to change file permissions from root  to the local user. Setting the `CHOWN_HOME` environment variable to 'yes' in our JupyterHub deployment caused issues like:
> chown: cannot access '/home/custom-username': No such file or directory
when older images were started
Added by @mathbunnyru 
Fix: https://github.com/jupyter/docker-stacks/issues/1465
=> Also copy hidden files/directories

base-notebook/test/test_container_options.py
Test if the hidden `.jupyter` folder is properly copied when the user is changed via `NB_USER` environment variable. This folder should exist as `jupyter notebook --generate-config` is executed to generate `/home/jovyan/.jupyter/jupyter_notebook_config.py` .
Test for fix #1466 for issue #1465.
=> Add test for copying of hidden folder

base-notebook/start.sh, base-notebook/test/test_container_options.py
Towards fixing #1270 I am convinced by @consideRatio's approach in #1052.
His #1052 grew quite large, and generated a lot of interesting discussion. It also introduced some very valuable enhancements to `start.sh` to improve comments, messages, and make it more robust.
I have rebased a subset of his commits which I consider less controvertial. In theory, they should not significantly change anything except for the messages, but several edge cases should now be handled better.
I hope that this can be tested and approved. Then I hope to
- bring in the remaining commits from #1052
- implement #1270 based on an approach which reverts 4ef8a78, likely with a few additional subtle modifications.
- Try to close #1478
=> Rework of start.sh script, take 2

base-notebook/start.sh
=> Revert broken sed --in-place command

base-notebook/start-notebook.sh, base-notebook/test/test_start_container.py
Cherry-pick of d63c09c, working through https://github.com/jupyter/docker-stacks/pull/1512#issuecomment-962672049
Looks like this is meant to address #1034
=> start-notebook.sh: pass NOTEBOOK_ARGS as docs say

base-notebook/start.sh, base-notebook/test/test_container_options.py, docs/using/common.md
Cherry-pick of b44b7ab. I'm working through https://github.com/jupyter/docker-stacks/pull/1512#issuecomment-962672049
> Allow you to define variables to be unset before running the command
> that start.sh is supposed to start. These variables will still be
> available in the hooks run before.
=> start.sh: JUPYTER_ENV_VARS_TO_UNSET introduced

base-notebook/start.sh
Cherry-pick of 63295ba, working through  https://github.com/jupyter/docker-stacks/pull/1512#issuecomment-962672049
> It is meant to allow you to opt out from non-error non-warning logs
> generated by start.sh.
=> Refactor logging in start.sh and add JUPYTER_DOCKER_STACKS_QUIET

.github/workflows/docker-amd64.yml, .github/workflows/docker-x86.yml
The idea behind this is simple - let's build x86 images in a different workflow.
It's enough for most PRs and we can skip long x86+arm builds and merge quicker.
=> Build and test amd64 docker images in a dedicated workflow for quick feedback

datascience-notebook/Dockerfile
A [new stable version](https://julialang.org/blog/2021/11/julia-1.7-highlights/) just came out.
=> Update Julia to 1.7.0

base-notebook/start.sh, base-notebook/test/test_container_options.py, base-notebook/test/test_package_managers.py, base-notebook/test/test_pandoc.py, base-notebook/test/test_python.py, base-notebook/test/test_start_container.py
Closes #1520
During tests, I now check for unexpected ERROR/WARNING messages.
I added a few tests to check for expected warning messages regarding
- unable to write to `/etc/passwd` because `uid != 0`
- unable to write to `/home/jovyan` because user not in `users(100)` group
I also improved the warning messages to suggest solutions in both cases.
To suppress the spurious warnings from #1520, I warn only when the defaults change, which is in-line with [the old logic](https://github.com/jupyter/docker-stacks/blob/93a6865aa3540cd4df94aba312bbab5b9a9d147c/base-notebook/start.sh#L108).
I removed the "test for nonempty" tests `-n "${NB_USER}"`, `-n "${NB_UID}"`, `-n "${NB_GID}"`, because these variables all have nonempty default values, so they should never be empty in the first place.
Finally, …
=> Fix spurious warnings when using docker run --user=X

base-notebook/Dockerfile
There are various tools that scans for known vulnerabilities in images. The base image we use, `ubutnu:focal` has at the moment was latest updated more than 2 months ago, meaning all known vulnerabilities that actually has been patched, hasn't been patched in new builds of our image as the `ubuntu:focal` image hasn't been updated.
Due to that, I suggest we run `apt-get upgrade` when we build the base image.
=> Run apt-get upgrade to patch known vulnerabilities faster

docs/contributing/features.md, docs/contributing/stacks.md
Hello,
Fixes #1552 .
Anchors are not supported with Markdown.
I've used a workaround to fix the broken links by transforming Markdown to HTML anchors as described [here](https://stackoverflow.com/a/64044458/4413446).
Best
=> Fix broken markdown anchors in the doc

docs/using/specifics.md, pyspark-notebook/Dockerfile, pyspark-notebook/ipython_kernel_config.py
Hello,
This fixes #1423 by [configuring IPython system-wide](https://ipython.readthedocs.io/en/stable/config/intro.html#systemwide-configuration) to turn off  low-level output capture and forward through the [`IPKernelApp.capture_fd_output`](https://ipython.readthedocs.io/en/stable/config/options/kernel.html#configtrait-IPKernelApp.capture_fd_output) flag.
Best
=> Turn off ipython low-level output capture and forward

requirements-dev.txt
I think this was coming from times when myst-parser installed old sphinx version.
=> Do not fix sphinx version

docs/using/recipes.md
Calling the "latest" tag ( "FROM jupyter/pyspark-notebook:latest" ) installs Spark 3.2 version, which is incompatible with delta lake ( https://docs.delta.io/latest/releases.html#-compatibility-with-as ). Installing the last version of Spark 3.1.x resolves the issue. In the jupyter docker repo that would be version 3.1.18
=> Spark version incompatibility with Delta

.gitattributes, all-spark-notebook/test/test_spark_notebooks.py, base-notebook/test/test_container_options.py, base-notebook/test/test_package_managers.py, base-notebook/test/test_pandoc.py, base-notebook/test/test_python.py, base-notebook/test/test_start_container.py, conftest.py, datascience-notebook/test/test_julia.py, minimal-notebook/test/test_inkscape.py, minimal-notebook/test/test_nbconvert.py, pyspark-notebook/test/test_spark.py, scipy-notebook/test/test_extensions.py, scipy-notebook/test/test_matplotlib.py, tagging/create_manifests.py, tagging/docker_runner.py, tagging/manifests.py, tagging/tag_image.py, tagging/taggers.py, test/helpers.py, test/test_notebook.py, test/test_outdated.py, test/test_packages.py, test/test_units.py
Main change is to add some typing, but there are some other changes as well.
Sorry they are all packed in one PR, but there are no significant changes here.
=> Add some typing to tests

.github/workflows/docker-amd64.yml, all-spark-notebook/test/test_spark_notebooks.py, base-notebook/test/test_container_options.py, base-notebook/test/test_package_managers.py, base-notebook/test/test_pandoc.py, base-notebook/test/test_python.py, base-notebook/test/test_start_container.py, conftest.py, datascience-notebook/test/test_julia.py, minimal-notebook/test/test_inkscape.py, minimal-notebook/test/test_nbconvert.py, pyspark-notebook/test/test_spark.py, scipy-notebook/test/test_extensions.py, scipy-notebook/test/test_matplotlib.py, tagging/docker_runner.py, test/package_helper.py, test/test_notebook.py, test/test_units.py
Benefits of `container.run_and_wait`:
- it's typed and it's type is `str`. I don't like Docker approach, where one function can return different things depending on parameters (but in their case it makes sense).
- warnings and errors are checked, unless explicitly asked not to check them
- return code is always checked
- it's easy to debug broken tests - because not all the tests used `LOGGER.debug`, now they will
- less code :)
=> Unify docker usage in tests

base-notebook/start.sh, base-notebook/test/test_container_options.py
Replaces #1054 (because I deleted my fork)
Fixes #1053
=> Prepend $CONDA_DIR/bin instead of appending

r-notebook/Dockerfile
Summary by Erik: In the past we have omitted installing three R packages in our arm64 image specifically. Now though, it seems like arm64 support has improved and we only need to omit one R package.
=> Install more r packages for arm

minimal-notebook/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/1588
=> Only install system packages which are useful for many people

Makefile
I think, this is the default behaviour on RTD, I would like it to be the default behaviour when I run `make docs`.
Makes local build process more similar to what happens in the CI.
=> Fail make docs on docs warnings

.markdownlint.yaml, docs/contributing/stacks.md, docs/using/selecting.md
It's the same amount of information, but without duplications like `is a community Jupyter Docker Stack image` or `Try it on`.
I think this is visually much more clear and easy to choose from.
Also refactored GPU flavours, because their descriptions are quite long and it makes sense to have them in a separate table.
=> Present community stacks as a table

docs/conf.py, docs/contributing/features.md, docs/contributing/issues.md, docs/contributing/stacks.md, docs/maintaining/tasks.md, docs/using/common.md, docs/using/recipes.md, docs/using/running.md, docs/using/selecting.md, docs/using/troubleshooting.md
I used sphinx link check (`sphinx-build -b linkcheck docs/ docs/_build/` or `make linkcheck-docs` in our Makefile) to get rid of broken links and redirects.
=> Fix wrong links

base-notebook/Dockerfile, base-notebook/jupyter_server_config.py, docs/using/common.md, examples/openshift/README.md, examples/openshift/templates.json, examples/source-to-image/templates.json
Hello,
This is a follow-on to the PR #1575 in the frame of the issue #1217 aiming to switch to Jupyter Lab by default.
Since [Jupyter Server](https://jupyter-server.readthedocs.io/en/latest/index.html) is now the default backend, I think it's better to maintain it's configuration file `jupyter_server_config.py` instead of the Jupyter Notebook one `jupyter_notebook_config.py`.
- I've simply inverted  in the Dockerfile the transformation between the two files. 
- I've tried to update all the references in the doc, however I may have forgotten some.
- I've basically updated (search & replace)  the files in the directory [`examples/openshift`](https://github.com/jupyter/docker-stacks/tree/master/examples/openshift), however I'm not sure they are sill working 😕.
Best :cake:
=> Switch the default to Jupyter Server configuration file

base-notebook/test/test_container_options.py, base-notebook/test/test_start_container.py, conftest.py, test/test_notebook.py
Related: https://github.com/jupyter/docker-stacks/issues/1622
=> Choose random host port in tests

Makefile, base-notebook/test/test_container_options.py, base-notebook/test/test_start_container.py, conftest.py, requirements-dev.txt, test/test_notebook.py
Fix: https://github.com/jupyter/docker-stacks/issues/1622
`time TEST_IMAGE="jupyter/base-notebook" pytest test/ base-notebook/test/ --log-level debug`:
Executed in  145.72 secs
Same with `-n auto`:
Executed in   44.42 secs
=> Run tests in parallel

Makefile, requirements-dev.txt
I ended up needing to google around a bit to learn about the `-n` flag that turned out to come from pytest-xdist, so I figured it was helpful to document it and provide the flag in its long form. This is a followup to https://github.com/jupyter/docker-stacks/pull/1624.
=> Add inline comments about pytest-xdist

scipy-notebook/Dockerfile, tests/pytest.ini, tests/scipy-notebook/data/cython/helloworld.pyx, tests/scipy-notebook/data/cython/setup.py, tests/scipy-notebook/test_cython.py
Fix: https://github.com/jupyter/docker-stacks/issues/1625
Follows: https://github.com/jupyter/docker-stacks/pull/1383
I added the test, that cython works properly (it didn't before this fix).
Image size increase: 2.68GB -> 2.82GB (checked under arm)
As we provide cython, we should make sure it works fine, that's why we have to install `build-essential` in `scipy-notebook`.
This also fixes the recent issue with absent `make` command.
=> Fix cython in scipy-notebook

.pre-commit-config.yaml, Makefile, mypy.ini, tests/base-notebook/test_packages.py, tests/conftest.py, tests/images_hierarchy.py
What I've done:
- Updated mypy config to use `--strict --follow-imports error`. This makes this tool much more efficient in finding errors.
- Fixed all the errors
- Made `pre-commit` mypy hook use the same config
- Made sure the `pre-commit` hook works well and disabled `mypy` for `git commit` stage
- Added some inline comments to explain why and how I did it.
=> Update mypy config and make it work well with pre-commit

docs/using/selecting.md
Updating documentation for selecting docker image to include new community stack **scraper-notebook**
Based on the `minimal-notebook`, this new new image comes with pre-installed python libs for web scraping (`requests`,`beautifulsoup4`, `selenium`) and google chrome + chrome driver to use as the web driver.
=> Adding community docker stack : scraper-notebook

.gitignore, README.md, docs/conf.py, docs/contributing/issues.md, docs/contributing/lint.md, docs/contributing/packages.md, docs/contributing/stacks.md, docs/index.rst, docs/maintaining/tasks.md, docs/using/common.md, docs/using/recipes.md, docs/using/selecting.md, docs/using/specifics.md, docs/using/troubleshooting.md, tagging/taggers.py, tests/base-notebook/test_packages.py, tests/base-notebook/test_units.py, tests/package_helper.py, tests/scipy-notebook/data/matplotlib/matplotlib_1.py, tests/scipy-notebook/data/matplotlib/matplotlib_fonts_1.py
Sometimes I like to use PyCharm to write python/markdown code.
So I decided to fix some issues to not to see them anymore.
This PR doesn't fix all the issues, though, but I think the remaining ones are not actually issues and they have to do with some our internal names like `jovyan`.
=> Fix English typos and misc details detected by PyCharm

.pre-commit-config.yaml, docs/using/recipes.md, docs/using/specifics.md, tagging/README.md
It would be nice if people could copy our code from the documentation and paste it into their projects and it would work without any changes.
This also makes the code in the docs follow the same principles as we have in our main projects.
It also makes the review process easier - because the docs are easier to read.
=> Run black pre-commit on python code in docs

base-notebook/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/915
Some people would like to have HEALTCHECK working for their docker containers.
This is especially important to people using Docker Swarm, where the container might be "still working", but not actually responding, and so on.
Let's try to add this to the base image, actually.
If someone uses custom configuration, they can for sure do one of many things if a health check doesn't work for them:
- `HEALTHCHECK NONE`
- `HEALTHCHECK CMD custom-command
- `docker run --no-healthcheck`
- disable it in docker-compose
So, I think, we should be fine even for people who explicitly don't want this healthcheck.
=> Add healthcheck command to Dockerfile

.github/workflows/docker.yml
Our CI fails now on any change:
https://github.com/jupyter/docker-stacks/pull/1672
What happens:
Because of our complicated build system, when we build minimal image, instead of building it on top of just created base image, we end up pulling an old image.
And this happens for other images as well.
And, we also rebuild during `push`, which is also not great.
This is **a major problem**.
What I want to do - merge this, rebuild images in master 5 times.
This way all our images eventually will be updated as they were build from source code.
After that, testing cab be enabled back.
=> [TMP] Disable tests

base-notebook/start-notebook.sh, tests/base-notebook/test_start_container.py
This warning was there for more than 2 months.
Let's remove it, because I think everyone who wanted to change something, already did it.
=> Remove JUPYTER_ENABLE_LAB variable warning

tagging/manifests.py
This will reduce output we don't need, for example here: https://github.com/jupyter/docker-stacks/wiki/all-spark-notebook-068e3c5ddab0#python-packages
=> Add --quiet to mamba info

.github/workflows/docker-amd64.yml, .github/workflows/pre-commit.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>
=> Set permissions for GitHub actions

base-notebook/Dockerfile
It seems that the HEALTHCHECK command accesses the wrong endpoint when running the image in JupyterHub.
Since JupyterHub adds a prefix (obtained by `JUPYTERHUB_SERVICE_PREFIX`) to the endpoint, I assume that adding this to the HEALTHCHECK command will allow HEALTHCHECK to work correctly with JupyterHub.
This PR may also fix the following: https://github.com/jupyter/docker-stacks/issues/915#issuecomment-1104230461
=> Fix HEALTHCHECK command for JupyterHub

docs/using/running.md
* Add exmaple 4 that demonstrates how to run the container
image docker.io/jupyter/r-notebook:6b49f3337709 with rootless podman.
Signed-off-by: Erik Sjölund <erik.sjolund@gmail.com>
=> Add section "Using the Podman CLI"

base-notebook/Dockerfile, tests/base-notebook/test_python.py
Bump Python 3.9 → 3.10
Closes #1688
=> Bump Python 3.9 → 3.10

docs/using/common.md
The use of `IPython.lib.passwd()` does not match with [Jupyter server documentation](https://jupyter-server.readthedocs.io/en/latest/operators/public-server.html#preparing-a-hashed-password) and may lead to confusion on how to import/use it.
=> Update passwd function

README.md, binder/Dockerfile, docs/using/recipes.md, docs/using/running.md, examples/docker-compose/README.md, examples/docker-compose/notebook/Dockerfile, examples/make-deploy/Dockerfile
=> Update tag example

.github/workflows/sphinx.yml, .readthedocs.yaml, docs/conf.py, docs/requirements.txt
=> Up docs dependencies and move requirements to docs folder

tests/base-notebook/test_container_options.py, tests/base-notebook/test_start_container.py
=> Reduce sleep timeouts in tests

docs/using/specifics.md, pyspark-notebook/Dockerfile
add Scala version choice
[BUG] pyspark-notebook no longer builds for Spark 3.1.3, 3.1.2, 2.4.8 - Fix: https://github.com/jupyter/docker-stacks/issues/1756
=> Add Scala as `--build-arg`

base-notebook/fix-permissions
Using the `-exec command {} +` (instead of `;`)  action of `find`, we can improve the performance of fix-permissions script significantly. The difference between the two is that the former (`+`) invokes a single process and passes all the files to it as arguments, whereas the latter (`;`) invokes one process per matched file resulting in thousands of `chmod` runs per build.
My benchmarks show about a 30 second improvement in steps that involve fix-permissions for the `build-all` target of `make`. More importantly for me, user defined Docker images, which use the fix-permissions script, will also show perf improvements.
n/a
=> Improve performance of fix-permissions script

base-notebook/Dockerfile, tests/base-notebook/test_python.py
I think that our build system works well and doesn't have any known bugs and it finally supports both `x86_64` and `aarch64` and multi-arch images for these platforms properly.
I also think, some users still want to use old images (not all people can switch to the new ubuntu or python version quickly).
So, I had an idea to rebuild the images in this order:
- First, ubuntu-20.04 with python 3.7, 3.8, 3.9, 3.10
- Then, ubuntu-22.04 with python 3.7, 3.8, 3.9, 3.10 as well
After this, people will be able to choose the old version(s) if they want to.
And tags will work correctly for these images as well.
*This doesn't mean, that we will support these versions in the future.*
After all these rebuilds, the latest versions will be the same as they currently are.
But in the process, they will …
=> Build images with ubuntu-20.04 and python-3.7

docs/using/recipes.md
https://github.com/jupyter/docker-stacks/issues/1796
=> Document how to enable pandas.read_clipboard()

docs/using/recipes.md
Add a recipe to the recipes section of the docs. This recipe is a simple `Dockerfile` that installs a working kernel for ijavascript. This allows node to be used in jupyter.
=> add recipe for installing ijavascript kernel

.github/workflows/docker-merge-tags.yml, .github/workflows/docker-tag-manifest-push.yml, .github/workflows/docker-wiki-update.yml, .github/workflows/sphinx.yml
=> Make workflows work fine in forked repos

docs/using/recipes.md
Recipe with Dockerfile adding a layer with Microsoft SQL Server ODBC driver and ``pyodbc``.
=> Recipe for Microsoft SQL Server

base-notebook/Dockerfile, base-notebook/jupyter_server_config.py, docs/using/common.md, tests/base-notebook/test_container_options.py, tests/base-notebook/test_healthcheck.py
Opening PR intended to close #1817 
Fix #1817
=> Parameterize healthcheck by internal port

docs/using/troubleshooting.md
Jupyter can have multiple local instances if the used ports don't overlap. Added this as a troubleshooting alternative for users who may want or need to have more than one Jupyter instance running.
=> Add third option: Route container to another local port

pyspark-notebook/Dockerfile
Upgrade Apache Spark from 3.3.1 to 3.3.2
[Release notes](https://spark.apache.org/releases/spark-release-3-3-2.html)
Fix: #1838
=> Upgrade `Apache Spark` to 3.3.2

.pre-commit-config.yaml, base-notebook/Dockerfile, base-notebook/docker_healthcheck.py, tests/base-notebook/test_healthcheck.py
This PR tries to implement the idea discussed on #1817. Obtain the URL where the jupyter server runs on from a json file located on `/home/$NB_USER/.local/share/jupyter/runtime` directory and use it for healthcheck. Parsing of the json file is done with minimal python currently written as a one-liner command. 
Would appreciate any feedback!
Intended as a solution for https://github.com/jupyter/docker-stacks/issues/1709
=> Healthcheck url from json

all-spark-notebook/Dockerfile, base-notebook/Dockerfile, datascience-notebook/Dockerfile, docs/using/common.md, docs/using/recipes.md, examples/docker-compose/notebook/Dockerfile, examples/make-deploy/Dockerfile, pyspark-notebook/Dockerfile, r-notebook/Dockerfile, scipy-notebook/Dockerfile, tensorflow-notebook/Dockerfile
Removing `--quiet` flag from most commands.
It was added only because of Travis CI logs size, which we no longer use.
This flag makes it more difficult to analyze the logs when something (usually dependency solver) goes wrong.
=> Remove --quiet flag when not needed

pyspark-notebook/Dockerfile
Upgrade Apache Spark from 3.3.2 to 3.4.0
[Release notes](https://spark.apache.org/releases/spark-release-3-4-0.html)
=> Upgrade `Apache Spark` to 3.4.0

base-notebook/Dockerfile, tests/base-notebook/test_packages.py
NodeJS >= 18.0 is installed in base-notebook image because `jupyter lab build` command requires it.
Fix: #1901
=> Install nodejs >= 18.0

datascience-notebook/Dockerfile
Bump version of Julia to 1.9, with significant performance upgrades.
=> Bump Julia version to 1.9

Makefile
The `hook/%` target refers to the script `tagging.tag_image` which does not exist anymore. This PR updates Makefile to use `tagging.write_tags_file` and `tagging.apply_tags` instead (identical to what is being done in Github Actions).
=> Fix image tagging in hook/%

docs/using/selecting.md, minimal-notebook/Dockerfile, minimal-notebook/setup-scripts/setup-julia.bash, pyspark-notebook/Dockerfile
=> Use curl instead of wget for Spark and Julia downloads

docs/using/common.md, docs/using/troubleshooting.md
`-w "/home/${NB_USER}"` never does what you think it will do.
`${NB_USER}` is interpreted by bash on the host machine, not inside the docker.
And this variable is (almost) never set on the host machine, so this line works as `-w "/home/"`, which is not what most people want.
=> Fix usage for -w in docs

base-notebook/docker_healthcheck.py, tests/base-notebook/test_healthcheck.py
For environments that use proxies, mostly corporate environments, the health check did not work. Proxies are not necessary for the health check so the proxies are disabled.
The health check runs in the docker container and makes a request to a specific address. If that request is routed through a proxy it leaves the docker container. This can cause two types of problems:
- The proxy does not know the ip address and thus the request never terminates
- Outside of the container the ports can change and the request will not reach the proper port.
Closed [1962](https://github.com/jupyter/docker-stacks/issues/1962)
- [-] I have updated the documentation for significant changes
=> Healthcheck gives correct result even behind proxy

README.md, docs/using/faq.md, docs/using/recipes.md, docs/using/running.md
Fix: https://github.com/jupyter/docker-stacks/issues/1959
=> Add info how to persist user data

docs/using/recipe_code/custom_environment.dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/1903
=> Update the custom env recipe to correctly activate it by default

docs/using/common.md, docs/using/selecting.md, images/docker-stacks-foundation/Dockerfile, images/docker-stacks-foundation/run-hooks.sh, images/docker-stacks-foundation/start.sh, tests/conftest.py, tests/docker-stacks-foundation/run-hooks-data/executable.py, tests/docker-stacks-foundation/run-hooks-data/non_executable.py, tests/docker-stacks-foundation/run-hooks-data/run-me.sh, tests/docker-stacks-foundation/test_run_hooks.py
Work on: https://github.com/jupyter/docker-stacks/issues/1478
=> Implement run-hooks as a separate script

images/docker-stacks-foundation/start.sh
=> Preserve LD_LIBRARY_PATH in start.sh

docs/using/selecting.md
- datascience-notebook now references julia-notebook
- also modified a line under julia-notebook for consistency with r-notebook
=> Update selecting.md without duplicated julia-notebook info

images/pyspark-notebook/Dockerfile, tests/pyspark-notebook/units/unit_pandas_version.py
Upgrade `Apache Spark` from 3.4.1 to 3.5.0
[Release notes](https://spark.apache.org/releases/spark-release-3-5-0.html)
Pandas on Spark API are using 'pandas<=2.0.3' now. 
https://github.com/apache/spark/blob/9c0b803ba124a6e70762aec1e5559b0d66529f4d/dev/infra/Dockerfile#L67C40-L67C40
=> Upgrade `Apache Spark` to 3.5.0

docs/index.rst, docs/maintaining/new-images-and-packages-policy.md, docs/maintaining/tasks.md
I'm combing @consideRatio and @minrk ideas from https://github.com/jupyter/docker-stacks/issues/1958 and my proposal of voting from https://github.com/jupyter/docker-stacks/pull/2000.
Fix: https://github.com/jupyter/docker-stacks/issues/1958
=> Introduce policy for new images/packages

docs/using/selecting.md
One-character fix for broken link to r-notebook tags on quay.
=> Fix broken link to r-notebook tags on quay

tests/docker-stacks-foundation/run-hooks-unset/a.sh, tests/docker-stacks-foundation/run-hooks-unset/b.sh, tests/docker-stacks-foundation/run-hooks-unset/c.sh, tests/docker-stacks-foundation/test_run_hooks.py
=> [FAST_BUILD] Test unset in run-hooks

.github/workflows/registry-move.yml
=> Correctly move multi-arch images from Docker Hub to Quay.io

images/docker-stacks-foundation/start.sh, images/scipy-notebook/Dockerfile
Remove environment variable XDG_CACHE_HOME
Fixes https://github.com/jupyter/docker-stacks/issues/2037
=> Remove environment variable XDG_CACHE_HOME

images/minimal-notebook/setup-scripts/setup-julia-packages.bash
For amd64 (x86_64), we should specify what specific targets the precompilation should be done for.  If we don't specify it, it's *only* done for the target of the host doing the compilation. When the container runs on a host that's still x86_64, but a *different* generation of CPU than what the build host was, the precompilation is useless and Julia takes a long long time to start up. This specific multitarget comes from
https://docs.julialang.org/en/v1/devdocs/sysimg/#Specifying-multiple-system-image-targets, and is the same set of options that the official Julia x86_64 build is compiled with.  If the architecture the container runs on is different, precompilation may still have to be re-done on first startup - but this *should* catch most of the issues.
h/t to …
=> Specify multiple architectures for Julia to precompile to

.github/actions/download-manifests/action.yml, .github/actions/load-image/action.yml, .github/workflows/docker-build-test-upload.yml, .github/workflows/docker-merge-tags.yml, .github/workflows/docker-tag-push.yml
=> Update actions/download-artifact and actions/upload-artifact to v4

README.md
Link to the [rocker/binder](https://rocker-project.org/images/versioned/binder.html) image
as a potential alternative, maintained by the R focused [rocker-project](https://rocker-project.org).
I think of the rocker project as the R equivalent of jupyter/docker-stacks (they maintain
many images in that field!) and it would be good to crosslink.
=> Link to the rocker/binder image as an alternative

images/minimal-notebook/setup-scripts/setup_julia.py
Since the keys are semantic version strings, that means that `"1.9.4" > "1.10.0"`, which we know isn't true. 🙂
I just added some code to convert the string to tuples, find the max, then convert back to a string.
I first noticed this on the `2024-01-05` build of the `datascience-notebook`, since Julia 1.10.0 was released ~2 weeks ago: https://github.com/JuliaLang/julia/releases/tag/v1.10.0.
=> Fix `max(stable_versions)` on Julia version finding

images/base-notebook/docker_healthcheck.py, mypy.ini, tests/base-notebook/test_healthcheck.py
This PR fixes the Docker healthcheck script in `base-notebook` when using custom runtime dirs.
Fix #2073
=> [FAST_BUILD] Fix Docker healthcheck when using custom runtime dirs

images/docker-stacks-foundation/Dockerfile
=> [FAST_BUILD] Update the way we install micromamba

images/pyspark-notebook/Dockerfile, tagging/images_hierarchy.py, tagging/taggers.py
=> Do not bloat spark image with ENV variables

images/pyspark-notebook/Dockerfile, images/pyspark-notebook/setup_spark.py
=> Use argparse to setup spark

images/docker-stacks-foundation/Dockerfile, tests/docker-stacks-foundation/test_python_version.py
Fix: https://github.com/jupyter/docker-stacks/issues/2084
=> Fix Python version pin

.github/workflows/contributed-recipes.yml, aarch64-runner/setup.sh, docs/using/recipe_code/oracledb.dockerfile, images/docker-stacks-foundation/start.sh, tests/docker-stacks-foundation/test_user_options.py
=> Unify access to env variables

docs/using/common.md, docs/using/selecting.md, images/base-notebook/start-notebook.py, images/base-notebook/start-singleuser.py, images/docker-stacks-foundation/Dockerfile, images/docker-stacks-foundation/start.sh, tests/R_mimetype_check.py, tests/all-spark-notebook/test_spark_notebooks.py, tests/base-notebook/test_container_options.py, tests/base-notebook/test_pandoc.py, tests/base-notebook/test_start_container.py, tests/docker-stacks-foundation/test_packages.py, tests/docker-stacks-foundation/test_python_version.py, tests/docker-stacks-foundation/test_units.py, tests/docker-stacks-foundation/test_user_options.py, tests/minimal-notebook/test_nbconvert.py, tests/package_helper.py, tests/run_command.py, tests/scipy-notebook/test_cython.py, tests/scipy-notebook/test_extensions.py, tests/scipy-notebook/test_matplotlib.py
Move `start.sh` from CMD to ENTRYPOINT
This ensures the setup steps performed in start.sh will always be run unless the user overrides the entrypoint. For example, someone can pass `jupyterhub-singleuser` (the default with KubeSpawner) and the image should "just work" as intuitively expected: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2138#issuecomment-828291826
There's a check to prevent re-execution of the script for anyone who continues to pass it as the first CMD.
Closes https://github.com/jupyter/docker-stacks/issues/1528
=> Make `start.sh` the entrypoint

images/docker-stacks-foundation/Dockerfile
I'd expect that if a user wants a particular locale settings they should set it explicitly for themselves. It feels US-centric to default to `en_US`. So let's still generate the `en_US` to make it easier in case people want to change it back, but default to the more standard `C`omputer [format](https://stackoverflow.com/q/55673886).
The `C` option is more sane with things like 24-hr times when running the `date` command.
=> Don't default to US-specific locale settings

README.md, docs/using/selecting.md
=> Improve CUDA enabled images docs and add a policy

docs/using/selecting.md
This is a minor change regarding the header levels. I believe the intent was to have levels:
Selecting an Image
- Core Stacks
- CUDA Enabled Variant
- jupyter/docker-stacks-foundation
- jupyter/base-notebook
- jupyter/minimal-notebook
- ...
- ...
The current iteration seems to indicate that `jupyter/...` derives from the "CUDA Enabled Variant" header when really it is part of the core stack.
In general, I would propose a reorganization of this particular page for additional clarity (perhaps in a future pull request). Mainly I would suggest just moving certain things around and changing some of the header levels.
N/A
=> Updated header level to fit rest of the page

images/pytorch-notebook/cuda11/Dockerfile, images/pytorch-notebook/cuda12/Dockerfile, images/tensorflow-notebook/cuda/Dockerfile, images/tensorflow-notebook/cuda/nvidia-lib-dirs.sh
When using the tensorflow / pytorch images with cuda-variants I expect the ability to work with `nvidia-smi` (system management interface CLI) as in pangeo/pangeo-docker-images (https://github.com/pangeo-data/pangeo-docker-images/blob/09649eb48226cf851d2a8b1d714b850902faa26f/pytorch-notebook/Dockerfile#L8-L12). For this to work though, it needs to be put on PATH and misc library files put on LD_LIBRARY_PATH.
This PR makes that happen for the cuda variant images that prepares other things for work where nvidia drivers gets installed.
> I'm not sure if this merits a test, if so it should be conditional to the cuda variants specifically to check for the environment variables.
> I considered this, but it seems that https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#cud …
=> Put nvidia-smi on path for cuda image variants

images/docker-stacks-foundation/Dockerfile
Add the [netbase Ubuntu package](https://ubuntu.pkgs.org/22.04/ubuntu-main-amd64/netbase_6.3_all.deb.html) to the docker-stacks-foundation image.
This could also go in base, or minimal, but as a part of POSIX it seems like this belongs in the foundation image. It also seems analogous to the locales package installed in the same spot.
Fix: https://github.com/jupyter/docker-stacks/issues/2128
=> Add netbase to docker-stacks-foundation image - fixes #2128

images/docker-stacks-foundation/start.sh, tests/docker-stacks-foundation/test_user_options.py
-  rootless triplet: `-e NB_USER=root` `-e NB_UID=0` `-e NB_GID=0`
=> [FAST_BUILD] No sudo when run with rootless triplet

.github/workflows/docker-build-test-upload.yml, Makefile, images/docker-stacks-foundation/Dockerfile
- Upgrade to Ubuntu 24.04
Ran `DOCKER_BUILD_ARGS='--no-cache make build-all.` All images were built successfully. 
Build Logs ( too big to paste)
https://gist.github.com/jmcgrath207/cf77b5b52cb5c10d45e667ec1052db60
=> Upgrade to Ubuntu 24.04 Image base

docs/using/recipe_code/docker-bake.python312.hcl, docs/using/recipes.md
Add example Bake file for building locally with custom arguments.
The recipe bake file currently just references head of main, I've not mentioned how/why they should change this. Didn't think it was necessary.
Fix #2140
=> Recipe using bake to build with custom arguments

docs/using/recipe_code/ijavascript.dockerfile, docs/using/recipes.md
Fix: https://github.com/jupyter/docker-stacks/issues/2136
=> Fix ijavascript example

docs/contributing/features.md, docs/index.rst, docs/using/custom-images.md, docs/using/recipes.md
=> Create a separate doc page on how to build a custom set of images

docs/using/selecting.md
https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#core-stacks starts with `CUDA enabled variant`, implying it's the first thing people should know about. It's not, since it only applies to a subset of the images.
=> docs: Core Stacks: move CUDA docs to later in the page

.pre-commit-config.yaml, requirements-dev.txt, tests/package_helper.py
This should work fine with both mamba v1 and v2
=> Use mamba env export differently: --no-build(s) and no --json

CHANGELOG.md, Makefile, binder/Dockerfile, docs/using/custom-images.md, docs/using/recipe_code/docker-bake.python312.hcl, images/all-spark-notebook/Dockerfile, images/base-notebook/Dockerfile, images/datascience-notebook/Dockerfile, images/docker-stacks-foundation/Dockerfile, images/julia-notebook/Dockerfile, images/minimal-notebook/Dockerfile, images/pyspark-notebook/Dockerfile, images/pytorch-notebook/Dockerfile, images/pytorch-notebook/cuda11/Dockerfile, images/pytorch-notebook/cuda12/Dockerfile, images/r-notebook/Dockerfile, images/scipy-notebook/Dockerfile, images/tensorflow-notebook/Dockerfile, images/tensorflow-notebook/cuda/Dockerfile
There is no such thing as parent (base/root) container, it's about images, so let's use proper naming
Fix: https://github.com/jupyter/docker-stacks/issues/2154
=> Rename: ROOT_CONTAINER->ROOT_IMAGE, BASE_CONTAINER->BASE_IMAGE

CHANGELOG.md, images/pyspark-notebook/Dockerfile, images/pyspark-notebook/setup_spark.py, tests/all-spark-notebook/test_spark_notebooks.py, tests/pyspark-notebook/test_spark.py, tests/pyspark-notebook/units/unit_pandas_version.py
=> Start using spark4-preview versions

docs/using/specifics.md, images/pyspark-notebook/Dockerfile, images/pyspark-notebook/setup_spark.py
=> Fix docs: we're not installing stable version of spark anymore

CHANGELOG.md, docs/using/recipe_code/jupyterhub_version.dockerfile, docs/using/selecting.md, images/base-notebook/Dockerfile, tests/base-notebook/test_npm_package_manager.py, tests/docker-stacks-foundation/test_packages.py
nodejs was a conda dependency of jupyterhub, but by installing
jupyterhub-base we no longer need it and could opt to remove it.
By doing this, building base-notebook led to a reported size reduction
from 974MB to 828MB, which is a 146MB / 15% size reduction.
- closes https://github.com/jupyter/docker-stacks/issues/2170 which is related if its still open
I removed a test related to `npm`, dependency of `nodejs` conda-forge package.
=> base-notebook: stop installing nodejs from conda-forge

images/minimal-notebook/setup-scripts/setup_julia.py
Julia `1.11.2` has just been released and it seems that it causes our self-hosted aarch64 runners to hang.
Previous build was using `1.11.1` and has been working fine: https://github.com/jupyter/docker-stacks/actions/runs/12123374006/job/33801780215
Let's try to downgrade to `1.11.1` and see if it helps.
=> Downgrade to Julia 1.11.1

.pre-commit-config.yaml
https://github.com/prettier/prettier/issues/15742
=> Use another repo for prettier pre-commit

tests/base-notebook/test_healthcheck.py
=> Specify protocol when using host.docker.internal proxy

images/base-notebook/jupyter_server_config.py
`c.ServerApp.ip = "0.0.0.0"` in `jupyter_server_config.py` configures jupyter-server to listen on all IPv4 interfaces. 
Setting it to `""` configures jupyter-server to listen on [all available (IPv4 and IPv6) interfaces](https://www.tornadoweb.org/en/stable/netutil.html#tornado.netutil.bind_sockets), ensuring these images work with IPv4, IPv6, and dual stack networks.
=> jupyter_server_config.py: Listen on all interfaces (IPv4 and IPv6)

images/base-notebook/start-singleuser.py
JupyterHub controls which interface(s) the singleuser server listens on.
The IP is set in the Spawner configuration, and passed to the singleuser server in the environment variable `JUPYTERHUB_SERVICE_URL`:
https://jupyterhub.readthedocs.io/en/latest/reference/spawners.html#note-on-ips-and-ports
Docker-stacks shouldn't override it. For example, if you configure a JupyterHub container spawner to use a docker-stacks image and use the default CMD it won't work with IPv6.
=> Don't override singleuser ip to 0.0.0.0

.github/workflows/contributed-recipes.yml, .github/workflows/docker-merge-tags.yml, .github/workflows/docker-tag-push.yml, .github/workflows/docker-wiki-update.yml, .github/workflows/docker.yml, .github/workflows/pre-commit.yml, .github/workflows/registry-overviews.yml, .github/workflows/sphinx.yml, docs/using/recipe_code/generate_matrix.py
=> Use ubuntu-24.04 instead of ubuntu-latest

images/all-spark-notebook/README.md, images/base-notebook/README.md, images/datascience-notebook/README.md, images/docker-stacks-foundation/README.md, images/julia-notebook/README.md, images/minimal-notebook/README.md, images/pyspark-notebook/README.md, images/pytorch-notebook/README.md, images/r-notebook/README.md, images/scipy-notebook/README.md, images/tensorflow-notebook/README.md
=> Remove information about Docker Hub images from READMEs

images/datascience-notebook/Dockerfile, images/r-notebook/Dockerfile, tests/docker-stacks-foundation/test_packages.py
=> Pin some packages to fix `r-notebook` and `datascience-notebook` under aarch64

.github/workflows/contributed-recipes.yml, .github/workflows/docker.yml
=> Enable building contributed recipes in PRs

.github/workflows/docker-build-test-upload.yml, .github/workflows/docker-tag-push.yml, CHANGELOG.md
=> Don't create extra free space in runners for cuda images

.github/workflows/docker-build-test-upload.yml, .github/workflows/docker-merge-tags.yml, .github/workflows/docker-tag-push.yml, .github/workflows/docker-wiki-update.yml, Makefile, tagging/apply_tags.py, tagging/common_arguments.py, tagging/merge_tags.py, tagging/update_wiki.py, tagging/write_manifest.py, tagging/write_tags_file.py, tests/run_tests.py
=> Improve handling common parser arguments

.github/workflows/docker-wiki-update.yml, .github/workflows/docker.yml, tagging/Home.md, tagging/update_wiki.py
=> Properly generate wiki home page in forks

.github/workflows/contributed-recipes.yml, .github/workflows/docker-build-test-upload.yml, .github/workflows/docker-merge-tags.yml, .github/workflows/docker-tag-push.yml, .github/workflows/docker-wiki-update.yml, .github/workflows/docker.yml, .github/workflows/pre-commit.yml, .github/workflows/registry-move.yml, .github/workflows/registry-overviews.yml, .github/workflows/sphinx.yml
=> Add timeouts to all GitHub jobs

tagging/utils/docker_runner.py, tests/utils/tracked_container.py
=> Clarify container.remove() behaviour

.github/workflows/docker-build-test-upload.yml, .github/workflows/docker-merge-tags.yml, .github/workflows/docker-tag-push.yml, Makefile, tagging/apps/apply_tags.py, tagging/apps/common_cli_arguments.py, tagging/apps/merge_tags.py, tagging/apps/write_manifest.py, tagging/apps/write_tags_file.py, tagging/hierarchy/get_taggers_and_manifests.py, tagging/manifests/header.py, tagging/utils/config.py, tests/hierarchy/images_hierarchy.py, tests/image_specific_tests/docker-stacks-foundation/test_units.py, tests/run_tests.py
=> Add tagging config to pass params easier

docs/maintaining/tagging.md, tagging/apps/write_manifest.py, tagging/manifests/apt_packages.py, tagging/manifests/build_info.py, tagging/manifests/conda_environment.py, tagging/manifests/julia_packages.py, tagging/manifests/manifest_interface.py, tagging/manifests/r_packages.py, tagging/manifests/spark_info.py
=> [FAST_BUILD] Add MarkdownPiece class to make manifest pieces better structured

wiki/update_wiki.py
=> Use tabulate in wiki to create better tables

.github/workflows/docker-build-test-upload.yml
We already use zst to compress our images, so it shouldn't be necessary to compress on upload.
https://github.com/actions/upload-artifact?tab=readme-ov-file#inputs
`For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.`
=> Do not compress images in `actions/upload-artifact`

CHANGELOG.md, tagging/hierarchy/images_hierarchy.py, tagging/taggers/versions.py
=> Add tags for mamba and conda versions

tests/by_image/base-notebook/test_healthcheck.py
=> Refactor healthcheck tests to use one function

.github/actions/create-dev-env/action.yml, .github/workflows/docker-build-test-upload.yml, tests/by_image/base-notebook/data/check_listening.py, tests/by_image/base-notebook/test_healthcheck.py, tests/by_image/base-notebook/test_ips.py, tests/conftest.py, tests/utils/get_container_health.py
=> Test server listening on IPv4/IPv6

images/base-notebook/start-notebook.py, images/base-notebook/start-singleuser.py, tests/by_image/base-notebook/test_start_container.py
=> Flush output in Python before running execvp

tests/by_image/docker-stacks-foundation/test_user_options.py, tests/utils/tracked_container.py
=> Use tty for running docker commands by default

tagging/utils/docker_runner.py, tests/conftest.py, tests/pytest.ini, tests/utils/conda_package_helper.py, tests/utils/tracked_container.py
=> Improve logs around running docker

CHANGELOG.md, images/tensorflow-notebook/Dockerfile, images/tensorflow-notebook/cuda/Dockerfile, tests/by_image/docker-stacks-foundation/test_packages.py
=> Use mamba to install jupyter-server-proxy

requirements-dev.txt, tests/by_image/all-spark-notebook/test_spark_r_nbconvert.py, tests/by_image/docker-stacks-foundation/test_user_options.py, tests/by_image/pyspark-notebook/test_spark_nbconvert.py
=> Try to unmark tests as flaky

.github/workflows/docker-merge-tags.yml, .github/workflows/docker-tag-push.yml
=> Robust registry operations: adjust timelimit and use retries

.github/workflows/docker-merge-tags.yml
Now we install latest docker engine, so the problem might be gone.
We will stop installing latest docker, when runners update built-in version to a recent one (should happen in May).
I will revert this change, if docker will be stuck during `docker pull`
=> Do not reset docker state

.github/actions/load-image/action.yml, .github/workflows/docker-build-test-upload.yml, .github/workflows/docker-tag-push.yml, .github/workflows/docker-wiki-update.yml, .github/workflows/registry-move.yml
=> Unify multiline run statements in GitHub Actions steps

images/pyspark-notebook/setup_spark.py, tagging/apps/apply_tags.py, tagging/apps/merge_tags.py, tagging/apps/write_manifest.py, tagging/utils/get_prefix.py, tests/by_image/base-notebook/test_healthcheck.py, tests/by_image/docker-stacks-foundation/test_run_hooks.py, tests/utils/tracked_container.py
=> Force using keyword-only arguments where types are the same

.github/workflows/contributed-recipes.yml, docs/using/custom-images.md
=> Use proper BASE_IMAGE in contributed recipes for forks

images/pytorch-notebook/cuda12/Dockerfile
Upgrade the CUDA-version used in the PyTorch image from 12.4 to 12.8 . This is needed to get PyTorch working on recent GPUs like the RTX5090 with nvidia drivers R570 which has CUDA version 12.8 .
I tested the resulting image on an older machine which is running R535 with CUDA version 12.2, and my local tests ran fine. I don't think that there are any adverse effects to upgrading the CUDA version used.
Also, note that the PyTorch-release with CUDA 12.4 is not even mentioned anymore on https://pytorch.org/get-started/locally/, so it makes sense to update our version used to something that is officially supported.
For further reference, the following script was used to diagnose the original issue I had:
```python
import torch
device = torch.device("cuda" if torch.cuda.is_available() else …
```
=> Upgrade CUDA version used in PyTorch cuda12-variant to 12.8

.flake8, images/docker-stacks-foundation/run-hooks.sh, images/docker-stacks-foundation/start.sh, tests/by_image/docker-stacks-foundation/test_run_hooks.py, tests/by_image/docker-stacks-foundation/test_user_options.py, tests/utils/tracked_container.py
- use `_log` in run-hooks.sh, like start.sh (needs to redefine it for unnittests only, could split into a common utility file)
- `_log` writes to stderr instead of stdout for easier output capture (piping, etc.)
In general, it's a good practice to avoid logging to stdout, since it means you can't capture command output with pipes, e.g.
```
docker run --rm -it quay.io/jupyter/base-notebook conda env export > base-env.yml
```
because it will include the 'uid: 1000`, etc. messages.
I looked through the tests, and it's tricky because the tests run with `tty: true`, in which case docker merges stdout and stderr, so can't test the splitting is correct. Running with `tty: false`, e.g. `docker run --rm -i pwd > stdout.txt 2>stderr.txt` does the right thing in a manual test. I'm just not 100% sure …
=> log hook messages to stderr

CHANGELOG.md, Makefile, README.md, images/docker-stacks-foundation/Dockerfile, tests/by_image/docker-stacks-foundation/test_python_version.py
=> Switch to Python 3.13
