- Makefile
- pyspark-notebook/Dockerfile
- pyspark-notebook/README.md
Plus README explaining how to use pyspark in local mode and with a Mesos cluster.
> Notebook stack for Python w/ Spark on Mesos

- Makefile
- all-spark-notebook/Dockerfile
- all-spark-notebook/README.md
- all-spark-notebook/kernel.json
Includes lengthy README on setting up each in local mode or in cluster mode against Mesos.
> Notebook stack Scala, Python, and R w/ Spark on Mesos

- all-spark-notebook/Dockerfile
- r-notebook/Dockerfile
> Pin irkernel build to avoid auto-upgrade to notebook 4.0

- minimal-notebook/jupyter_notebook_config.py
> Ensure PEM file directory exists before creating file.

- Makefile
- README.md
Ref #12 
Would appreciate a review of the README steps which would be the manual flow for building / pushing new images for the time being. If there's a TON of traffic here that makes manually running the few commands there untenable, we can start to look into automating it with a CI system that runs the make target instead.
> New versioning scheme

- README.md
- all-spark-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
> Readme updates to remove legacy version info

- all-spark-notebook/Dockerfile
- all-spark-notebook/README.md
- pyspark-notebook/Dockerfile
- pyspark-notebook/README.md
Based on PR #52 but with additional workaround commit for upstream pkg problem noted in #55.
> Update to Spark 1.5.1

- all-spark-notebook/README.md
- pyspark-notebook/README.md
Instructions for opening additional ports on docker run command in order to view the spark Monitoring and Instrumentation UI.
> Updating Readmes for Spark UI support

- scipy-notebook/Dockerfile
patsy, numba, bokeh all need upgrade to satisfy conda constraints
Ref #69
> Fix scipy-notebook build after pandas bump

- all-spark-notebook/Dockerfile
- all-spark-notebook/kernel.json
The latest Spark Kernel uses make to build/package. This changes reflect how to build and setup Spark Kernel.
> Updating to reflect changes in how Spark Kernel is build and packaged

- minimal-notebook/Dockerfile
Avoids costly chown, fixes #81.
Unfortunately, we cannot build all containers that depend on minimal at the moment because the #55 workaround is no longer viable.
> Create jovyan user before conda install

- all-spark-notebook/Dockerfile
- all-spark-notebook/README.md
- datascience-notebook/Dockerfile
- datascience-notebook/README.md
- minimal-notebook/Dockerfile
- minimal-notebook/README.md
- minimal-notebook/start-notebook.sh
- pyspark-notebook/Dockerfile
- pyspark-notebook/README.md
- r-notebook/Dockerfile
- r-notebook/README.md
- scipy-notebook/Dockerfile
- scipy-notebook/README.md
* Switch to jovyan at the end of every Dockerfile
* Document --user root requirement for NB_UID and GRANT_SUDO flags
Resolves #91
> Make jovyan the default user for the docker cmd

- minimal-notebook/Dockerfile
> Add texlive-generic-recommended to fix PDF export

- Makefile
- all-spark-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/Dockerfile
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
Conda rev'ed to Notebook 4.1.0. Updated pinned install to 4.1*. 
Manually tested plotting, different kernels, and Spark across images. Nothing seems amiss. (Would be nice to have a small suite of notebook-based sniff tests that we could run automatically against each stack using Selenium or something ...)
> Notebook 4.1.x

- all-spark-notebook/Dockerfile
- all-spark-notebook/README.md
- pyspark-notebook/Dockerfile
- pyspark-notebook/README.md
Fixes #109 
/cc @jakirkham @boechat107
> Set PYSPARK_PYTHON path in python2 kernelspec

- all-spark-notebook/Dockerfile
- pyspark-notebook/Dockerfile
Tested R, Python 2 and 3, and Scala samples from READMEs. 
Fixes #116
> Fix py4j version and path

- all-spark-notebook/Dockerfile
- pyspark-notebook/Dockerfile
- scipy-notebook/Dockerfile
Includes changes from #121 in other stacks so that everything builds successfully off of the minimal-notebook image.
> Bump python libs to match other images

- datascience-notebook/Dockerfile
- scipy-notebook/Dockerfile
> Add libav-tools for matplotlib animation

- all-spark-notebook/Dockerfile
- datascience-notebook/Dockerfile
- pyspark-notebook/Dockerfile
- scipy-notebook/Dockerfile
Missing some `--yes`/`-y` options for `conda` in a few places. This cleans them up.
> Ensure conda works automatically

- all-spark-notebook/Dockerfile
- datascience-notebook/Dockerfile
- minimal-notebook/Dockerfile
- pyspark-notebook/Dockerfile
- r-notebook/Dockerfile
- scipy-notebook/Dockerfile
Related: https://github.com/jupyter/docker-stacks/issues/62
This cleans out just about everything `conda` can remove. The most notable thing is this removes any unused packages that are lingering.
> Clean conda

- all-spark-notebook/Dockerfile
I've modified the Dockerfile to use `pip` to install Apache Toree. 
It also is set to move to the latest 0.1.0.dev release. @parente Let me know how you feel about this. I'm glad with putting a specific version.
> Modified to install Apache Toree using pip

- all-spark-notebook/Dockerfile
- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
Combines the conda config update line and the installation of R packages into the same `RUN` command.
> Add and install from the r channel with conda

- datascience-notebook/Dockerfile
> Rebase datascience-notebook on scipy-notebook

- all-spark-notebook/Dockerfile
- pyspark-notebook/Dockerfile
Closes https://github.com/jupyter/docker-stacks/pull/161
To speed up build, reduce accidental disparity, ease maintenance.
> Rebase all-spark-notebook on pyspark-notebook

- all-spark-notebook/README.md
- datascience-notebook/README.md
- minimal-kernel/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
> [ci skip] Add badges to stack READMEs

- .gitignore
- Makefile
- README.md
- all-spark-notebook/README.md
- datascience-notebook/README.md
- internal/build-singleuser
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
For every `*-notebook` stack, a `*-singleuser` image is also built
cf jupyter/dockerspawner#82
> build JupyterHub singleuser images for each notebook stack

- README.md
I really like this image and want to move it higher on the page so it catches more views :smile:
> Move the overview image up on README page

- pyspark-notebook/Dockerfile
- scipy-notebook/Dockerfile
> Add numexpr to wherever pandas is

- all-spark-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
Update text to be consistent with list of documented options.
> README: Change NB_USER to NB_UID

- all-spark-notebook/README.md
Never got updated when Toree started getting pip installed. Addresses some of the questions in #180, #169. Fixes #167.
> Update README for current Apache Toree

- all-spark-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
Fixes remainder of READMEs that have it
> [skip ci] Remove old pem path

- all-spark-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/Dockerfile
- minimal-notebook/README.md
- pyspark-notebook/Dockerfile
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/Dockerfile
- scipy-notebook/README.md
Need to wait for ipywidgets 5.0 on conda
> [WIP] Upgrade to notebook 4.2, ipywidgets 5.0

- all-spark-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
> [no ci] Document notebook.pem format

- all-spark-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
Update files for changed link.
> Update README links

- minimal-notebook/Dockerfile
https://github.com/docker-library/official-images/pull/1695
> Update debian base image for CVEs

- .travis.yml
- Makefile
Some makefile cleanup too. Tests run interspersed with individual
image builds to fail-fast.
> Add liveliness check

- pyspark-notebook/Dockerfile
Fixes https://github.com/jupyter/docker-stacks/issues/164
> Use `jq` from conda-forge

- datascience-notebook/Dockerfile
rather than all kernelspecs that might be in the user kernelspec dir
cf https://github.com/jupyter/docker-demo-images/pull/94
> Only move julia kernelspec

- scipy-notebook/Dockerfile
* A fix for a pandas feature used in https://github.com/jupyter-incubator/declarativewidgets/issues/426 is included in this updated version.
> Update pandas version to 0.18*

- scipy-notebook/Dockerfile
- scipy-notebook/mplimporthook.py
Fixes #235 and avoids repeat regressions
> Default matplotlib to inline backend

- base-notebook/Dockerfile
> Temporary workaround for #210

- all-spark-notebook/README.md
- base-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
Already supported via the command line.
Update all the READMEs.
Fixes #220
> Document how to set a hashed password

- minimal-notebook/Dockerfile
> Add inkscape to fix SVGs in PDFs

- scipy-notebook/Dockerfile
> add sqlalchemy to conda install command

- .travis.yml
- Makefile
- README.md
* Don't pull images onto travis. Caching doesn't work. See #150 
* Add retry option #131
> Build improvements

- Makefile
- tensorflow-notebook/.dockerignore
- tensorflow-notebook/Dockerfile
- tensorflow-notebook/README.md
> add tensorflow book

- r-notebook/Dockerfile
Resolves https://github.com/IRkernel/IRkernel/issues/399 by adding a dependency that was introduced.
> Adds crayon to the r notebook image

- scipy-notebook/Dockerfile
> Update ipywidgets to 5.2

- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
Also update irkernel to fix base_display problem on rebuild
> Fix #269, NB_UID regression

- scipy-notebook/Dockerfile
This update allows pandas to use parameter "lines" in function `pd.read_json()`.
See http://pandas-docs.github.io/pandas-docs-travis/io.html#io-jsonl
> Update pandas to version 0.19*

- scipy-notebook/Dockerfile
* Bump numexpr to 2.6 so it comes from conda-forge
* Install nomkl
Fixes #295
> Don't mix mkl and open_blas packages

- scipy-notebook/Dockerfile
- scipy-notebook/README.md
Also adds support to install from pip.
> Add vincent, beautifulsoup, and xlrd to scipy-notebook

- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
Remove pinning for plotting fix and upgrade other R packages
> Upgrade to r-base 3.3.2

- scipy-notebook/Dockerfile
> update scikit-learn to latest release (v0.18*)

- README.md
> Update JHub compatibility note

- all-spark-notebook/Dockerfile
- pyspark-notebook/Dockerfile
> Fix #345: Move to Spark 2.1, spylon-kernel to 0.2

- pyspark-notebook/Dockerfile
changed the version of mesos to avoid backward compatibility issue
> PR for issue #367

- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
- add a few missing `--system` flags to conda config
- install default notebook config to /etc/jupyter instead of ~/.jupyter
- add a few missing `conda clean`s
cc @yuvipanda
> reduce files in home directory a bit

- base-notebook/start.sh
Follow-up from missed comment in #388.
> Fix chown of $NB_USER home

- base-notebook/start.sh
Signed-off-by: Gaetan Semet <gaetan@xeberon.net>
> Fix sudoers.d inclusion with debian img (fix #394)

- base-notebook/start.sh
Ease user understanding about what's going out on startup
Signed-off-by: Gaetan Semet <gaetan@xeberon.net>
> Add logs to start.sh

- all-spark-notebook/README.md
- pyspark-notebook/Dockerfile
- pyspark-notebook/README.md
> [Update] Spark updated to 2.1.1

- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- minimal-notebook/Dockerfile
- r-notebook/Dockerfile
* Fixes #379
* Fixes #382
* Fixes #298
> miniconda 4.3.x, python 3.6, spylon 0.4, sparklyr

- all-spark-notebook/README.md
- pyspark-notebook/Dockerfile
- pyspark-notebook/README.md
Upgrade Spark to 2.2.0
https://spark.apache.org/releases/spark-release-2-2-0.html
> Upgrade Spark to 2.2.0

- base-notebook/start.sh
if some env vars are set that aren't used, complain about it so behaviour is a bit less surprising.
> warn about unused config

- README.md
> [ci skip] Note in README about Python 2.x

- all-spark-notebook/README.md
- base-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
- tensorflow-notebook/README.md
> [ci skip] Documentation improvements

- tensorflow-notebook/README.md
> [ci skip] Remove py2 reference

- scipy-notebook/Dockerfile
> Update ipywidgets to 7.0.x

- README.md
- internal/inherit-diagram.svg
Based on https://github.com/jupyter/docker-stacks/pull/428/commits/0351f0c3b7743026e2aec161b8e23a4182408c74
> Fix inherit-diagram: debian@SHA -> ubuntu@SHA

- base-notebook/start.sh
Improve start.sh logging along the way. Fixes #442.
> Fix working directory problems with custom NB_USER

- base-notebook/start.sh
- don't relocate home if home exists (e.g. mounted volume)
- respect workdir, only cd to new home if we were in /home/jovyan/
#455 broke SystemUserSpawner, where workdir is already set and /home/$NB_USER is a mounted volume that should not be modified.
> homedir fixes

- README.md
`:latest` is never a reliable base.
> Further emphasize the use of tags in README

- scipy-notebook/Dockerfile
* Don't change WORKDIR
* Fix permissions after install
* Cleanup source tree
Fixes #460 . Subsumes #461.
> Fix facets install

- all-spark-notebook/Dockerfile
-The following patch addresses issue #489
(https://github.com/jupyter/docker-stacks/issues/489)
> Patch R package install user issues

- datascience-notebook/Dockerfile
Updates Julia to 0.6.0 (fixes #454)
> julia 0.6.0

- .travis.yml
- Makefile
- base-notebook/Dockerfile
- base-notebook/start.sh
- base-notebook/test/test_container_options.py
- conftest.py
- requirements-test.txt
- scipy-notebook/Dockerfile
- test/test_notebook.py
* Port server liveliness test from make to test/test_notebook.py
* Add placeholders for base-notebook tests
* Update travis config to install test dependencies on the host
> pytest integration tests

- base-notebook/start.sh
- base-notebook/test/test_container_options.py
Fixes #524. Adds a test to prevent regression.
> Append /opt/conda/bin to the sudo secure_path

- r-notebook/Dockerfile
Fixes #532. Caveat: I am not set up to test this.
> Update Dockerfile to install r-hexbin

- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- base-notebook/Dockerfile.ppc64le
- datascience-notebook/Dockerfile
- minimal-notebook/Dockerfile
- pyspark-notebook/Dockerfile
- r-notebook/Dockerfile
- scipy-notebook/Dockerfile
For full details on the requirement for this patch see https://github.com/jupyter/docker-stacks/issues/549
> Use NB_UID for USER statement in Dockerfile so deployment platform can verify that image doesn't run as root.

- base-notebook/start.sh
> Chown of home dir needs to be recursive

- Makefile
- datascience-notebook/Dockerfile
I'm thinking the Julia build might be the long pole here. Pushing this just to test how it changes the build time.
Ref: #577
> Disable datascience-notebook precompilation

- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- datascience-notebook/Dockerfile
- minimal-notebook/Dockerfile
- r-notebook/Dockerfile
> Fix netcat, pin tornado 4.x for R + zmq issues, update various R libs

- .travis.yml
- datascience-notebook/Dockerfile
> Add TEST_ONLY_BUILD arg

- tensorflow-notebook/README.md
This PR relates to issue #582.
Added instructions for distributed mode to the tensorflow-notebook readme.
> Update tensorflow-notebook readme with distributed mode instructions

- base-notebook/Dockerfile
- pyspark-notebook/Dockerfile
Fixes #589 if it builds without downgrading
> Remove tornado<5 pin

- base-notebook/Dockerfile
- scipy-notebook/Dockerfile
Fix suggested by @mimoralea in PR #617. (Thanks!)
> Force npm cache clean

- tensorflow-notebook/Dockerfile
> Update tensorflow to 1.5, keras to 2.1

- scipy-notebook/Dockerfile
pandas, scipy, matplotlib, etc.
> Update scipy-notebook packages

- base-notebook/jupyter_notebook_config.py
https://github.com/jupyter/notebook/issues/3130
Now, files not delete on https://hub.docker.com/r/jupyter/base-notebook/ and derived container images.
> send2trash not work

- minimal-notebook/Dockerfile
#514 
Add nano and vim editors to Dockerfiles.
> Add nano and vim to Dockerfiles

- base-notebook/Dockerfile
Fixes https://github.com/jupyter/docker-stacks/issues/647
Upgrades to `conda` 4.5.4 (latest) from conda-forge.
> Upgrade to conda 4.5.4

- base-notebook/Dockerfile
- base-notebook/Dockerfile.ppc64le
Also added the option to send signal to all child group processes as mentioned in docs
https://github.com/krallin/tini#process-group-killing
> upgrade tini to latest version 0.18.0

- docs/using/recipes.md
Updated the recipe for pip to include requirements.txt file.
Also included example for using conda to install packages.
> Updated recipe for pip and added conda example.

- README.md
- base-notebook/Dockerfile
- docs/index.rst
- scipy-notebook/Dockerfile
- notebook 5.5
- matplotlib 2.2
- pandas 0.23
- scipy 1.1
- scikit-image 0.14
- statsmodels 0.9
> bump some packages

- scipy-notebook/Dockerfile
Image build and tested; everything works fine.
> Update version of seaborn to 0.9.X

- base-notebook/Dockerfile
- scipy-notebook/Dockerfile
Tested with: `make build-test-all`
> Bump up jupyterlab & extensions version

- .travis.yml
- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- docs/using/running.md
- scipy-notebook/Dockerfile
- tensorflow-notebook/Dockerfile
Cherry-picking #726 into this to get a clean build. (Fixes #710)
> Fix builds by updating to compatible versions

- base-notebook/Dockerfile
> Changed Dockerfile for USER/ID/GID to be Docker build arguments

- docs/using/recipes.md
Closes #728 
Hi @taqtiqa-mark -- Can you read through this and give me feedback on how well I represented your use case?
> Add note for launching notebook with no token

- docs/index.rst
> [skip ci] Fix JUPYTER_ENABLE_LAB example

- Makefile
> [ci skip] Disable linkcheck

- base-notebook/Dockerfile
- pyspark-notebook/Dockerfile
> Bumped Spark to 2.4.0 and miniconda to 4.5.11

- base-notebook/Dockerfile
- scipy-notebook/Dockerfile
> Update JupyterLab and extensions to 0.35.4

- tensorflow-notebook/Dockerfile
Current release is 1.12.0 https://anaconda.org/anaconda/tensorflow
> Update tensorflow to 1.12

- .gitignore
- docs/using/common.md
Closes #715
Following the suggestion from @parente in #715. Minimal documentation to start since the use case seems pretty self-explanatory. I'm happy to add more prose if necessary.
> Add note about customizing the startup with before-notebook.d

- all-spark-notebook/Dockerfile
Try updating other libs in the image to get r-sparklyr to use noarch package for 0.9.3.
> Update all R libs in all-spark-notebook for Spark 2.4 

- README.md
- binder/Dockerfile
- binder/README.ipynb
- docs/index.rst
plus update some example image tags in the docs for good measure while I'm touching the files.
> Add an example binder

- binder/Dockerfile
Hardcode the tag in two places
> [ci skip] ARG does not survive past FROM

- scipy-notebook/Dockerfile
update ipywidgets to 7.4
https://ipywidgets.readthedocs.io/en/stable/changelog.html
> scipy-notebook: update ipywidgets

- r-notebook/Dockerfile
I recommend to add the support for ODBC.
> Support for ODBC

- docs/index.rst
> Add intermediate example to describe port mapping

- base-notebook/Dockerfile
Fix permissions in parent dir of $CONDA_DIR instead of $CONDA_DIR
> Fix for build error #807

- scipy-notebook/Dockerfile
Fixes https://github.com/jupyter/docker-stacks/issues/816
> Require Dask 1.1 in the scipy-notebook

- base-notebook/Dockerfile
> notebook 5.7.5

- all-spark-notebook/hooks/index.tmpl
- all-spark-notebook/hooks/manifest.tmpl
- all-spark-notebook/hooks/post_push
- base-notebook/hooks/index.tmpl
- base-notebook/hooks/manifest.tmpl
- base-notebook/hooks/post_push
- datascience-notebook/hooks/index.tmpl
- datascience-notebook/hooks/manifest.tmpl
- datascience-notebook/hooks/post_push
- minimal-notebook/hooks/index.tmpl
- minimal-notebook/hooks/manifest.tmpl
- minimal-notebook/hooks/post_push
- pyspark-notebook/hooks/index.tmpl
- pyspark-notebook/hooks/manifest.tmpl
- pyspark-notebook/hooks/post_push
- r-notebook/hooks/index.tmpl
- r-notebook/hooks/manifest.tmpl
- r-notebook/hooks/post_push
- scipy-notebook/hooks/index.tmpl
- scipy-notebook/hooks/manifest.tmpl
- scipy-notebook/hooks/post_push
- tensorflow-notebook/hooks/index.tmpl
- tensorflow-notebook/hooks/manifest.tmpl
- tensorflow-notebook/hooks/post_push
> [ci skip] Improve manifests, update index page

- all-spark-notebook/hooks/manifest.tmpl
- pyspark-notebook/hooks/manifest.tmpl
> [ci skip] Fix spark version check

- all-spark-notebook/Dockerfile
- datascience-notebook/Dockerfile
- docs/using/selecting.md
- minimal-notebook/Dockerfile
- r-notebook/Dockerfile
This makes TZ environment actually useful.
> Move tzdata to minimal-notebook and document it

- base-notebook/Dockerfile
> bump notebook, jupyterhub

- docs/contributing/issues.md
- docs/index.rst
https://discourse.jupyter.org/t/responsible-vulnerability-reporting/655
> Add vulnerability reporting info

- .travis.yml
- Makefile
- docs/.tx/config
- docs/conf.py
- docs/contributing/features.md
- docs/contributing/recipes.md
- docs/locale/en/LC_MESSAGES/contributing.po
- docs/locale/en/LC_MESSAGES/index.po
- docs/locale/en/LC_MESSAGES/maintaining.po
- docs/locale/en/LC_MESSAGES/using.po
- docs/using/common.md
- docs/using/recipes.md
- docs/using/selecting.md
- requirements-dev.txt
> Try RTD+Transifex workflow

- base-notebook/Dockerfile
This contains a fix for chrome download file bug: https://github.com/jupyterlab/jupyterlab/pull/6232
> Update to JupyterLab 0.35.5

- pyspark-notebook/Dockerfile
Spark 2.4.1 is gone from the mirror.
> Update to Spark 2.4.2

- .readthedocs.yml
- readthedocs.yml
- Update to v2
- Create config as a dotfile
> Update RTD config file to v2

- docs/using/specifics.md
https://github.com/jupyter/docker-stacks/issues/875
> Add `Specific Docker Image Options` for jupyter spark

- base-notebook/Dockerfile
Attempt to fix build errors in #906 
@clkao I retained your commits. I tried to push to your PR branch but was denied access.
> Bump notebook to 6.0.0, jupyterlab to 1.0.4, conda to 4.7.10

- all-spark-notebook/Dockerfile
- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
- scipy-notebook/Dockerfile
New versions found with `conda upgrade --all` inside the current image,
which I guess is the right way to do it.  Only scipy-notebook so far.
It builds but I haven't done any live tests yet.
> Update all package versions

- datascience-notebook/Dockerfile
Use the latest stable version of Julia.
> bump Julia version (1.1.0 => 1.1.1)

- base-notebook/Dockerfile
- pyspark-notebook/Dockerfile
This PR addresses updating base notebook to jupyterlab 1.1.3 in order to fix the sidebar issues as well as a myriad of other issues present in the recent 1.0.x releases.
#936
> Address updating base notebook to jupyterlab 1.1.3

- base-notebook/Dockerfile
> update jupyterlab to 1.2.1

- base-notebook/start.sh
Workaround of a Docker bad handling of sparse files
Fixes #923
> Modify the way to change user uid/gid

- docs/using/recipes.md
this was surprisingly hard to find help for online that was up-to-date and worked with the stacks, contributing here in hopes it'll help others.
> instructions for python 3.x kernels with conda

- base-notebook/Dockerfile
it should be there automatically, but no harm in being explicit
bump notebook to 6.0.3 while we are here
closes #988
> install pip explicitly

- base-notebook/Dockerfile
- Replace `ADD` with `COPY` as its documented as the [preferred option](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/)
> chore: Replace ADD with COPY

- pyspark-notebook/Dockerfile
- pyspark-notebook/test/test_spark.py
https://github.com/jupyter/docker-stacks/commit/45d51e3b42b83748fe64997b0e39473aeee10377#r37272915
> Fix pyspark path

- base-notebook/Dockerfile
Everything is in the title :smile:
> Bump Ubuntu Base Image

- docs/using/recipes.md
Closes #999 
Happy to receive any feedback as this was my first Dockerfile.
> recipe: dask

- docs/using/selecting.md
- scipy-notebook/Dockerfile
- test/test_packages.py
This adds two optional dependencies for pandas
bottleneck
and
pytables
These relate to issues #1066 and #1063.
> add pytables and bottleneck

- Makefile
- minimal-notebook/test/test_nbconvert.py
- scipy-notebook/test/data/matplotlib_1.py
- scipy-notebook/test/test_matplotlib.py
- scipy-notebook/test/test_pandas.py
- tensorflow-notebook/test/test_tensorflow.py
- test/test_notebook.py
* `Maplotlib` is an important package. It has now its own test checking that a plot can be generated and exported as an image.
* Some helpers methods added to the `Makefile` mainly permitting to clean containers and images.
* Improved assertion messages of some tests.
> Matplotlib tests + helpers methods

- docs/using/recipes.md
For folks wanting to experiment with auto_sklearn, its easy to get it cleanly installed with this Dockerfile.
Thanks!
> Add a recipe for auto_sklearn

- Makefile
- all-spark-notebook/hooks/manifest.tmpl
- base-notebook/hooks/manifest.tmpl
- datascience-notebook/hooks/manifest.tmpl
- minimal-notebook/hooks/manifest.tmpl
- pyspark-notebook/hooks/manifest.tmpl
- r-notebook/hooks/manifest.tmpl
- scipy-notebook/hooks/manifest.tmpl
- tensorflow-notebook/hooks/manifest.tmpl
As far as I understand, some people worry about image sizes.
So, I added a simple print statement to make it easier to notice the changes in the logs after building the image.
> Print image size after building it

- .github/workflows/docker.yml
- .github/workflows/sphinx.yml
- docs/contributing/features.md
- docs/contributing/packages.md
- docs/contributing/stacks.md
- docs/contributing/tests.md
- docs/maintaining/tasks.md
- docs/using/selecting.md
- requirements-dev.txt
Follow-on to #1132 to correct PR build errors and update relevant documentation. Steps that execute upon merge to master may still require further debugging.
> Update doc, Dockerfile to test GH Actions

- scipy-notebook/Dockerfile
https://pandas.pydata.org/docs/whatsnew/v1.1.0.html
> Pandas to 1.1

- Makefile
> Fix git-commit upstream

- datascience-notebook/Dockerfile
Julia update to 1.5.0
* https://julialang.org/blog/2020/08/julia-1.5-highlights/
> update to julia 1.5.0

- scipy-notebook/Dockerfile
- scipy-notebook/test/data/matplotlib_fonts_1.py
- scipy-notebook/test/test_matplotlib.py
This follows on from #1162 and correcting a messed up git history and adding changes requested from @romainx
> add cm-super

- scipy-notebook/test/test_matplotlib.py
Just a refactor of the `matplotlib` tests to avoid code duplication.
> Matplotlib test refactoring (Follow-on PR #1169)

- docs/using/selecting.md
- minimal-notebook/Dockerfile
A tiny improvement, but consistent with what has already been done.
> nano -> nano-tiny

- docs/using/selecting.md
- minimal-notebook/Dockerfile
Fix https://github.com/jupyter/docker-stacks/issues/1174
> Remove emacs and jed from the minimal image

- .github/workflows/docker.yml
- Makefile
Enable [Docker BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements/) to try to improve build performances and maybe benefit from other features.
> Enable Docker BuildKit

- base-notebook/Dockerfile
Follow-up on: https://github.com/jupyter/docker-stacks/pull/1046#issuecomment-774636297
> JLab clean instead of rm in base docker

- base-notebook/Dockerfile
- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
- scipy-notebook/Dockerfile
Small updates mainly to trigger a reinstall of `sudo` and fix #1235.
> Regular update

- Makefile
- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
- scipy-notebook/Dockerfile
Hello,
A standard update.
Best.
> Regular update 2021-03-17

- base-notebook/Dockerfile
Otherwise JupyterLab doesn't load in Safari:
https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v3-0-12
> Update JupyterLab to 3.0.12

- docs/using/recipes.md
Hi everyone!
As more and more people are using Databricks and Delta Lake engine, this recipe may be useful for others. 
Best!
> Added recipe for Delta lake

- tensorflow-notebook/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/1268
> Install tensorflow from conda instead of pip

- .github/workflows/docker.yml
- .github/workflows/sphinx.yml
**NOTE: someone more experienced in GitHub actions should tell that this is fine.**
Also, there is no way I could check this (because my permissions are very limited)
Fix: https://github.com/jupyter/docker-stacks/issues/1280
The advice I used: https://github.com/jupyterhub/team-compass/issues/404#issue-863678103
> Add write permissions to github jobs

- base-notebook/Dockerfile
Title says it all.
I was not able to locally test due to [known issues](https://docs.docker.com/docker-for-mac/apple-silicon/#known-issues) with Docker on Apple silicon.
> Update Ubuntu 20.04 LTS (Focal Fossa) base image

- Makefile
- base-notebook/Dockerfile
- base-notebook/test/test_python.py
- datascience-notebook/Dockerfile
- pyspark-notebook/Dockerfile
- scipy-notebook/Dockerfile
- tensorflow-notebook/Dockerfile
Hello,
- Few packages updated
- Fix Hadolint warnings
- Style
Not updated Mambaforge version since it brings a new version of Python `3.9` thanks @mathbunnyru for the heads-up.
- Added a test to check the Python version to avoid this kind of surprise in the future.
Best.
> Regular update 2021-05-04

- all-spark-notebook/kernel.json
This file usage was deleted 5 years ago!
https://github.com/jupyter/docker-stacks/pull/144/files
> Remove unused all-spark-notebook/kernel.json

- docs/using/recipes.md
Hello everyone,
Seeing that delta is now available through pypy and includes python methods for downloading the delta packages, I have updated the recipe.
Best! 
Tony
> Updating the recipe for 1.0.0 release of delta

- docs/using/selecting.md
- scipy-notebook/Dockerfile
This was already done in https://github.com/jupyter/docker-stacks/pull/1319 (and approved there), but it's better to have a separate commit, which is easier to revert if something bad happens. Also, it's not an update, so also doesn't make a lot of sense there.
> Replace vincent with altair

- docs/using/specifics.md
Hello,
As suggested by @mathbunnyru this a try to improve the documentation and add a section explaining how to define Spark dependencies. This fixes #1334.
Suggestions / improvements are welcome!
Best.
> How to define Spark Dependencies

- .github/workflows/docker.yml
Fix: https://github.com/jupyter/docker-stacks/issues/1347
> Use DOCKERHUB_TOKEN secret name instead of DOCKERHUB_PASSWORD

- docs/contributing/stacks.md
This is in sync with: https://github.com/jupyter/cookiecutter-docker-stacks/pull/13
> Update cookiecutter instruction because of project changes

- all-spark-notebook/test/test_spark_notebooks.py
- base-notebook/test/test_package_managers.py
- base-notebook/test/test_start_container.py
- datascience-notebook/test/test_julia.py
- minimal-notebook/test/test_nbconvert.py
- pyspark-notebook/test/test_spark.py
- scipy-notebook/test/test_matplotlib.py
- scipy-notebook/test/test_pandas.py
- tagging/docker_runner.py
- tensorflow-notebook/test/test_tensorflow.py
After the test failure, it would be very convenient to use debug logging level and there will be logs probably indicating the problem.
> Move assert after logs output to make debug easier

- README.md
- all-spark-notebook/README.md
- base-notebook/README.md
- datascience-notebook/README.md
- minimal-notebook/README.md
- pyspark-notebook/README.md
- r-notebook/README.md
- scipy-notebook/README.md
- tensorflow-notebook/README.md
MicroBadger.com will shutdown on 1st July 2021.
https://microbadger.com/shutdown
> Remove microbadge usage

- .github/workflows/docker.yml
Co-authored-by: Erik Sundell <erik.i.sundell@gmail.com>
> Improve docker workflow naming

- base-notebook/Dockerfile
- base-notebook/start.sh
- base-notebook/test/test_container_options.py
Hi all! Potential fix for https://github.com/jupyter/docker-stacks/issues/1229 for review. Thanks!
> Fix: volumes/files deleted when bind mount to /home/jovyan

- base-notebook/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/1436
> Use latest mambaforge release

- .github/workflows/docker.yml
Fix: https://github.com/jupyter/docker-stacks/issues/1410
> Do not explicitly ask latest docker buildx version

- r-notebook/Dockerfile
The issue seems to be closed, so should work without this hack.
> Remove old bug workaround

- docs/using/recipes.md
ref #1506 
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
> Add recipe for installing custom fonts

- base-notebook/start.sh
Fix: https://github.com/jupyter/docker-stacks/issues/1518
> Remove XDG_CACHE_HOME from start.sh sudo call

- base-notebook/start-singleuser.sh
Cherry-pick of f3aabbe, working through https://github.com/jupyter/docker-stacks/pull/1512#issuecomment-962672049
> start-singleuser.sh: remove JPY_* NOTEBOOK_DIR

- datascience-notebook/Dockerfile
> Update Julia to 1.6.4

- docs/using/common.md
Fix: https://github.com/jupyter/docker-stacks/issues/1541
> Document NOTEBOOK_ARGS

- docs/using/common.md
Adding documentation updates regarding https://github.com/jupyter/docker-stacks/issues/1333
> Documentation updates 

- base-notebook/Dockerfile
- docs/contributing/features.md
- docs/contributing/lint.md
- docs/contributing/packages.md
- docs/contributing/stacks.md
- docs/contributing/tests.md
- docs/maintaining/tasks.md
- docs/using/common.md
- docs/using/recipes.md
- docs/using/running.md
- docs/using/specifics.md
- examples/docker-compose/README.md
- examples/openshift/README.md
- examples/source-to-image/README.md
@trallard please, also take a look, I think you will like this :)
> Cleanup docs

- base-notebook/start.sh
Supersedes #1519
Does this work?:
Closes #1519
> Envvar comments

- .github/workflows/docker-amd64.yml
- .github/workflows/docker.yml
- .github/workflows/sphinx.yml
- .readthedocs.yaml
- Makefile
- docs/conf.py
- docs/contributing/lint.md
- docs/maintaining/tasks.md
- requirements-dev.txt
- requirements-docs.txt
Fix: https://github.com/jupyter/docker-stacks/issues/1597
Alabaster hasn't received any updates in 3 years.
This theme is also not very active, but it was last updated 5 months ago.
I think it looks better and has more modern style.
> Use sphinx_rtd theme and separate docs environment

- docs/using/selecting.md
Added a transformer docker stacks that comes preinstalled with the popular transformers library and other deep learning frameworks
> Add Transformers Notebook

- .github/workflows/sphinx.yml
- docs/conf.py
- requirements-docs.txt
Sorry for creating new PR, I merged docs environment to make this PR easier to follow.
Fix: https://github.com/jupyter/docker-stacks/issues/1597
> Use sphinx-book-theme

- docs/using/recipes.md
Hello,
@mathbunnyru I've checked as you suggested and this is a follow-on PR for #1617.
After a check, I dot not see a reason to keep two recipes for the same thing. The recipe kept permits to create a custom conda env and to register it as a Jupyter kernel whatever the chosen python version (I've tested it with Python 2.7 and it seems to work correctly). So I've kept only one recipe (the initial Python 3) and made some wording changes and some cleaning.
Let me know if it's OK for you.
Best.
> Unique recipe to install a custom conda env

- tests/base-notebook/test_packages.py
- tests/package_helper.py
After this PR tests pass on arm base-notebook image 🎉.
I tested this under m1 mac, should also work fine on arm linux.
> Refactor package helper and fix tests for aarch64

- Makefile
- all-spark-notebook/Dockerfile
- base-notebook/Dockerfile
- binder/Dockerfile
- datascience-notebook/Dockerfile
- minimal-notebook/Dockerfile
- pyspark-notebook/Dockerfile
- r-notebook/Dockerfile
- scipy-notebook/Dockerfile
- tensorflow-notebook/Dockerfile
@consideRatio
This actually reverts your previous PR:
https://github.com/jupyter/docker-stacks/pull/1307
> Do not print git diff on pre-commit fail

- .pre-commit-config.yaml
- base-notebook/jupyter_server_config.py
- tagging/create_manifests.py
- tagging/docker_runner.py
- tagging/get_taggers_and_manifests.py
- tagging/images_hierarchy.py
- tagging/manifests.py
- tagging/tag_image.py
- tagging/taggers.py
- tests/all-spark-notebook/test_spark_notebooks.py
- tests/base-notebook/test_container_options.py
- tests/base-notebook/test_outdated.py
- tests/base-notebook/test_package_managers.py
- tests/base-notebook/test_packages.py
- tests/base-notebook/test_python.py
- tests/base-notebook/test_start_container.py
- tests/conftest.py
- tests/minimal-notebook/data/notebook_math.ipynb
- tests/minimal-notebook/test_nbconvert.py
- tests/package_helper.py
- tests/pyspark-notebook/test_spark.py
- tests/run_tests.py
- tests/scipy-notebook/data/cython/setup.py
- tests/scipy-notebook/data/matplotlib/matplotlib_1.py
- tests/scipy-notebook/data/matplotlib/matplotlib_fonts_1.py
- tests/scipy-notebook/test_extensions.py
- tests/scipy-notebook/test_matplotlib.py
- tests/scipy-notebook/units/unit_pandas.py
- tests/tensorflow-notebook/units/unit_tensorflow.py
isort, requirements-txt-fixer both automatically fix files, so it should be good for developers as well.
> Run pre-commit tools: isort, requirements-txt-fixer

- .github/workflows/docker.yml
This reverts commit c6f0aa1d94a4b07dd02042ad7c58d9c64bd7b278.
> Revert "[TMP] Disable tests (#1675)"

- Makefile
- tagging/README.md
- tagging/create_manifests.py
- tagging/get_taggers_and_manifests.py
- tagging/images_hierarchy.py
- tagging/manifests.py
- tagging/tag_image.py
- tagging/taggers.py
- tests/all-spark-notebook/test_spark_notebooks.py
- tests/base-notebook/test_container_options.py
- tests/base-notebook/test_notebook.py
- tests/base-notebook/test_outdated.py
- tests/base-notebook/test_package_managers.py
- tests/base-notebook/test_packages.py
- tests/base-notebook/test_pandoc.py
- tests/base-notebook/test_python.py
- tests/base-notebook/test_start_container.py
- tests/base-notebook/test_units.py
- tests/datascience-notebook/test_julia.py
- tests/minimal-notebook/test_inkscape.py
- tests/minimal-notebook/test_nbconvert.py
- tests/package_helper.py
- tests/pyspark-notebook/test_spark.py
- tests/run_tests.py
- tests/scipy-notebook/test_cython.py
- tests/scipy-notebook/test_extensions.py
- tests/scipy-notebook/test_matplotlib.py
My motivation is that this way it works well in PyCharm when I open the root of this project.
I'm not a pro in python imports, unfortunately.
> Make tests a module and make imports absolute

- base-notebook/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/1698
> Fix HEALTHCHECK when GEN_CERT=yes

- docs/using/specifics.md
Fix: https://github.com/jupyter/docker-stacks/issues/1369
> Add warning about using local spark mode

- datascience-notebook/Dockerfile
Update to the latest version of Julia
N/A
> Update Julia to 1.7.3

- mypy.ini
- requirements-dev.txt
- tests/base-notebook/test_python.py
We pin `major.minor` python version in the base Dockerfile.
So it makes sense to check this version stays the same.
> Compare major.minor python version to be expected one

- .github/actions/download-manifests/action.yml
- .github/workflows/docker.yml
- README.md
- datascience-notebook/Dockerfile
> Build aarch64 datascience-notebook

- docs/conf.py
> Fix docs default branch

- README.md
- binder/Dockerfile
- docs/using/recipes.md
- docs/using/running.md
- docs/using/selecting.md
- examples/docker-compose/README.md
- examples/docker-compose/notebook/Dockerfile
- examples/make-deploy/Dockerfile
- tagging/README.md
> Improve docs about tags

- .github/workflows/docker-build-test-upload.yml
- .github/workflows/docker-tag-manifest-push.yml
- .github/workflows/hub-overview.yml
- tagging/tag_image.py
- tagging/write_manifest.py
- tests/run_tests.py
> Do not hardcode owner of the image

- datascience-notebook/Dockerfile
Update to the latest version of Julia
N/A
> Update Julia to 1.8.0

- datascience-notebook/Dockerfile
> Update Julia to 1.8.1

- datascience-notebook/Dockerfile
> Update Julia to 1.8.2

- minimal-notebook/Dockerfile
To deal with: https://github.com/jupyter/docker-stacks/issues/1796
I will merge this if the image size increase is small and I will add a recipe to enable clipboard functionality.
> Install xclip to support clipboard functionality

- README.md
> Add info about old versions to docs

- docs/using/selecting.md
- scipy-notebook/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/1804
> add openpyxl to scipy-notebook (#1804)

- pyspark-notebook/Dockerfile
Upgrade Apache Spark from 3.3.0 to 3.3.1
[Release notes](https://spark.apache.org/releases/spark-release-3-3-1.html)
> Upgrade `Spark` to 3.3.1

- docs/maintaining/tasks.md
> Introduce policy to update python version

- .github/workflows/docker-merge-tags.yml
- .github/workflows/docker-tag-manifest-push.yml
- .github/workflows/docker-wiki-update.yml
- .github/workflows/hub-overview.yml
> Show tags for third-party github actions

- .github/workflows/hub-overview.yml
> Update DockerHub overview programmatically

- .github/workflows/hub-overview.yml
> Update DockerHub short descriptions

- .github/workflows/docker-merge-tags.yml
- .github/workflows/docker-tag-manifest-push.yml
- .github/workflows/docker.yml
> Start using matrix in reuseable workflows directly

- datascience-notebook/Dockerfile
> Update Julia to 1.8.3

- base-notebook/Dockerfile
- scipy-notebook/Dockerfile
- tests/base-notebook/test_healthcheck.py
- tests/base-notebook/test_packages.py
- tests/conftest.py
Fix: https://github.com/jupyter/docker-stacks/issues/1851
> Pin jupyter_server>=2.0.0

- tests/base-notebook/test_healthcheck.py
> Check healthcheck in all jupyter applications

- datascience-notebook/Dockerfile
> Update Julia to 1.8.5

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> Improve issue template

- datascience-notebook/Dockerfile
> Install rpy2 on aarch64 as well

- README.md
- binder/Dockerfile
- docs/using/recipes.md
- docs/using/running.md
- docs/using/selecting.md
- examples/docker-compose/README.md
- examples/docker-compose/notebook/Dockerfile
- examples/make-deploy/Dockerfile
> Use date tag in all the examples

- pyspark-notebook/Dockerfile
> Change spark download url to https://dlcdn.apache.org

- datascience-notebook/Dockerfile
- r-notebook/Dockerfile
> Install r-tidymodels on aarch64 images

- .github/workflows/sphinx.yml
- docs/conf.py
- docs/requirements.txt
> Show last_updated in docs

- base-notebook/Dockerfile
> Pin nodejs version

- scipy-notebook/Dockerfile
- tests/base-notebook/test_packages.py
https://github.com/jupyter/docker-stacks/issues/1851
> Remove jupyter_server version fix

- tensorflow-notebook/Dockerfile
> Temporarily pin flatbuffers version

- docs/using/selecting.md
Adding Scala kernel to Community Stacks docs
Fix: https://github.com/jupyter/docker-stacks/issues/1865
- [ x] I have performed a self-review of my code
- [x ] I will try not to use force-push to make the review process easier for reviewers
- [ x] I have updated the documentation for significant changes
> Adding Scala kernel to Community Stacks docs

- .github/workflows/docker-merge-tags.yml
- .github/workflows/docker.yml
- Makefile
- README.md
- docs/images/inherit.svg
- docs/using/selecting.md
> Build aarch64 tensorflow image

- base-notebook/Dockerfile
> Do not pin nodejs version

- tests/base-notebook/test_packages.py
> Try to remove r-sparklyr fix

- tests/all-spark-notebook/test_spark_notebooks.py
> Add local_sparklyr test

- .github/workflows/docker-build-test-upload.yml
> Kill containers and remove stopped ones on aarch64 runners

- pyspark-notebook/Dockerfile
Upgrade Apache Spark from 3.4.0 to 3.4.1
> Upgrade `Apache Spark` to 3.4.1

- .github/actions/load-image/action.yml
- .github/workflows/docker-build-test-upload.yml
- .github/workflows/docker-merge-tags.yml
- .github/workflows/docker-tag-push.yml
- .github/workflows/docker-wiki-update.yml
- Makefile
> Refactor handling of artifacts

- minimal-notebook/setup-scripts/setup-julia.bash
> Update julia version

- docs/using/recipes.md
Fix: https://github.com/jupyter/docker-stacks/issues/1951
> Update Microsoft SQL Server ODBC driver recipe

- .hadolint.yaml
- .pre-commit-config.yaml
- docs/contributing/lint.md
- docs/using/recipe_code/dask_jupyterlab.dockerfile
- docs/using/recipe_code/jupyterhub_version.dockerfile
- docs/using/recipe_code/mamba_install.dockerfile
- docs/using/recipe_code/manpage_install.dockerfile
- docs/using/recipe_code/microsoft_odbc.dockerfile
- docs/using/recipe_code/pip_install.dockerfile
- docs/using/recipe_code/rise_jupyterlab.dockerfile
- docs/using/recipe_code/xgboost.dockerfile
- docs/using/recipes.md
- tensorflow-notebook/Dockerfile
Work on: https://github.com/jupyter/docker-stacks/issues/1324
> Move recipe Dockerfiles to separate files

- docs/contributing/recipes.md
- docs/using/recipes.md
Work on: https://github.com/jupyter/docker-stacks/issues/1324
> Warn outdated recipes might be broken

- .github/workflows/contributed-recipes.yml
Work on: https://github.com/jupyter/docker-stacks/issues/1324
> Build recipes in GitHub Actions

- docs/using/common.md
Fix: https://github.com/jupyter/docker-stacks/issues/1941
> Add docs how to change frontend for JupyterHub singleuser image

- README.md
- docs/using/running.md
Fix: https://github.com/jupyter/docker-stacks/issues/1969
> Add info about root_dir in docs

- .github/workflows/contributed-recipes.yml
- docs/contributing/recipes.md
- docs/using/recipe_code/generate_matrix.py
> Build all contributed recipes automatically

- .github/workflows/contributed-recipes.yml
- docs/using/recipe_code/generate_matrix.py
- docs/using/recipes.md
> Build contributed recipes on aarch64

- images/docker-stacks-foundation/Dockerfile
- images/docker-stacks-foundation/start.sh
- images/pyspark-notebook/Dockerfile
> Small improvements to startup hooks

- images/docker-stacks-foundation/Dockerfile
- images/docker-stacks-foundation/start.sh
I don't change the meaning, only making code more readable.
> Use long options in useradd

- images/docker-stacks-foundation/start.sh
> Specify /bin/bash shell in useradd

- tests/conftest.py
> Use only rv['StatusCode'] to simplify code

- images/base-notebook/jupyter_server_config.py
- tests/scipy-notebook/data/matplotlib/matplotlib_1.py
- tests/scipy-notebook/data/matplotlib/matplotlib_fonts_1.py
> Replace os with pathlib where paths are used

- .github/actions/create-dev-env/action.yml
- .github/workflows/docker-build-test-upload.yml
- .github/workflows/docker-merge-tags.yml
- .github/workflows/docker-tag-push.yml
- .github/workflows/docker-wiki-update.yml
> Simplify create-dev-env by using runner.arch

- .github/workflows/contributed-recipes.yml
- .github/workflows/docker-merge-tags.yml
- .github/workflows/docker-tag-push.yml
- .github/workflows/docker-wiki-update.yml
- .github/workflows/registry-overviews.yml
- .github/workflows/sphinx.yml
This will allow me to first merge potentially breaking changes to my fork, check if they work, and only then merge in the upstream.
I can easily push-force, revert, and do whatever I want in my fork without affecting anyone.
I will have to set up Docker Hub (and Quay.io), but it's worth the trouble.
> Build all workflows in my fork

- images/all-spark-notebook/README.md
- images/base-notebook/README.md
- images/datascience-notebook/README.md
- images/docker-stacks-foundation/README.md
- images/julia-notebook/README.md
- images/minimal-notebook/README.md
- images/pyspark-notebook/README.md
- images/r-notebook/README.md
- images/scipy-notebook/README.md
- images/tensorflow-notebook/README.md
> Add Docker Hub warning

- README.md
> Rearrange parts in README.md to and remove call for maintainers

- tests/docker-stacks-foundation/run-hooks-change/a.sh
- tests/docker-stacks-foundation/run-hooks-change/b.sh
- tests/docker-stacks-foundation/run-hooks-change/c.sh
- tests/docker-stacks-foundation/test_run_hooks.py
> [FAST_BUILD] Test change variable value in run-hooks

- tagging/update_wiki.py
Fix: https://github.com/jupyter/docker-stacks/issues/2025
> Remove old manifests and put everything in folders

- .github/workflows/aarch64-setup.yml
- aarch64-runner/setup.sh
Mostly for fun.
A little bit to make sure the setup script can be used at any time.
> Add workflow to check aarch64 setup script

- README.md
Slight wording change to mention that 2i2c is a non-profit organization
> Mention that 2i2c is a non-profit

- .github/workflows/registry-move.yml
> Add workflow to move some images from Docker Hub to Quay.io

- .github/workflows/docker-tag-push.yml
- tagging/apply_tags.py
> [FAST_BUILD] Remove latest tag in workflow to make local development easier

- README.md
> Add acknowledgement of me :)

- images/docker-stacks-foundation/Dockerfile
Fix: https://github.com/jupyter/docker-stacks/issues/2051
> [FAST_BUILD] [TMP] Fix mamba clean by downloading updated file

- images/scipy-notebook/Dockerfile
> Remove jupyterlab and notebook pins in scipy-notebook

- .pre-commit-config.yaml
- docs/using/specifics.md
- images/pyspark-notebook/Dockerfile
- images/pyspark-notebook/setup_spark.py
- tagging/taggers.py
Fix: https://github.com/jupyter/docker-stacks/issues/2063
Close: https://github.com/jupyter/docker-stacks/issues/1937
> Automatically install latest spark version

- docs/using/common.md
Close: https://github.com/jupyter/docker-stacks/issues/2042
> Document root homedir

- images/base-notebook/Dockerfile
- tests/base-notebook/test_healthcheck.py
- tests/base-notebook/test_start_container.py
- tests/pluto_check.py
> Adjust sleep times

- images/minimal-notebook/setup-scripts/setup-julia-packages.bash
According to https://github.com/JuliaCI/julia-buildkite/blob/main/utilities/build_envs.sh
\-
> Update JULIA_CPU_TARGET for precompiling packages

- docs/using/recipe_code/oracledb.dockerfile
> Update oracledb example

- Makefile
Fixes root container args in new PR per:
https://github.com/jupyter/docker-stacks/pull/2131#discussion_r1713016127
> fix root container arg

- docs/using/recipe_code/microsoft_odbc.dockerfile
- docs/using/recipe_code/oracledb.dockerfile
- docs/using/recipes.md
- images/all-spark-notebook/Dockerfile
- images/docker-stacks-foundation/Dockerfile
- images/pytorch-notebook/cuda11/Dockerfile
- images/pytorch-notebook/cuda12/Dockerfile
- images/tensorflow-notebook/cuda/Dockerfile
Mostly https://docs.docker.com/reference/build-checks/legacy-key-value-format/
Fixes for env values with spaces
> Unify ENV command in Dockerfiles

- images/docker-stacks-foundation/Dockerfile
> Use awk to pin python major.minor version

- tests/conftest.py
> Expect warnings/errors when no_warnings/no_errors is False

- images/pytorch-notebook/cuda12/Dockerfile
> Use pytorch with cuda12.4

- tests/docker-stacks-foundation/test_packages.py
> Remove pandas from EXCLUDED_PACKAGES

- docs/using/recipe_code/oracledb.dockerfile
> Update OracleDB Instant Client version

- docs/using/recipe_code/oracledb.dockerfile
> Use Ububtu 24.04 image for OracleDB Instant Client

- docs/using/recipe_code/microsoft_odbc.dockerfile
> Use Ubuntu 24.04 image for Microsoft ODBC

- .github/workflows/contributed-recipes.yml
- docs/using/recipe_code/custom_environment.dockerfile
- docs/using/recipe_code/dask_jupyterlab.dockerfile
- docs/using/recipe_code/generate_matrix.py
- docs/using/recipe_code/ijavascript.dockerfile
- docs/using/recipe_code/jupyterhub_version.dockerfile
- docs/using/recipe_code/mamba_install.dockerfile
- docs/using/recipe_code/manpage_install.dockerfile
- docs/using/recipe_code/microsoft_odbc.dockerfile
- docs/using/recipe_code/oracledb.dockerfile
- docs/using/recipe_code/pip_install.dockerfile
- docs/using/recipe_code/rise_jupyterlab.dockerfile
- docs/using/recipe_code/spellcheck_notebook_v6.dockerfile
- docs/using/recipe_code/xgboost.dockerfile
> Build contributed recipes in PRs

- .github/workflows/docker.yml
> Don't use matrix.image-variant, use 2 separate variables

- .github/actions/create-dev-env/action.yml
- .github/workflows/pre-commit.yml
- .github/workflows/sphinx.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- mypy.ini
- tagging/docker_runner.py
- tagging/get_taggers_and_manifests.py
- tagging/images_hierarchy.py
- tests/base-notebook/test_healthcheck.py
- tests/base-notebook/test_start_container.py
- tests/conftest.py
- tests/docker-stacks-foundation/test_packages.py
- tests/images_hierarchy.py
- tests/package_helper.py
> Use Python 3.12 for internal code

- .github/workflows/docker-build-test-upload.yml
- .github/workflows/registry-move.yml
> Wrap long commands in GitHub workflows

- tests/hierarchy/images_hierarchy.py
> Fail if test dir doesn't exist

- tagging/utils/docker_runner.py
- tests/image_specific_tests/base-notebook/test_container_options.py
- tests/image_specific_tests/base-notebook/test_start_container.py
- tests/image_specific_tests/docker-stacks-foundation/test_packages.py
- tests/image_specific_tests/docker-stacks-foundation/test_user_options.py
- tests/image_specific_tests/scipy-notebook/test_matplotlib.py
- tests/utils/conda_package_helper.py
- tests/utils/tracked_container.py
> Remove explicit utf-8 from decode() as it's default

- wiki/config.py
- wiki/manifest_time.py
- wiki/update_wiki.py
> [FAST_BUILD] Refactor wiki: create functions, better logs and names

- README.md
Mainly to allow workflows to run automatically.
See https://github.com/jupyter/docker-stacks/pull/2243#issuecomment-2682605163.
See [how it renders](https://github.com/jupyter/docker-stacks/blob/38049e6810274f74b466e849b7e7dc2d298b6d98/README.md).
> docs: Add badge for supported Python versions in `README.md`

- tests/by_image/all-spark-notebook/test_spark_notebooks.py
- tests/by_image/base-notebook/test_container_options.py
- tests/by_image/base-notebook/test_healthcheck.py
- tests/by_image/base-notebook/test_ips.py
- tests/by_image/base-notebook/test_pandoc.py
- tests/by_image/base-notebook/test_start_container.py
- tests/by_image/docker-stacks-foundation/test_python_version.py
- tests/by_image/docker-stacks-foundation/test_run_hooks.py
- tests/by_image/docker-stacks-foundation/test_units.py
- tests/by_image/docker-stacks-foundation/test_user_options.py
- tests/by_image/minimal-notebook/test_nbconvert.py
- tests/by_image/pyspark-notebook/test_spark.py
- tests/by_image/scipy-notebook/test_cython.py
- tests/by_image/scipy-notebook/test_extensions.py
- tests/by_image/scipy-notebook/test_matplotlib.py
- tests/shared_checks/R_mimetype_check.py
- tests/utils/conda_package_helper.py
- tests/utils/run_command.py
> Do not allocate TTY in tests if not needed

- tests/by_image/docker-stacks-foundation/test_packages.py
> Cleanup EXCLUDED_PACKAGES list

- tagging/apps/merge_tags.py
> Only create manifests when images are pushed to registry

- docs/using/custom-images.md
- docs/using/recipe_code/custom_environment.dockerfile
- docs/using/recipe_code/docker-bake.custom-python.hcl
- docs/using/recipe_code/jupyterhub_version.dockerfile
> Update custom recipes versions

- requirements-dev.txt
- tests/by_image/all-spark-notebook/test_spark_r_nbconvert.py
> Use pytest-rerunfailures for flaky tests

- .github/workflows/docker.yml
> Make docker tag-push depend on contributed recipes in CI

- images/docker-stacks-foundation/Dockerfile
> Pin libxml2 to avoid ABI breakage

- .github/workflows/docker-tag-push.yml
> Retry login operation in docker-tag-push.yml

- tests/by_image/pytorch-notebook/units/unit_pytorch.py
> Improve pytorch unit test

- images/pytorch-notebook/cuda12/Dockerfile
> Upgrade CUDA version used in PyTorch cuda12-variant to 12.6

- .github/actions/apply-single-tags/action.yml
- .github/workflows/docker-tag-push.yml
> Generate SBOM correctly for different platforms/variants

- .github/ISSUE_TEMPLATE/blank.yml
> Fix blank issue

- .github/ISSUE_TEMPLATE/blank.yml
> Validate if maintainer in blank issue

- .github/ISSUE_TEMPLATE/blank.yml
> Make checkboxes options array

- SECURITY.md
> Update security.md to follow GitHub template

- .github/actions/free-disk-space/action.yml
- .github/dependabot.yml
- .github/workflows/docker-build-test-upload.yml
- .github/workflows/docker-tag-push.yml
> Implement free-disk-space using rmz
